### ISSUE TITLE
Snake demo issue; FileNotFoundError: [Errno 2] No such file or directory: 'node_modules/.bin/browsers'

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [geekan/MetaGPT#1052]
When I tried to run a demo using WSLg in Docker on WSL, I encountered the following error:

How can I fix this issue?

```bash
2024-03-20 02:39:20.007 | INFO     | metagpt.utils.file_repository:save:60 - save to: /app/metagpt/workspace/20240320023843/resources/prd/20240320023917.md
2024-03-20 02:39:20.009 | INFO     | metagpt.roles.role:_act:399 - Bob(Architect): to do WriteDesign(WriteDesign)
2024-03-20 02:39:20.064 | INFO     | metagpt.actions.design_api:run:67 - Nothing has changed.
2024-03-20 02:39:20.066 | INFO     | metagpt.roles.role:_act:399 - Eve(Project Manager): to do WriteTasks(WriteTasks)
2024-03-20 02:39:20.121 | INFO     | metagpt.actions.project_management:run:54 - Nothing has changed.
2024-03-20 02:39:20.256 | INFO     | metagpt.utils.git_repository:archive:168 - Archive: ['node_modules/.bin/browsers', 'node_modules/.bin/extract-zip', 'node_modules/.bin/js-yaml', 'node_modules/.bin/mmdc', 'node_modules/.package-lock.json', 'node_modules/@babel/code-frame/LICENSE', 'node_modules/@babel/code-frame/README.md', 'node_modules/@babel/code-frame/node_modules/ansi-styles/index.js', 'node_modules/@babel/code-frame/node_modules/ansi-styles/license', 'node_modules/@babel/code-frame/node_modules/ansi-styles/package.json', 'node_modules/@babel/code-frame/node_modules/ansi-styles/readme.md', 'node_modules/@babel/code-frame/node_modules/chalk/index.js', 'nod

...

2024-03-20 02:39:20.281 | ERROR    | metagpt.utils.common:wrapper:553 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/app/metagpt/metagpt/utils/common.py", line 548, in wrapper
    result = await func(self, *args, **kwargs)
  File "/app/metagpt/metagpt/team.py", line 135, in run
    self.env.archive(auto_archive)
FileNotFoundError: [Errno 2] No such file or directory: 'node_modules/.bin/browsers'
```

**Comment by iorisa** [comment]
It seems caused by this issue: #1035.
Try out main branch.
