### ISSUE TITLE
MetaGPT is failing to run with an error that it is not able to find the model. Correct Model and API Key has been provided in the cofiguration.

### ISSUE THREAD

**Issue by nilukush** [geekan/MetaGPT#1085]
**Bug description**
024-03-23 14:43:54.511 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 0.689(s), this was the 1st time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:43:55.262 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 1.439(s), this was the 2nd time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:43:57.329 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 3.506(s), this was the 3rd time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:44:00.070 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 6.248(s), this was the 4th time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:44:00.694 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 6.871(s), this was the 5th time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:44:04.228 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 10.405(s), this was the 6th time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:44:04.229 | WARNING  | metagpt.utils.common:wrapper:572 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-03-23 14:44:04.232 | ERROR    | metagpt.utils.common:wrapper:554 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/Users/nileshkumar/anaconda3/lib/python3.10/site-packages/metagpt/utils/common.py", line 549, in wrapper
    result = await func(self, *args, **kwargs)
  File "/Users/nileshkumar/anaconda3/lib/python3.10/site-packages/metagpt/team.py", line 134, in run
    await self.env.run()
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Bug solved method**

**Environment information**

- LLM type and model name: ggpt-3.5-turbo
- System version: Macos
- Python version: Python 3.10.9

- packages version:
- installation method: 
1. Create a new virtual environment to isolate the dependencies for your project. You can use tools like `venv` or `conda` to create a virtual environment.

   For example, using `venv`:
   ```
   python -m venv myenv
   source myenv/bin/activate
   ```

2. Inside the virtual environment, upgrade `pip` to the latest version:
   ```
   pip install --upgrade pip
   ```

3. Install the required packages one by one, specifying the compatible versions mentioned in the error message:
   ```
   pip install websockets~=12.0
   pip install tokenizers!=0.11.3,<0.14,>=0.11.1
   ```

4. Install the `metagpt` package:
   ```
   pip install metagpt==0.7.6
   ```

5. Install the `transformers` package:
   ```
   pip install transformers==4.24.0
   ```

**Screenshots or logs**

024-03-23 14:43:54.511 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 0.689(s), this was the 1st time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:43:55.262 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 1.439(s), this was the 2nd time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:43:57.329 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 3.506(s), this was the 3rd time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:44:00.070 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 6.248(s), this was the 4th time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:44:00.694 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 6.871(s), this was the 5th time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:44:04.228 | ERROR    | metagpt.utils.common:log_it:477 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 10.405(s), this was the 6th time calling it. exp: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-03-23 14:44:04.229 | WARNING  | metagpt.utils.common:wrapper:572 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-03-23 14:44:04.232 | ERROR    | metagpt.utils.common:wrapper:554 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/Users/nileshkumar/anaconda3/lib/python3.10/site-packages/metagpt/utils/common.py", line 549, in wrapper
    result = await func(self, *args, **kwargs)
  File "/Users/nileshkumar/anaconda3/lib/python3.10/site-packages/metagpt/team.py", line 134, in run
    await self.env.run()
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `ggpt-3.5-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by geekan** [comment]
`ggpt-3.5-turbo` -> `gpt-3.5-turbo`

**Comment by nilukush** [comment]
I made it work with Claude / Anthropic. We can close.
