### ISSUE TITLE
Keyerror Anthropic

### ISSUE THREAD

**Issue by iitrsamrat** [geekan/MetaGPT#1104]
**Bug description**
Can't load Claude from config, throws key error.

**Environment information**

config
`
llm:
  api_type: "anthropic"
  api_key: "xxxxx"
  model: "claude-3-opus-20240229"
  base_url: "https://api.anthropic.com"
`

**Screenshots or logs**
`
2024-03-25 20:11:00.818 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to /Users/samsaha2
Traceback (most recent call last):
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt/roles/researcher.py", line 126, in <module>
    fire.Fire(main)
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/fire/core.py", line 679, in _CallAndUpdateTrace
    component = loop.run_until_complete(fn(*varargs, **kwargs))
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt/roles/researcher.py", line 123, in main
    role = Researcher(language=language)
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt/roles/researcher.py", line 36, in __init__
    super().__init__(**kwargs)
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt/roles/role.py", line 167, in validate_role_extra
    self._process_role_extra()
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt/roles/role.py", line 177, in _process_role_extra
    self.llm.system_prompt = self._get_prefix()
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt/context_mixin.py", line 95, in llm
    self.private_llm = self.context.llm_with_cost_manager_from_llm_config(self.config.llm)
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt/context.py", line 94, in llm_with_cost_manager_from_llm_config
    llm = create_llm_instance(llm_config)
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt/provider/llm_provider_registry.py", line 36, in create_llm_instance
    return LLM_REGISTRY.get_provider(config.api_type)(config)
  File "/Users/samsaha2/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt/provider/llm_provider_registry.py", line 21, in get_provider
    return self.providers[enum]
KeyError: <LLMType.ANTHROPIC: 'anthropic'>
`

**Comment by iitrsamrat** [comment]
this problem happens with pip install

after I installed from git above problem resolved. so closing this but still Claude does not work.
