### ISSUE TITLE
Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' exp: 1 validation error for PM_NODE_AN  Value error, Missing fields

### ISSUE THREAD

**Issue by 45592858** [geekan/MetaGPT#1152]
**Bug description**
Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 95.869(s), this was the 6th time calling it. exp: 1 validation error for PM_NODE_AN  Value error, Missing fields

**Bug solved method**
Terminated when run: metagpt --project-name 'jqdlhwap' --project-path '/app/metagpt/workspace/jqdlhwap' [IDEA]

**Environment information**
"docker compose up -d" after clone

- LLM type and model name:  zhipu-api / GLM-4
- System version:
- Python version:
- MetaGPT version or branch: main

`run in docker`

- packages version:
- installation method: 

**Screenshots or logs**
2024-04-02 03:22:23.470 | INFO     | metagpt.utils.cost_manager:update_cost:52 - Total running cost: $0.143 | Max budget: $10.000 | Current cost: $0.024, prompt_tokens: 1156, completion_tokens: 407
2024-04-02 03:22:23.472 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 95.869(s), this was the 6th time calling it. exp: 1 validation error for PM_NODE_AN
  Value error, Missing fields: {'Required Python packages', 'Required Other language third-party packages'} [type=value_error, input_value={'Required Front-end pack...anagement is required.'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/value_error
2024-04-02 03:22:23.472 | WARNING  | metagpt.utils.common:wrapper:571 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-04-02 03:22:23.474 | ERROR    | metagpt.utils.common:wrapper:553 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/metagpt/metagpt/actions/action_node.py", line 434, in _aask_v1
    instruct_content = output_class(**parsed_data)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PM_NODE_AN
  Value error, Missing fields: {'Required Python packages', 'Required Other language third-party packages'} [type=value_error, input_value={'Required Front-end pack...anagement is required.'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/value_error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/metagpt/metagpt/utils/common.py", line 562, in wrapper
    return await func(self, *args, **kwargs)
  File "/app/metagpt/metagpt/roles/role.py", line 558, in run
    rsp = await self.react()
tenacity.RetryError: RetryError[<Future at 0x7f4d9e12d640 state=finished raised ValidationError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/metagpt/metagpt/utils/common.py", line 548, in wrapper
    result = await func(self, *args, **kwargs)
  File "/app/metagpt/metagpt/team.py", line 134, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/metagpt/metagpt/actions/action_node.py", line 434, in _aask_v1
    instruct_content = output_class(**parsed_data)
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PM_NODE_AN
  Value error, Missing fields: {'Required Python packages', 'Required Other language third-party packages'} [type=value_error, input_value={'Required Front-end pack...anagement is required.'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/value_error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/metagpt/metagpt/utils/common.py", line 562, in wrapper
    return await func(self, *args, **kwargs)
  File "/app/metagpt/metagpt/roles/role.py", line 558, in run
    rsp = await self.react()
  File "/app/metagpt/metagpt/roles/role.py", line 525, in react
    rsp = await self._react()
  File "/app/metagpt/metagpt/roles/role.py", line 471, in _react
    rsp = await self._act()
  File "/app/metagpt/metagpt/roles/role.py", line 400, in _act
    response = await self.rc.todo.run(self.rc.history)
  File "/app/metagpt/metagpt/actions/project_management.py", line 43, in run
    task_doc = await self._update_tasks(filename=filename)
  File "/app/metagpt/metagpt/actions/project_management.py", line 66, in _update_tasks
    rsp = await self._run_new_tasks(context=system_design_doc.content)
  File "/app/metagpt/metagpt/actions/project_management.py", line 76, in _run_new_tasks
    node = await PM_NODE.fill(context, self.llm, schema=self.prompt_schema)
  File "/app/metagpt/metagpt/actions/action_node.py", line 505, in fill
    return await self.simple_fill(schema=schema, mode=mode, images=images, timeout=timeout, exclude=exclude)
  File "/app/metagpt/metagpt/actions/action_node.py", line 457, in simple_fill
    content, scontent = await self._aask_v1(
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f4d9e12d640 state=finished raised ValidationError>]

**Comment by iorisa** [comment]
The response from the large model is missing the field corresponding to "Required Python packages".
There's an issue with the response from the large model.

**Comment by 45592858** [comment]
Then? Close ^-^

**Comment by jackiezhangcn** [comment]
any solution provided?

**Comment by moonlightnoodles** [comment]
any solution provided?

**Comment by qxk925** [comment]
how to resolve？
