### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by AIMinuteMind** [geekan/MetaGPT#118]
安装好MetaGPT后第一次尝试出现了下面的错误：
2023-08-04 22:11:24.677 | INFO     | metagpt.roles.role:_act:166 - Alice(Product Manager): ready to WritePRD
Traceback (most recent call last):
  File "C:\Users\yueqi\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000016B23127D80> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\yueqi\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000016B23127C60> still has pending operation at deallocation, the process may crash

哪位大神有解决方法呀，跪求！

**Comment by geekan** [comment]
8. PRD卡住 / 无法访问 / 连接中断
  1. OPENAI_API_BASE 官方地址为 https://api.openai.com/v1
  2. 如果自己的环境中OPENAI_API_BASE官方地址不可访问（可以通过curl验证），那么建议配置使用 [openai-forward](https://github.com/beidongjiedeguang/openai-forward) 等库给出的反向代理OPENAI_API_BASE，例如 OPENAI_API_BASE: "https://api.openai-forward.com/v1"
  3. 如果自己的环境中OPENAI_API_BASE官方地址不可访问（可以通过curl验证），还有一种可选的办法是配置 OPENAI_PROXY 参数，这样就可以通过本地代理来访问官方的OPENAI_API_BASE。如果不需要通过代理访问，请不要开启这个配置；如果需要通过代理访问，请把它改成你的正确的代理地址。注意，开启OPENAI_PROXY时，不要设置OPENAI_API_BASE
  4. 注意：OpenAI的默认API设计尾部会有个v1，正确配置示例： OPENAI_API_BASE: "[https://api.openai.com/v1](https://api.openai-forward.com/v1)"
