### ISSUE TITLE
RAG Faiss AssertionError

### ISSUE THREAD

**Issue by GG-Lizen** [geekan/MetaGPT#1213]
**Environment information**

- LLM type and model name: ollama ,nomic-embed-text
- System version:win 11 
- Python version:3.9
- MetaGPT version or branch:0.8

**Bug description**

run code as below
```
import asyncio
from metagpt.rag.engines import SimpleEngine
from metagpt.rag.schema import FAISSRetrieverConfig
from metagpt.const import EXAMPLE_DATA_PATH
DOC_PATH = EXAMPLE_DATA_PATH / "rag/travel.txt"
async def main():
    engine = SimpleEngine.from_docs(input_files=[DOC_PATH], retriever_configs=[FAISSRetrieverConfig()])
    answer = await engine.aquery("What does Bob like?")
    print(answer)

if __name__ == "__main__":
    asyncio.run(main())
```
occur AssertionError
```
Traceback (most recent call last):
  File "E:\MyTask\Metagpt\MetaGPT-0.8.0\examples\rag_test.py", line 25, in <module>
    asyncio.run(main())
  File "D:\Dev_Software\Anaconda\envs\metagpt\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Dev_Software\Anaconda\envs\metagpt\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\MyTask\Metagpt\MetaGPT-0.8.0\examples\rag_test.py", line 15, in main
    SimpleEngine.from_docs(input_files=[DOC_PATH], retriever_configs=retriever_configs).persist(persist_dir)
  File "e:\mytask\metagpt\metagpt-0.8.0\metagpt\rag\engines\simple.py", line 111, in from_docs
    return cls._from_index(index, llm=llm, retriever_configs=retriever_configs, ranker_configs=ranker_configs)
  File "e:\mytask\metagpt\metagpt-0.8.0\metagpt\rag\engines\simple.py", line 211, in _from_index
    retriever = get_retriever(configs=retriever_configs, index=index)  # Default index.as_retriever
  File "e:\mytask\metagpt\metagpt-0.8.0\metagpt\rag\factories\retriever.py", line 52, in get_retriever
    retrievers = super().get_instances(configs, **kwargs)
  File "e:\mytask\metagpt\metagpt-0.8.0\metagpt\rag\factories\base.py", line 18, in get_instances
    return [self.get_instance(key, **kwargs) for key in keys]
  File "e:\mytask\metagpt\metagpt-0.8.0\metagpt\rag\factories\base.py", line 18, in <listcomp>
    return [self.get_instance(key, **kwargs) for key in keys]
  File "e:\mytask\metagpt\metagpt-0.8.0\metagpt\rag\factories\base.py", line 45, in get_instance
    return creator(key, **kwargs)
  File "e:\mytask\metagpt\metagpt-0.8.0\metagpt\rag\factories\retriever.py", line 61, in _create_faiss_retriever
    config.index = self._build_index_from_vector_store(config, vector_store, **kwargs)
  File "e:\mytask\metagpt\metagpt-0.8.0\metagpt\rag\factories\retriever.py", line 93, in _build_index_from_vector_store
    new_index = VectorStoreIndex(
  File "D:\Dev_Software\Anaconda\envs\metagpt\lib\site-packages\llama_index\core\indices\vector_store\base.py", line 74, in __init__
    super().__init__(
  File "D:\Dev_Software\Anaconda\envs\metagpt\lib\site-packages\llama_index\core\indices\base.py", line 91, in __init__
    index_struct = self.build_index_from_nodes(
  File "D:\Dev_Software\Anaconda\envs\metagpt\lib\site-packages\llama_index\core\indices\vector_store\base.py", line 307, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **insert_kwargs)
  File "D:\Dev_Software\Anaconda\envs\metagpt\lib\site-packages\llama_index\core\indices\vector_store\base.py", line 279, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "D:\Dev_Software\Anaconda\envs\metagpt\lib\site-packages\llama_index\core\indices\vector_store\base.py", line 233, in _add_nodes_to_index
    new_ids = self._vector_store.add(nodes_batch, **insert_kwargs)
  File "D:\Dev_Software\Anaconda\envs\metagpt\lib\site-packages\llama_index\vector_stores\faiss\base.py", line 121, in add
    self._faiss_index.add(text_embedding_np)
  File "D:\Dev_Software\Anaconda\envs\metagpt\lib\site-packages\faiss\class_wrappers.py", line 228, in replacement_add
    assert d == self.d
AssertionError
```
But when using BM25 instead of Faiss, it runs well.

**Comment by seehi** [comment]
Try the following code.
```
import asyncio
from metagpt.rag.engines import SimpleEngine
from metagpt.rag.schema import FAISSRetrieverConfig
from metagpt.const import EXAMPLE_DATA_PATH
DOC_PATH = EXAMPLE_DATA_PATH / "rag/travel.txt"
async def main():
    engine = SimpleEngine.from_docs(input_files=[DOC_PATH], retriever_configs=[FAISSRetrieverConfig(dimensions=768)])
    answer = await engine.aquery("What does Bob like?")
    print(answer)

if __name__ == "__main__":
    asyncio.run(main())
```

Need to set `dimensions` in some ollama's models, the value can be obtained through the following code.
```python
from llama_index.embeddings.ollama import OllamaEmbedding

embedding = OllamaEmbedding(base_url="http://localhost:11434", model_name="nomic-embed-text")
print(len(embedding.get_query_embedding("1")))

**Comment by GG-Lizen** [comment]
> Try the following code.
> 
> ```
> import asyncio
> from metagpt.rag.engines import SimpleEngine
> from metagpt.rag.schema import FAISSRetrieverConfig
> from metagpt.const import EXAMPLE_DATA_PATH
> DOC_PATH = EXAMPLE_DATA_PATH / "rag/travel.txt"
> async def main():
>     engine = SimpleEngine.from_docs(input_files=[DOC_PATH], retriever_configs=[FAISSRetrieverConfig(dimensions=768)])
>     answer = await engine.aquery("What does Bob like?")
>     print(answer)
> 
> if __name__ == "__main__":
>     asyncio.run(main())
> ```
> 
> Need to set `dimensions` in some ollama's models, the value can be obtained through the following code.
> 
> ```python
> from llama_index.embeddings.ollama import OllamaEmbedding
> 
> embedding = OllamaEmbedding(base_url="http://localhost:11434", model_name="nomic-embed-text")
> print(len(embedding.get_query_embedding("1")))
> ```

grateful ！
