### ISSUE TITLE
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config

### ISSUE THREAD

**Issue by 1027548366** [geekan/MetaGPT#1220]
D:\MetaGPT-main\venv\Scripts\python.exe D:/MetaGPT-main/test.py
2024-04-23 17:14:39.661 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to D:\MetaGPT-main
Traceback (most recent call last):
  File "D:\MetaGPT-main\test.py", line 3, in <module>
    repo: ProjectRepo = generate_repo("Create a 2048 game")  # or ProjectRepo("<path>")
  File "D:\MetaGPT-main\metagpt\software_company.py", line 30, in generate_repo
    from metagpt.config2 import config
  File "D:\MetaGPT-main\metagpt\config2.py", line 164, in <module>
    config = Config.default()
  File "D:\MetaGPT-main\metagpt\config2.py", line 106, in default
    return Config(**final)
  File "D:\MetaGPT-main\venv\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
llm.api_key
  Value error, Please set your API key in config2.yaml [type=value_error, input_value='YOUR_API_KEY', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/value_error

I've written the config as to why this is still the case？？？
![微信图片_20240423172525](https://github.com/geekan/MetaGPT/assets/91006305/804b3f17-98b4-4137-9487-475ead58560b)

**Comment by seehi** [comment]
Try to create .metagpt in the user's root directory, such as `C:\Users\x\.metagpt\config2.yaml`.
