### ISSUE TITLE
No result prompt in local with open_llm

### ISSUE THREAD

**Issue by Almeyric** [geekan/MetaGPT#1227]
**Bug description**
Hello,

I installed and configured MetaGPT on a VM under vmWare. However, I end up with the errors below.
I saw topic 838 which ended up with the same errors.
Except that here I am local and not with external AI.

**Environment information**

2 vCPU & 6 GB
prompt minconda

- LLM type and model name: open_llm - llama2-13b
- System version: W10 v22h2
- Python version: 3.9.13
- MetaGPT version or branch: clone v0.8

- packages version:
- installation method: pip install

**Screenshots or logs**
```
(metagpt) c:\metagpt>python c:\metagpt\metagpt\software_company.py "write a cli snake game based on pygame"
2024-04-25 10:26:26.882 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to c:\metagpt
2024-04-25 10:26:39.091 | INFO     | metagpt.team:invest:93 - Investment: $3.0.
2024-04-25 10:26:39.095 | INFO     | metagpt.roles.role:_act:396 - Alice(Product Manager): to do PrepareDocuments(PrepareDocuments)
2024-04-25 10:26:39.560 | INFO     | metagpt.utils.file_repository:save:57 - save to: C:\metagpt\workspace\20240425102639\docs\requirement.txt
2024-04-25 10:26:39.576 | INFO     | metagpt.roles.role:_act:396 - Alice(Product Manager): to do WritePRD(WritePRD)
2024-04-25 10:26:39.576 | INFO     | metagpt.actions.write_prd:run:86 - New requirement detected: write a cli snake game based on pygame
2024-04-25 10:26:48.291 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 8.703(s), this was the 1st time calling it.
2024-04-25 10:26:57.782 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 18.188(s), this was the 2nd time calling it.
2024-04-25 10:27:08.232 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 28.641(s), this was the 3rd time calling it.
2024-04-25 10:27:19.982 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 40.391(s), this was the 4th time calling it.
2024-04-25 10:27:36.116 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 56.532(s), this was the 5th time calling it.
2024-04-25 10:27:59.703 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 80.110(s), this was the 6th time calling it.
2024-04-25 10:27:59.703 | ERROR    | metagpt.utils.common:log_and_reraise:818 - Retry attempts exhausted. Last exception: Connection error.
2024-04-25 10:27:59.703 | WARNING  | metagpt.utils.common:log_and_reraise:819 -
Recommend going to https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4#part-XdatdVlhEojeAfxaaEZcMV3ZniQ
See FAQ 5.8

2024-04-25 10:27:59.703 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 80.110(s), this was the 1st time calling it. exp: Connection error.
2024-04-25 10:28:08.514 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 8.562(s), this was the 1st time calling it.
2024-04-25 10:28:18.294 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 18.343(s), this was the 2nd time calling it.
2024-04-25 10:28:28.638 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 28.687(s), this was the 3rd time calling it.
2024-04-25 10:28:41.296 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 41.343(s), this was the 4th time calling it.
2024-04-25 10:28:50.318 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 50.375(s), this was the 5th time calling it.
2024-04-25 10:29:03.046 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 63.093(s), this was the 6th time calling it.
2024-04-25 10:29:03.046 | ERROR    | metagpt.utils.common:log_and_reraise:818 - Retry attempts exhausted. Last exception: Connection error.
2024-04-25 10:29:03.046 | WARNING  | metagpt.utils.common:log_and_reraise:819 -
Recommend going to https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4#part-XdatdVlhEojeAfxaaEZcMV3ZniQ
See FAQ 5.8

2024-04-25 10:29:03.046 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 143.453(s), this was the 2nd time calling it. exp: Connection error.
2024-04-25 10:29:12.455 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 8.875(s), this was the 1st time calling it.
2024-04-25 10:29:21.287 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 17.718(s), this was the 2nd time calling it.
2024-04-25 10:29:30.887 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 27.312(s), this was the 3rd time calling it.
2024-04-25 10:29:40.908 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 37.328(s), this was the 4th time calling it.
2024-04-25 10:29:55.125 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 51.547(s), this was the 5th time calling it.
2024-04-25 10:30:08.772 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 65.203(s), this was the 6th time calling it.
2024-04-25 10:30:08.772 | ERROR    | metagpt.utils.common:log_and_reraise:818 - Retry attempts exhausted. Last exception: Connection error.
2024-04-25 10:30:08.772 | WARNING  | metagpt.utils.common:log_and_reraise:819 -
Recommend going to https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4#part-XdatdVlhEojeAfxaaEZcMV3ZniQ
See FAQ 5.8

2024-04-25 10:30:08.772 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 209.188(s), this was the 3rd time calling it. exp: Connection error.
2024-04-25 10:30:19.932 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 8.687(s), this was the 1st time calling it.
2024-04-25 10:30:28.975 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 17.734(s), this was the 2nd time calling it.
2024-04-25 10:30:38.376 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 27.125(s), this was the 3rd time calling it.
2024-04-25 10:30:50.189 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 38.937(s), this was the 4th time calling it.
2024-04-25 10:31:05.540 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 54.296(s), this was the 5th time calling it.
2024-04-25 10:31:22.626 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 71.375(s), this was the 6th time calling it.
2024-04-25 10:31:22.626 | ERROR    | metagpt.utils.common:log_and_reraise:818 - Retry attempts exhausted. Last exception: Connection error.
2024-04-25 10:31:22.626 | WARNING  | metagpt.utils.common:log_and_reraise:819 -
Recommend going to https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4#part-XdatdVlhEojeAfxaaEZcMV3ZniQ
See FAQ 5.8

2024-04-25 10:31:22.626 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 283.032(s), this was the 4th time calling it. exp: Connection error.
2024-04-25 10:31:38.652 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 8.906(s), this was the 1st time calling it.
2024-04-25 10:31:47.716 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 17.968(s), this was the 2nd time calling it.
2024-04-25 10:31:57.254 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 27.515(s), this was the 3rd time calling it.
2024-04-25 10:32:08.564 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 38.812(s), this was the 4th time calling it.
2024-04-25 10:32:18.005 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 48.265(s), this was the 5th time calling it.
2024-04-25 10:32:40.706 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 70.953(s), this was the 6th time calling it.
2024-04-25 10:32:40.706 | ERROR    | metagpt.utils.common:log_and_reraise:818 - Retry attempts exhausted. Last exception: Connection error.
2024-04-25 10:32:40.706 | WARNING  | metagpt.utils.common:log_and_reraise:819 -
Recommend going to https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4#part-XdatdVlhEojeAfxaaEZcMV3ZniQ
See FAQ 5.8

2024-04-25 10:32:40.706 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 361.110(s), this was the 5th time calling it. exp: Connection error.
2024-04-25 10:33:03.519 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 8.734(s), this was the 1st time calling it.
2024-04-25 10:33:13.374 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 18.594(s), this was the 2nd time calling it.
2024-04-25 10:33:23.791 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 29.015(s), this was the 3rd time calling it.
2024-04-25 10:33:36.818 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 42.047(s), this was the 4th time calling it.
2024-04-25 10:33:51.868 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 57.094(s), this was the 5th time calling it.
2024-04-25 10:34:09.156 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.openai_api.OpenAILLM.acompletion_text' after 74.375(s), this was the 6th time calling it.
2024-04-25 10:34:09.156 | ERROR    | metagpt.utils.common:log_and_reraise:818 - Retry attempts exhausted. Last exception: Connection error.
2024-04-25 10:34:09.156 | WARNING  | metagpt.utils.common:log_and_reraise:819 -
Recommend going to https://deepwisdom.feishu.cn/wiki/MsGnwQBjiif9c3koSJNcYaoSnu4#part-XdatdVlhEojeAfxaaEZcMV3ZniQ
See FAQ 5.8

2024-04-25 10:34:09.156 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 449.563(s), this was the 6th time calling it. exp: Connection error.
2024-04-25 10:34:09.172 | WARNING  | metagpt.utils.common:wrapper:649 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-04-25 10:34:09.531 | ERROR    | metagpt.utils.common:wrapper:631 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\metagpt\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\tools\miniconda3\envs\metagpt\lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\metagpt\lib\site-packages\openai\_base_client.py", line 1339, in _request
    response = await self._client.send(
  File "C:\tools\miniconda3\envs\metagpt\lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\metagpt\lib\site-packages\metagpt-0.8.0-py3.9.egg\metagpt\utils\common.py", line 626, in wrapper
    result = await func(self, *args, **kwargs)
  File "C:\tools\miniconda3\envs\metagpt\lib\site-packages\metagpt-0.8.0-py3.9.egg\metagpt\team.py", line 131, in run
    await self.env.run()
openai.APIConnectionError: Connection error.
```

**Comment by seehi** [comment]
Make sure the open_llm service port can be connected, such as testing with telnet: `telnet {OPEN_LLM_IP} {OPEN_LLM_PORT}`.

**Comment by Almeyric** [comment]
Hello, in fact it wasn't filming. But failed to spin it.

So I moved to Ollama with the llama3 model. This works, takes time to respond between 2-3 minutes (material resources problem).

I modified the config2 file with the config2.example model.

Execution is faster, I have the creation of the folders but stalls on a method..

Here is the result :

`(metagpt-p311) c:\metagpt-p311\MetaGPT>python  c:\metagpt-p311\Metagpt\metagpt\software_company.py "write a cli snake game based on pygame"
2024-04-30 14:51:32.229 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to c:\metagpt-p311\MetaGPT
2024-04-30 14:51:42.289 | INFO     | metagpt.team:invest:90 - Investment: $3.0.
2024-04-30 14:51:42.296 | INFO     | metagpt.roles.role:_act:391 - Alice(Product Manager): to do PrepareDocuments(PrepareDocuments)
2024-04-30 14:51:42.671 | INFO     | metagpt.utils.file_repository:save:57 - save to: C:\metagpt-p311\MetaGPT\workspace\20240430145142\docs\requirement.txt
2024-04-30 14:51:42.679 | INFO     | metagpt.roles.role:_act:391 - Alice(Product Manager): to do WritePRD(WritePRD)
2024-04-30 14:51:42.693 | INFO     | metagpt.actions.write_prd:run:86 - New requirement detected: write a cli snake game based on pygame
2024-04-30 14:51:42.721 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 0.031(s), this was the 1st time calling it. exp: 'async for' requires an object with __aiter__ method, got bytes
2024-04-30 14:51:43.293 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 0.594(s), this was the 2nd time calling it. exp: 'async for' requires an object with __aiter__ method, got bytes
2024-04-30 14:51:43.434 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 0.734(s), this was the 3rd time calling it. exp: 'async for' requires an object with __aiter__ method, got bytes
2024-04-30 14:51:45.504 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 2.813(s), this was the 4th time calling it. exp: 'async for' requires an object with __aiter__ method, got bytes
2024-04-30 14:51:49.762 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 7.063(s), this was the 5th time calling it. exp: 'async for' requires an object with __aiter__ method, got bytes
2024-04-30 14:52:00.826 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 18.141(s), this was the 6th time calling it. exp: 'async for' requires an object with __aiter__ method, got bytes
2024-04-30 14:52:00.830 | WARNING  | metagpt.utils.common:wrapper:649 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-04-30 14:52:00.847 | ERROR    | metagpt.utils.common:wrapper:631 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\actions\action_node.py", line 420, in _aask_v1
    content = await self.llm.aask(prompt, system_msgs, images=images, timeout=timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'async for' requires an object with __aiter__ method, got bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\utils\common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\roles\role.py", line 550, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
tenacity.RetryError: RetryError[<Future at 0x25fee27ec10 state=finished raised TypeError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\utils\common.py", line 626, in wrapper
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\team.py", line 134, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\actions\action_node.py", line 420, in _aask_v1
    content = await self.llm.aask(prompt, system_msgs, images=images, timeout=timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\provider\base_llm.py", line 150, in aask
    rsp = await self.acompletion_text(message, stream=stream, timeout=self.get_timeout(timeout))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\provider\base_llm.py", line 200, in acompletion_text
    return await self._achat_completion_stream(messages, timeout=self.get_timeout(timeout))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\provider\ollama_api.py", line 79, in _achat_completion_stream
    async for raw_chunk in stream_resp:
TypeError: 'async for' requires an object with __aiter__ method, got bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\utils\common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\roles\role.py", line 550, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\roles\role.py", line 517, in react
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\roles\role.py", line 463, in _react
    rsp = await self._act()
          ^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\roles\role.py", line 392, in _act
    response = await self.rc.todo.run(self.rc.history)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\actions\write_prd.py", line 87, in run
    return await self._handle_new_requirement(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\actions\write_prd.py", line 108, in _handle_new_requirement
    node = await WRITE_PRD_NODE.fill(context=context, llm=self.llm, exclude=exclude)  # schema=schema
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\actions\action_node.py", line 505, in fill
    return await self.simple_fill(schema=schema, mode=mode, images=images, timeout=timeout, exclude=exclude)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\metagpt\actions\action_node.py", line 457, in simple_fill
    content, scontent = await self._aask_v1(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\miniconda3\envs\metagpt-p311\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x25fee27ec10 state=finished raised TypeError>]`

**Comment by geekan** [comment]
@better629 Can you look at this question?

**Comment by better629** [comment]
@Almeyric 
there are some related issues:
https://github.com/geekan/MetaGPT/issues/672
https://github.com/geekan/MetaGPT/issues/1024

can you try the main branch code.
