### ISSUE TITLE
为什么gpt4-turbo的回复为空？

### ISSUE THREAD

**Issue by Linzsd** [geekan/MetaGPT#1242]
一直等待对端的response？

ecs-user@iZbp15znu62vc68ovwhaazZ:~/AI/MetaGPT/examples$ python build_customized_agent.py 
2024-05-02 12:04:36.877 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to /home/ecs-user/AI/MetaGPT
2024-05-02 12:04:40.687 | INFO     | __main__:main:100 - write a function that calculates the product of a list and run it
2024-05-02 12:04:40.689 | INFO     | __main__:_act:84 - Alice(RunnableCoder): to do SimpleWriteCode(SimpleWriteCode)
^CTraceback (most recent call last):
  File "/home/ecs-user/AI/MetaGPT/examples/build_customized_agent.py", line 106, in <module>
    fire.Fire(main)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ecs-user/.local/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ecs-user/AI/MetaGPT/examples/build_customized_agent.py", line 101, in main
    result = asyncio.run(role.run(msg))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

**Comment by Linzsd** [comment]
ecs-user@iZbp15znu62vc68ovwhaazZ:~/AI/MetaGPT/examples$ python hello_world.py 
2024-05-02 02:10:43.753 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to /home/ecs-user/AI/MetaGPT
2024-05-02 02:10:46.487 | INFO     | __main__:ask_and_print:15 - Q: what's your name?

2024-05-02 02:10:47.645 | INFO     | metagpt.utils.cost_manager:update_cost:57 - Total running cost: $0.000 | Max budget: $10.000 | Current cost: $0.000, prompt_tokens: 23, completion_tokens: 0
2024-05-02 02:10:47.645 | INFO     | __main__:ask_and_print:17 - A: 
2024-05-02 02:10:47.646 | INFO     | __main__:ask_and_print:15 - Q: who are you?

2024-05-02 02:10:47.818 | INFO     | metagpt.utils.cost_manager:update_cost:57 - Total running cost: $0.001 | Max budget: $10.000 | Current cost: $0.000, prompt_tokens: 32, completion_tokens: 0
2024-05-02 02:10:47.818 | INFO     | __main__:ask_and_print:17 - A: 
2024-05-02 02:10:47.818 | INFO     | __main__:lowlevel_api_example:22 - low level api example
Traceback (most recent call last):
  File "/home/ecs-user/AI/MetaGPT/examples/hello_world.py", line 45, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ecs-user/AI/MetaGPT/examples/hello_world.py", line 41, in main
    await lowlevel_api_example(llm)
  File "/home/ecs-user/AI/MetaGPT/examples/hello_world.py", line 23, in lowlevel_api_example
    logger.info(await llm.aask_batch(["hi", "write python hello world."]))
  File "/home/ecs-user/AI/MetaGPT/metagpt/provider/base_llm.py", line 162, in aask_batch
    rsp_text = await self.acompletion_text(context, timeout=self.get_timeout(timeout))
  File "/home/ecs-user/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/ecs-user/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ecs-user/.local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/home/ecs-user/AI/MetaGPT/metagpt/provider/openai_api.py", line 157, in acompletion_text
    rsp = await self._achat_completion(messages, timeout=self.get_timeout(timeout))
  File "/home/ecs-user/AI/MetaGPT/metagpt/provider/openai_api.py", line 139, in _achat_completion
    self._update_costs(rsp.usage)
AttributeError: 'str' object has no attribute 'usage'

**Comment by usamimeri** [comment]
可能是网络问题，可以试试`curl https://api.openai.com/v1`

如果没有返回
```json
{
  "error": {
    "type": "invalid_request_error",
    "code": "unknown_url",
    "message": "Unknown request URL: GET /v1. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.",
    "param": null
  }
```
说明你的网络无法连接到外网，可以检查一下你的网络环境，如VPN连接情况。
