### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by luberion** [geekan/MetaGPT#13]
## Program call flow:

```sequence
Title: Snake Game Call Flow

Player->Game: Start game
Game->Game: Initialize game
Game->Game: Start game loop
Player->Game: Control snake using arrow keys
Game->Game: Handle player input
Game->Snake: Change snake direction
Game->Snake: Move snake
Game->Snake: Check collision with boundaries
Game->Snake: Check collision with self
Game->Snake: Eat food if collided
Game->Game: Update game state
Game->Game: Draw game screen
Game->Game: Check game over condition
Game->Game: Pause game if requested
Player->Game: Resume game if paused
Game->Game: End game if game over
Player->Game: Restart game if desired
```

## Anything UNCLEAR:

None.
Warning: gpt-3.5-turbo may change over time. Returning num tokens assuming gpt-3.5-turbo-0301.
2023-07-07 08:24:05.238 | INFO     | metagpt.provider.openai_api:update_cost:90 - Total running cost: $0.006 | Max budget: $3.000 | Current cost: $0.004, prompt_tokens=1113, completion_tokens=692
2023-07-07 08:24:05.246 | ERROR    | metagpt.utils.common:parse_code:67 - ```.*?\s+(.*?)``` not match following text:
2023-07-07 08:24:05.247 | ERROR    | metagpt.utils.common:parse_code:68 - snake_game
Traceback (most recent call last):
  File "/home/donp/Documents/coding/metagpt/startup.py", line 29, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire-0.5.0-py3.10.egg/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire-0.5.0-py3.10.egg/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire-0.5.0-py3.10.egg/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/donp/Documents/coding/metagpt/startup.py", line 25, in main
    asyncio.run(startup(idea, investment, n_round))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/donp/Documents/coding/metagpt/startup.py", line 15, in startup
    await company.run(n_round=n_round)
  File "/home/donp/Documents/coding/metagpt/metagpt/software_company.py", line 55, in run
    await self.environment.run()
  File "/home/donp/Documents/coding/metagpt/metagpt/environment.py", line 58, in run
    await asyncio.gather(*futures)
  File "/home/donp/Documents/coding/metagpt/metagpt/roles/role.py", line 223, in run
    rsp = await self._react()
  File "/home/donp/Documents/coding/metagpt/metagpt/roles/role.py", line 194, in _react
    return await self._act()
  File "/home/donp/Documents/coding/metagpt/metagpt/roles/role.py", line 154, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "/home/donp/Documents/coding/metagpt/metagpt/actions/design_api.py", line 86, in run
    self._save(context, system_design)
  File "/home/donp/Documents/coding/metagpt/metagpt/actions/design_api.py", line 73, in _save
    ws_name = CodeParser.parse_str(block="Python package name", text=system_design)
  File "/home/donp/Documents/coding/metagpt/metagpt/utils/common.py", line 74, in parse_str
    code = cls.parse_code(block, text, lang)
  File "/home/donp/Documents/coding/metagpt/metagpt/utils/common.py", line 69, in parse_code
    raise Exception
Exception

**Comment by geekan** [comment]
we'll do some experiments, trying to make gpt-3.5-turbo available. but it's not on current roadmap.

**Comment by WangShuXian6** [comment]
我遇到了同样的问题，使用了ChimeraGPT的GPT4

**Comment by geekan** [comment]
> 我遇到了同样的问题，使用了ChimeraGPT的GPT4

Chi's GPT4 is buggy. When token is more than 3.5k, it gets "Absolutely! How can I assist you today" oftenly
