### ISSUE TITLE
ImportError: cannot import name 'Anthropic' from 'anthropic'

### ISSUE THREAD

**Issue by halfsies1** [geekan/MetaGPT#131]
I am following given directions, using OPENAI API (only config change I made is adding the key in key.yaml. ANy ideas?  

Traceback (most recent call last):
  File "C:\metagpt\startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer
  File "C:\metagpt\metagpt\roles\__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "C:\metagpt\metagpt\roles\role.py", line 16, in <module>
    from metagpt.actions import Action, ActionOutput
  File "C:\metagpt\metagpt\actions\__init__.py", line 10, in <module>
    from metagpt.actions.action import Action
  File "C:\metagpt\metagpt\actions\action.py", line 14, in <module>
    from metagpt.llm import LLM
  File "C:\metagpt\metagpt\llm.py", line 9, in <module>
    from metagpt.provider.anthropic_api import Claude2 as Claude
  File "C:\metagpt\metagpt\provider\anthropic_api.py", line 10, in <module>
    from anthropic import Anthropic
ImportError: cannot import name 'Anthropic' from 'anthropic'

**Comment by voidking** [comment]
Did you install the depencies first? Follow the [README](https://github.com/geekan/MetaGPT/blob/main/README.md) `Traditional Installation` section please.

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
