### ISSUE TITLE
Attempt to repair JSON fails when set is enclosed into curly brackets instead of square brackets

### ISSUE THREAD

**Issue by shorvit** [geekan/MetaGPT#1312]
**Bug description**
The metagpt for my requirement stops with an error.
2024-05-29 22:49:23.591 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:268 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, try to fix it, exp: Expecting ':' delimiter: line 13 column 29 (char 389)
2024-05-30 00:41:58.766 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:237 - repair_invalid_json, raw error: Expecting ':' delimiter: line 13 column 29 (char 389)
2024-05-30 00:53:48.850 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:268 - parse json from content inside [CONTENT][/CONTENT] failed at retry 2, try to fix it, exp: Expecting ':' delimiter: line 13 column 31 (char 391)
873
2024-05-30 01:07:09.222 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:237 - repair_invalid_json, raw error: Expecting ':' delimiter: line 13 column 31 (char 391)
2024-05-30 01:07:10.223 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:268 - parse json from content inside [CONTENT][/CONTENT] failed at retry 3, try to fix it, exp: Expecting ':' delimiter: line 13 column 33 (char 393)
873

The JSON below was not fixed by repair_invalid_json, generating an error several times and then abandoning the file.

The JSON that cause problem has 2 issues: 
1) a set/list enclosed into curly brackets, not into square brackets as it is expected. In curly brackets "key":"value" pairs are expected. 
2) the next issue that appears if one replaces curly brackets with square brackets where needed, is a concatenation of strings via "plus" sign. While it is a useful language construct in programming languages, it is not allowed in JSON. I assume it must be replaced this comma - ','. 

The json is as follows:
{
    "Implementation approach": [
        "We will implement a trading robot on MOEX that buys and sells highly liquid shares based on forecasted end-of-day prices."
    ],
    "File list": [
        ["main.py", "moex_trading_bot.py"]
    ],
    "Data structures and interfaces": [
        [
            "classDiagram",
            "TradingBot",
            {
                "-MOEX moex",
                "-User user",
                "+start()",
                "+stop()"
            },
            {
                "-API api",
                "+get_prices()",
                "+place_order()"
            },
            {
                "-approval approval",
                "+approve_trade()",
                "+reject_trade()"
            }
        ]
    ],
    "Program call flow": [
        [
            "sequenceDiagram",
            "participant TB as TradingBot",
            "participant M as MOEX",
            "participant U as User",
            "TB->>M: get_prices()",
            "M-->>TB: return prices",
            "TB->>U: request_approval()",
            "U-->>TB: return approval",
            "if (approval == 'approve') then\n" +
            "    TB->>M: place_order()\n" +
            "else\n" +
            "    TB->>M: cancel_order()\n" +
            "end"
        ]
    ],
    "Anything UNCLEAR": [
        "Clarification needed on the algorithm to predict end-of-day prices and the user experience through the approval process."
    ]
} 

**Bug solved method**
1) if error is related to ':' symbol, the logic needs to find the previous and the following curly brackets and replace them with square brackets
2) if plus is the last symbol in the line, replace it with the comma symbol ','

**Environment information**
Windows 10, conda Python 3.12, ollama-hosted llama3. MetaGPT 0.8.1

**Screenshots or logs**
![image](https://github.com/geekan/MetaGPT/assets/138603838/7b179102-f738-40ce-a5ca-800100e5769f)

**Comment by krish240574** [comment]
I get a similar error, , with the JSON :
 Here is a plan to achieve the goal of analyzing climate change:

[
    {
        "task_id": "1",
        "dependent_task_ids": [],
        "instruction": "Scrape climate change data from web pages",
        "task_type": "web scraping"
    },
    {
        "task_id": "2",
        "dependent_task_ids": ["1"],
        "instruction": "Preprocess scraped climate change data",
        "task_type": "data preprocessing"
    },
    {
        "task_id": "3",
        "dependent_task_ids": ["2"],
        "instruction": "Perform exploratory data analysis on climate change data",
        "task_type": "eda"
    }
]
2024-06-03 03:12:35.126 | WARNING  | metagpt.utils.common:wrapper:649 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-06-03 03:12:35.128 | ERROR    | metagpt.utils.common:wrapper:631 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/root/strategy/MetaGPT/metagpt/utils/common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/strategy/MetaGPT/metagpt/roles/role.py", line 550, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/strategy/MetaGPT/metagpt/utils/common.py", line 626, in wrapper
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/strategy/MetaGPT/metagpt/team.py", line 131, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "/root/strategy/MetaGPT/metagpt/utils/common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/strategy/MetaGPT/metagpt/roles/role.py", line 550, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
  File "/root/strategy/MetaGPT/metagpt/roles/role.py", line 521, in react
    rsp = await self._plan_and_act()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/strategy/MetaGPT/metagpt/roles/di/data_interpreter.py", line 95, in _plan_and_act
    raise e
  File "/root/strategy/MetaGPT/metagpt/roles/di/data_interpreter.py", line 90, in _plan_and_act
    rsp = await super()._plan_and_act()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/strategy/MetaGPT/metagpt/roles/role.py", line 483, in _plan_and_act
    await self.planner.update_plan(goal=goal)
  File "/root/strategy/MetaGPT/metagpt/strategy/planner.py", line 89, in update_plan
    update_plan_from_rsp(rsp=rsp, current_plan=self.plan)
  File "/root/strategy/MetaGPT/metagpt/actions/di/write_plan.py", line 55, in update_plan_from_rsp
    rsp = json.loads(rsp)
          ^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


/root/strategy/lib/python3.11/site-packages/pydantic/functional_serializers.py:395: UserWarning: Pydantic serializer warnings:
  Expected `enum` but got `str` - serialized value may not be as expected
  lambda x, h: h(x), schema=core_schema.any_schema()
/root/strategy/lib/python3.11/site-packages/pydantic/_internal/_std_types_schema.py:512: UserWarning: Pydantic serializer warnings:
  Expected `enum` but got `str` - serialized value may not be as expected
  return handler(v)
/root/strategy/MetaGPT/metagpt/schema.py:77: UserWarning: Pydantic serializer warnings:
  Expected `enum` but got `str` - serialized value may not be as expected
  ret = default_serializer(self)

**Comment by krish240574** [comment]
@better629 , any updates on this, please? This is becoming a show-stopper, all runs break, because of this JSONDecoder error. Thanks,

**Comment by better629** [comment]
It's the LLM output format following problem, suggest to try a large LLM model like openai or others.
