### ISSUE TITLE
Run werewolf_game error

### ISSUE THREAD

**Issue by YichiHuang** [geekan/MetaGPT#1335]
Hi, developers:
I run the latest version metagpt script `examples/werewolf_game/start_game.py` and got error as follows. How can I get this error repaired. 
`2024-06-11 15:46:52.484 | ERROR    | metagpt.utils.common:wrapper:631 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/ext/werewolf/actions/common_actions.py", line 238, in run
    rsp_json = log_and_parse_json(self.name, rsp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting value: line 1 column 73 (char 72)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/utils/common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangyichi/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/roles/role.py", line 550, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
tenacity.RetryError: RetryError[<Future at 0x138a0b510 state=finished raised JSONDecodeError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangyichi/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/utils/common.py", line 626, in wrapper
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/team.py", line 131, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/ext/werewolf/actions/common_actions.py", line 238, in run
    rsp_json = log_and_parse_json(self.name, rsp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/ext/werewolf/actions/common_actions.py", line 18, in log_and_parse_json
    rsp_json = json.loads(json_blocks[0])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 73 (char 72)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/utils/common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/roles/role.py", line 550, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/roles/role.py", line 519, in react
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/roles/role.py", line 474, in _react
    rsp = await self._act()
          ^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/ext/werewolf/roles/base_player.py", line 101, in _act
    await Reflect().run(
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x138a0b510 state=finished raised JSONDecodeError>]

Traceback (most recent call last):
  File "/Users/Desktop/openai/metagpt/examples/werewolf_game/start_game.py", line 75, in <module>
    fire.Fire(main)
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Desktop/openai/metagpt/examples/werewolf_game/start_game.py", line 60, in main
    asyncio.run(
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/Desktop/openai/metagpt/examples/werewolf_game/start_game.py", line 47, in start_game
    await game.run(n_round=n_round)
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/utils/common.py", line 632, in wrapper
    self.serialize()  # Team.serialize
    ^^^^^^^^^^^^^^^^
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/team.py", line 62, in serialize
    write_json_file(team_info_path, serialized_data)
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/site-packages/metagpt/utils/common.py", line 581, in write_json_file
    json.dump(data, fout, ensure_ascii=False, indent=indent, default=to_jsonable_python)
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  [Previous line repeated 1 more time]
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/Users/opt/anaconda3/envs/metagpt/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'pydantic._internal._model_construction.ModelMetaclass'>`

I used the `config/config2.yaml` as follows:
`llm:
  api_type: "zhipuai"  
  model: "glm-4" 
  base_url: "https://open.bigmodel.cn/api/paas/v4/"  
  api_key: "XXXXX"
  repair_llm_output: true `

**Comment by LPSCRYPT** [comment]
I have the same issue.

**Comment by YichiHuang** [comment]
> I have the same issue.

I suspect it's a problem with the LLM, as I'm not using the OpenAI model.

**Comment by usamimeri** [comment]
> > I have the same issue.
> 
> I suspect it's a problem with the LLM, as I'm not using the OpenAI model.

JSON output in Werewolf game is quite demanding. The OpenAI models have been specifically optimized for JSON, so they perform well. However, if you use non-OpenAI models , they are prone to outputting incorrect JSON formats, leading to JSONDecodeError.

**Comment by ZhengQiushi** [comment]
maybe you can check the response of _achat_completion_stream.
If it retrurns 404, then maybe you can modify the parameters to fit your llm-api in metagpt/provider/ollama_api.py:
`
@register_provider(LLMType.OLLAMA)
class OllamaLLM(BaseLLM):
    """
    Refs to `https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-chat-completion`
    """

    def __init__(self, config: LLMConfig):
        self.__init_ollama(config)
        self.client = GeneralAPIRequestor(base_url=config.base_url)
        self.config = config
        self.suffix_url = ""
        self.http_method = "post"
        self.use_system_prompt = False
        self.cost_manager = TokenCostManager()
`

**Comment by ZhengQiushi** [comment]
Make sure your request API supports streaming.
For example, I used 'ollama' as an LLM. And my request endpoint should be `http://localhost:11434/v1/chat/completions`.

**Comment by ZhengQiushi** [comment]
Then jumps to `https://github.com/geekan/MetaGPT/issues/1340`
