### ISSUE TITLE
RequestsJSONDecodeError using RAG with ollama 

### ISSUE THREAD

**Issue by byang1981** [geekan/MetaGPT#1336]
**Bug description**
When I run the RAG example rag_search.py under metagpt with llama, report following error:
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)

Note: when using gpt3.5 or gpt4 it's work.

**Bug solved method**

Just run following rag_search.py with llama3  
https://github.com/geekan/MetaGPT/blob/main/examples/rag_search.py

**Environment information**
- LLM type and model name: llama2/llama3
- System version:windows11
- Python version:3.10.10
- MetaGPT version or branch: Main branch on git.

- packages version:
  commit id: bc1cd11a4b284e509056cc0052ec52d20568a4ab
- installation method: 
- pip install git+https://github.com/geekan/MetaGPT

**Screenshots or logs**
Traceback (most recent call last):
  File "C:\Users\brank\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\brank\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\brank\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

**Comment by byang1981** [comment]
Solution： 
  Close ollama desktop application ， and run “ollama serve” in command terminal.
Reason：
  The desktop application take port which leads to python get "404 not page" error.
