### ISSUE TITLE
Docker - workspace mkdir permission denied

### ISSUE THREAD

**Issue by aotombielecki** [geekan/MetaGPT#134]
M1 Macbook Pro

Running the docker container with prompt CLI snake game. Requirements are complete and clear, then error on mkdir

```
Traceback (most recent call last):
  File "/app/metagpt/startup.py", line 36, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/app/metagpt/startup.py", line 32, in main
    asyncio.run(startup(idea, investment, n_round, code_review))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/metagpt/startup.py", line 20, in startup
    await company.run(n_round=n_round)
  File "/app/metagpt/metagpt/software_company.py", line 60, in run
    await self.environment.run()
  File "/app/metagpt/metagpt/environment.py", line 56, in run
    await asyncio.gather(*futures)
  File "/app/metagpt/metagpt/roles/role.py", line 239, in run
    rsp = await self._react()
  File "/app/metagpt/metagpt/roles/role.py", line 208, in _react
    return await self._act()
  File "/app/metagpt/metagpt/roles/role.py", line 167, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "/app/metagpt/metagpt/actions/design_api.py", line 142, in run
    self._save(context, system_design)
  File "/app/metagpt/metagpt/actions/design_api.py", line 130, in _save
    self.recreate_workspace(workspace)
  File "/app/metagpt/metagpt/actions/design_api.py", line 104, in recreate_workspace
    workspace.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/app/metagpt/workspace/cli_snake_game'
```

**Comment by voidking** [comment]
Which host directory have you mount? If you map `/opt/metagpt/workspace:/opt/metagpt/workspace`, try to `sudo chmod a+w /opt/metagpt/workspace` in your host.

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
