### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'config/config2.yaml'

### ISSUE THREAD

**Issue by LPSCRYPT** [geekan/MetaGPT#1344]
**Bug description**
When running a metagpt command, getting the following error, even though I do have a config2.yaml file.

user@computer: /MetaGPT$ metagpt "sing a song about cheese"
<runs a few steps normally>
2024-06-12 23:48:18.772 | INFO     | metagpt.roles.role:_act:402 - Eve(Project Manager): to do WriteTasks(WriteTasks)
2024-06-12 23:48:49.451 | INFO     | metagpt.actions.project_management:run:54 - Nothing has changed.
2024-06-12 23:49:36.184 | INFO     | metagpt.utils.git_repository:archive:168 - Archive: ['config/config2.yaml']
2024-06-12 23:49:52.210 | ERROR    | metagpt.utils.common:wrapper:631 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/home/usr/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.8.1-py3.9.egg/metagpt/utils/common.py", line 626, in wrapper
    result = await func(self, *args, **kwargs)
  File "/home/usr/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.8.1-py3.9.egg/metagpt/team.py", line 134, in run
    self.env.archive(auto_archive)
FileNotFoundError: [Errno 2] No such file or directory: 'config/config2.yaml'

**Bug solved method**

**Environment information**
Ubuntu 

**Screenshots or logs**
<img width="848" alt="config2" src="https://github.com/geekan/MetaGPT/assets/6076063/a279b7de-5dd2-4fac-a6e2-46c9e9d9320f">

**Comment by voidking** [comment]
Try this:
```bash
mkdir $HOME/.metagpt/
mv config/config2.yaml $HOME/.metagpt/
```

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
