### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'root_relative_path'

### ISSUE THREAD

**Issue by krish240574** [geekan/MetaGPT#1379]
**Bug description**

Whenever I run metagpt --project-path <my_existing_project_path> "some new feature/incremental code" , I get the following error:
2024-07-02 11:54:36.567 | ERROR    | metagpt.utils.common:wrapper:631 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/root/DBApp/MetaGPT/metagpt/utils/common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DBApp/MetaGPT/metagpt/roles/role.py", line 550, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'root_relative_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/DBApp/MetaGPT/metagpt/utils/common.py", line 626, in wrapper
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DBApp/MetaGPT/metagpt/team.py", line 131, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "/root/DBApp/MetaGPT/metagpt/utils/common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DBApp/MetaGPT/metagpt/roles/role.py", line 550, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
  File "/root/DBApp/MetaGPT/metagpt/roles/role.py", line 519, in react
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "/root/DBApp/MetaGPT/metagpt/roles/role.py", line 474, in _react
    rsp = await self._act()
          ^^^^^^^^^^^^^^^^^
  File "/root/DBApp/MetaGPT/metagpt/roles/engineer.py", line 149, in _act
    return await self._act_write_code()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DBApp/MetaGPT/metagpt/roles/engineer.py", line 156, in _act_write_code
    changed_files = await self._act_sp_with_cr(review=self.use_code_review)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/DBApp/MetaGPT/metagpt/roles/engineer.py", line 121, in _act_sp_with_cr
    dependencies.add(coding_context.code_plan_and_change_doc.root_relative_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'root_relative_path'

**Bug solved method**

**Environment information**

- LLM type and model name: gpt-4o, llama-3-70b,, gemini-1.5-flash
- System version:
- Ubuntu 24.04
- Python version:
- python 3.11
- MetaGPT version or branch:
git clone https://github.com/geekan/MetaGPT && cd MetaGPT && pip install --upgrade -e .

**Comment by shenchucheng** [comment]
Is the existing project code you want to improve created by MetaGPT?

**Comment by krish240574** [comment]
Yes, I started the project using metagpt "project specs".
Then continued using metagpt --project-path "incremental feature"

Thanks,
Kumar

**Comment by shenchucheng** [comment]
Could you please upload the generated project code? I can try to reproduce this issue.

**Comment by krish240574** [comment]
I'm afraid I can't, since the code is now company-internal.
I simply followed the steps in the documentation,
metagpt "new project specs" - it generated some code ok.
Then I did metagpt --project path <project_path> "description of new
feature to be added".

**Comment by iorisa** [comment]
The code you submitted needs a modification in one place：#37

**Comment by iorisa** [comment]
I've consolidated all the incremental development-related issues into #1498 to make it easier to follow up. Any new issues will be discussed in this newly opened issue, and the old issue will be closed.
