### ISSUE TITLE
Failing with Ollama after 6 Retries

### ISSUE THREAD

**Issue by kjenney** [geekan/MetaGPT#1383]
**Bug description**
I'm trying to run a simple setup with Ollama. Whenever I run it I get failures.

**Bug solved method**
I've not been able to work around this issue.
My config2.yaml contains the following:
```
llm:
  api_type: 'ollama'
  base_url: 'http://localhost:11434/api'
  model: 'llama2:latest'
```

**Environment information**
- LLM type and model name: Ollama, llama2
- System version: OSX 14.5
- Python version: 3.10.12
- MetaGPT version or branch: 0.8.1
- packages version: pip 23.0.1
- installation method: pip install metagpt

**Screenshots or logs**
Here's the log for the failure:

```
Anything UNCLEAR:
Please clarify the third-party API integration, as it is unclear how to proceed with this aspect of the project.
2024-07-05 08:16:09.942 | WARNING  | metagpt.utils.cost_manager:update_cost:49 - Model llama2 not found in TOKEN_COSTS.
2024-07-05 08:16:09.943 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:320 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-07-05 08:16:09.943 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:268 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Expecting value: line 1 column 1 (char 0)
2024-07-05 08:16:09.944 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:237 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-07-05 08:16:09.944 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 350.868(s), this was the 5th time calling it. exp: RetryError[<Future at 0x1370446a0 state=finished raised JSONDecodeError>]
Understood! I will follow your instructions and generate the output in the requested format. Please provide me with the content for each node, and I will take care of the rest.
2024-07-05 08:16:20.965 | WARNING  | metagpt.utils.cost_manager:update_cost:49 - Model llama2 not found in TOKEN_COSTS.
2024-07-05 08:16:20.967 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:320 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-07-05 08:16:20.967 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:268 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Expecting value: line 1 column 1 (char 0)
2024-07-05 08:16:20.967 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:237 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-07-05 08:16:20.967 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 361.891(s), this was the 6th time calling it. exp: RetryError[<Future at 0x137044820 state=finished raised JSONDecodeError>]
2024-07-05 08:16:20.968 | WARNING  | metagpt.utils.common:wrapper:649 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-07-05 08:16:20.988 | ERROR    | metagpt.utils.common:wrapper:631 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/utils/repair_llm_raw_output.py", line 296, in retry_parse_json_text
    parsed_data = CustomDecoder(strict=False).decode(output)
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/actions/action_node.py", line 425, in _aask_v1
    parsed_data = llm_output_postprocess(
tenacity.RetryError: RetryError[<Future at 0x137044820 state=finished raised JSONDecodeError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/utils/common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/roles/role.py", line 550, in run
    rsp = await self.react()
tenacity.RetryError: RetryError[<Future at 0x137045fc0 state=finished raised RetryError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/utils/common.py", line 626, in wrapper
    result = await func(self, *args, **kwargs)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/team.py", line 134, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/utils/repair_llm_raw_output.py", line 296, in retry_parse_json_text
    parsed_data = CustomDecoder(strict=False).decode(output)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/utils/custom_decoder.py", line 297, in decode
    return super().decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/actions/action_node.py", line 425, in _aask_v1
    parsed_data = llm_output_postprocess(
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/provider/postprocess/llm_output_postprocess.py", line 19, in llm_output_postprocess
    result = postprocess_plugin.run(output=output, schema=schema, req_key=req_key)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/provider/postprocess/base_postprocess_plugin.py", line 68, in run
    new_output = self.run_repair_llm_output(output=output, schema=schema, req_key=req_key)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/provider/postprocess/base_postprocess_plugin.py", line 32, in run_repair_llm_output
    parsed_data = self.run_retry_parse_json_text(content)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/provider/postprocess/base_postprocess_plugin.py", line 47, in run_retry_parse_json_text
    parsed_data = retry_parse_json_text(output=content)  # should use output=content
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x137044820 state=finished raised JSONDecodeError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/utils/common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/roles/role.py", line 550, in run
    rsp = await self.react()
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/roles/role.py", line 517, in react
    rsp = await self._react()
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/roles/role.py", line 463, in _react
    rsp = await self._act()
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/roles/role.py", line 392, in _act
    response = await self.rc.todo.run(self.rc.history)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/actions/design_api.py", line 58, in run
    doc = await self._update_system_design(filename=filename)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/actions/design_api.py", line 86, in _update_system_design
    system_design = await self._new_system_design(context=prd.content)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/actions/design_api.py", line 73, in _new_system_design
    node = await DESIGN_API_NODE.fill(context=context, llm=self.llm)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/actions/action_node.py", line 505, in fill
    return await self.simple_fill(schema=schema, mode=mode, images=images, timeout=timeout, exclude=exclude)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/metagpt/actions/action_node.py", line 457, in simple_fill
    content, scontent = await self._aask_v1(
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/ken/devel/ai/agents/metagpt_novel/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x137045fc0 state=finished raised RetryError>]
```

**Comment by kjenney** [comment]
duplicate of https://github.com/geekan/MetaGPT/issues/1340.
