### ISSUE TITLE
使用本地部署的大模型报 Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 123.000(s), raised JSONDecodeError>]

### ISSUE THREAD

**Issue by liuxymm** [geekan/MetaGPT#1393]
总共三个错误
1： warning：model not found，我本地部署的Qwen大模型，api服务端有接收到响应（也不确定响应的对否，但确实响应了）
2. json decode error，在config2.yml中加了repair_llm_output: true，为什么还是报错呢
3. 最后程序终止了 Exception occurs, start to serialize the project, `exp:，试了好多次都是这样的error，有没有大佬帮助下啊好绝望

```
Warning: model not found. Using cl100k_base encoding.
2024-07-12 18:43:41.151 | WARNING  | metagpt.provider.openai_api:_calc_usage:244 - usage calculation failed: num_tokens_from_messages() is not implemented for model Qwen1.5-0.5B-Chat. See https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken for information on how messages are converted to tokens.
2024-07-12 18:43:41.153 | INFO     | metagpt.utils.repair_llm_raw_output:repair_case_sensitivity:39 - repair_case_sensitivity: Anything UNCLEAR
2024-07-12 18:43:41.155 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:320 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-07-12 18:43:41.157 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:268 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, try to fix it, exp: Expecting value: line 1 column 1 (char 0)
2024-07-12 18:43:41.159 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:237 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-07-12 18:43:42.161 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:268 - parse json from content inside [CONTENT][/CONTENT] failed at retry 2, try to fix it, exp: Expecting value: line 1 column 1 (char 0)
2024-07-12 18:43:42.163 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:237 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-07-12 18:43:43.166 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:268 - parse json from content inside [CONTENT][/CONTENT] failed at retry 3, try to fix it, exp: Expecting value: line 1 column 1 (char 0)
2024-07-12 18:43:43.167 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:237 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-07-12 18:43:43.168 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 123.000(s), this was the 6th time calling it. exp: RetryError[<Future at 0x1cfc23fd350 state=finished raised JSONDecodeError>]
2024-07-12 18:43:43.170 | WARNING  | metagpt.utils.common:wrapper:649 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-07-12 18:43:43.426 | ERROR    | metagpt.utils.common:wrapper:631 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "D:\software\anaconda\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\utils\repair_llm_raw_output.py", line 296, in retry_parse_json_text
    parsed_data = CustomDecoder(strict=False).decode(output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\anaconda\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\actions\action_node.py", line 425, in _aask_v1
    parsed_data = llm_output_postprocess(
                  ^^^^^^^^^^^^^^^^^^^^^^^
tenacity.RetryError: RetryError[<Future at 0x1cfc23fd350 state=finished raised JSONDecodeError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\anaconda\Lib\site-packages\metagpt\utils\common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\roles\role.py", line 550, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
tenacity.RetryError: RetryError[<Future at 0x1cfc240bf90 state=finished raised RetryError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\anaconda\Lib\site-packages\metagpt\utils\common.py", line 626, in wrapper
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\team.py", line 134, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "D:\software\anaconda\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\utils\repair_llm_raw_output.py", line 296, in retry_parse_json_text
    parsed_data = CustomDecoder(strict=False).decode(output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\utils\custom_decoder.py", line 297, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\anaconda\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\actions\action_node.py", line 425, in _aask_v1
    parsed_data = llm_output_postprocess(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\provider\postprocess\llm_output_postprocess.py", line 19, in llm_output_postprocess
    result = postprocess_plugin.run(output=output, schema=schema, req_key=req_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\provider\postprocess\base_postprocess_plugin.py", line 68, in run
    new_output = self.run_repair_llm_output(output=output, schema=schema, req_key=req_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\provider\postprocess\base_postprocess_plugin.py", line 32, in run_repair_llm_output
    parsed_data = self.run_retry_parse_json_text(content)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\provider\postprocess\base_postprocess_plugin.py", line 47, in run_retry_parse_json_text
    parsed_data = retry_parse_json_text(output=content)  # should use output=content
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1cfc23fd350 state=finished raised JSONDecodeError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\anaconda\Lib\site-packages\metagpt\utils\common.py", line 640, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\roles\role.py", line 550, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\roles\role.py", line 517, in react
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\roles\role.py", line 463, in _react
    rsp = await self._act()
          ^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\metagpt\roles\role.py", line 392, in _act
                        ^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\anaconda\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1cfc240bf90 state=finished raised RetryError>]

```

**Comment by shenchucheng** [comment]
1. Warning: model not found. Using cl100k_base encoding.这个异常可以忽略，不影响调用，只影响费用统计
2. repair_llm_output: true 只是尝试修复大模型的异常json格式，但是如果大模型本身的输出完全无法解析，也是无法解析成功的
3. 因为没成功，重试多次后就退出了
----------
你贴上来的这个是文件日志还是终端日志？运行时，终端正常是有打印大模型的流式输出的

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
