### ISSUE TITLE
Can't deploy MetaGPT docker on AWS Lambda: error with Config

### ISSUE THREAD

**Issue by malhotra5** [geekan/MetaGPT#1404]
Here is my docker file 

```
# Use the official AWS Lambda Python image
FROM public.ecr.aws/lambda/python:3.10

# Install system dependencies
RUN yum install -y gcc git

# Install metagpt library
RUN pip install litellm
RUN pip install metagpt==0.8.1
RUN pip install openai==1.6.1 

COPY config/ /tmp/config/
COPY images/ /tmp/images/

# Copy the function code
COPY app.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (e.g., app.lambda_handler)
CMD ["app.lambda_handler"]



```

Error is listed below when triggering the lambda

```{
  "errorMessage": "1 validation error for Config\nllm\n  Field required [type=missing, input_value={'AWS_LAMBDA_FUNCTION_VER..._INIT_AT_FORK': 'FALSE'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.6/v/missing",
  "errorType": "ValidationError",
  "requestId": "",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n",
    "  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
    "  File \"/var/task/app.py\", line 6, in <module>\n    from metagpt.actions import Action, UserRequirement\n",
    "  File \"/var/lang/lib/python3.10/site-packages/metagpt/actions/__init__.py\", line 10, in <module>\n    from metagpt.actions.action import Action\n",
    "  File \"/var/lang/lib/python3.10/site-packages/metagpt/actions/action.py\", line 15, in <module>\n    from metagpt.actions.action_node import ActionNode\n",
    "  File \"/var/lang/lib/python3.10/site-packages/metagpt/actions/action_node.py\", line 21, in <module>\n    from metagpt.llm import BaseLLM\n",
    "  File \"/var/lang/lib/python3.10/site-packages/metagpt/llm.py\", line 11, in <module>\n    from metagpt.context import Context\n",
    "  File \"/var/lang/lib/python3.10/site-packages/metagpt/context.py\", line 14, in <module>\n    from metagpt.config2 import Config\n",
    "  File \"/var/lang/lib/python3.10/site-packages/metagpt/config2.py\", line 151, in <module>\n    config = Config.default()\n",
    "  File \"/var/lang/lib/python3.10/site-packages/metagpt/config2.py\", line 101, in default\n    return Config(**final)\n",
    "  File \"/var/lang/lib/python3.10/site-packages/pydantic/main.py\", line 171, in __init__\n    self.__pydantic_validator__.validate_python(data, self_instance=self)\n"
  ]
}```




Is the config required to have an additional field for AWS_LAMBDA_FUNCTION_VERSION?

Running the lambda function locally is fine. 
When running the docker container in the cloud it fails with the following message.

**Comment by shenchucheng** [comment]
Why do you copy the config path to `/tmp/config/`? Is `/tmp` your working directory in the Docker container? You can copy the config path to the working directory or set the environment variable `METAGPT_PROJECT_ROOT` to `/tmp` in the Dockerfile.

**Comment by malhotra5** [comment]
I've set ```METAGPT_PROJECT_ROOT``` to ```/tmp```

The default working directory is ```var/task/``` but has restricted access on a lambda.

**Comment by shenchucheng** [comment]
Is there a complete log?

**Comment by malhotra5** [comment]
```

2024-07-20 21:42:04.767 \| INFO     \| metagpt.const:get_metagpt_root:39 - PROJECT_ROOT set from environment variable to /tmp
--

[ERROR] ValidationError: 1 validation error for Config

llm

Field required [type=missing, input_value={'AWS_LAMBDA_FUNCTION_VER..._INIT_AT_FORK': 'FALSE'}, input_type=dict]

For further information visit https://errors.pydantic.dev/2.6/v/missingTraceback (most recent call last):  File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module    return _bootstrap._gcd_import(name[level:], package, level)  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked  File "<frozen importlib._bootstrap_external>", line 883, in exec_module  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed  File "/var/task/app.py", line 6, in <module>    from metagpt.actions import Action, UserRequirement  File "/var/lang/lib/python3.10/site-packages/metagpt/actions/__init__.py", line 10, in <module>    from metagpt.actions.action import Action  File "/var/lang/lib/python3.10/site-packages/metagpt/actions/action.py", line 15, in <module>    from metagpt.actions.action_node import ActionNode  File "/var/lang/lib/python3.10/site-packages/metagpt/actions/action_node.py", line 21, in <module>    from metagpt.llm import BaseLLM  File "/var/lang/lib/python3.10/site-packages/metagpt/llm.py", line 11, in <module>    from metagpt.context import Context  File "/var/lang/lib/python3.10/site-packages/metagpt/context.py", line 14, in <module>    from metagpt.config2 import Config  File "/var/lang/lib/python3.10/site-packages/metagpt/config2.py", line 151, in <module>    config = Config.default()  File "/var/lang/lib/python3.10/site-packages/metagpt/config2.py", line 101, in default    return Config(**final)  File "/var/lang/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__    self.__pydantic_validator__.validate_python(data, self_instance=self)

INIT_REPORT Init Duration: 5304.86 ms	Phase: init	Status: error	Error Type: Runtime.Unknown

```

**Comment by malhotra5** [comment]
It seems `/tmp` gets remounted, so all the config files are lost. I also can't use any other directory as only `/tmp` has write permissions. 

The solution was to write the text into a config file when the lambda starts. I do this before any MetaGPT imports. That seems to be a good enough patch for now.
