### ISSUE TITLE
[bug] Can not download the dataset of SELA

### ISSUE THREAD

**Issue by Appointat** [geekan/MetaGPT#1568]
Can not download the dataset of SELA. I guess it is the problem of the path file.

### Operations
```
cd to *****/sela/data
python dataset.py --save_analysis_pool
```

### Errors

```
(terminal) data % python dataset.py --save_analysis_pool 
2024-11-03 23:18:**** | INFO     | metagpt.const:get_metagpt_package_root:21 - Package root set to /MetaGPT
Traceback (most recent call last):
  File "/MetaGPT/metagpt/ext/sela/data/dataset.py", line 12, in <module>
    from metagpt.ext.sela.insights.solution_designer import SolutionDesigner
  File "/MetaGPT/metagpt/ext/sela/insights/solution_designer.py", line 3, in <module>
    from metagpt.ext.sela.utils import clean_json_from_rsp, load_data_config
  File "/MetaGPT/metagpt/ext/sela/utils.py", line 21, in <module>
    DATASET_CONFIG = load_data_config("datasets.yaml")
  File "/MetaGPT/metagpt/ext/sela/utils.py", line 16, in load_data_config
    with open(file_path, "r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets.yaml'
```

### Envs:
```
macOS 16
python = 3.10
mategpt: cloned from the main branch
```

**Can I submit a PR to fix it?**

**Comment by cyzus** [comment]
Can you try 
```
python data/dataset.py
```
starting from the sela folder instead of the data folder.

I will update this to the readme

**Comment by Appointat** [comment]
Great. I will retry it.
