### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by baronbigghf** [geekan/MetaGPT#1583]
Hi ,
**I just installed MetaGpt on ubuntu20, and config LLM through modified ./config/congfig2.yaml;**

**then executed example , logs info below :**
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
llm.api_key
  Value error, Please set your API key in /home/*****/.metagpt/config2.yaml. If you also set your config in /data2/11_metadata/MetaGPT/config/config2.yaml, 
the former will overwrite the latter. This may cause unexpected result.
 [type=value_error, input_value='YOUR_API_KEY', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/value_error

**so ,I Erased  /home/*****/.metagpt/config2.yaml ，executed agant, Error info like below:**
**Feature description**
_$ python examples/di/data_visualization.py_
2024-11-08 11:28:52.046 | INFO     | metagpt.const:get_metagpt_package_root:21 - Package root set to /data2/11_metadata/MetaGPT
Traceback (most recent call last):
  File "/data2/11_metadata/MetaGPT/examples/di/data_visualization.py", line 4, in <module>
    from metagpt.roles.di.data_interpreter import DataInterpreter
  File "/data2/11_metadata/MetaGPT/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/data2/11_metadata/MetaGPT/metagpt/roles/role.py", line 30, in <module>
    from metagpt.actions import Action, ActionOutput
  File "/data2/11_metadata/MetaGPT/metagpt/actions/__init__.py", line 10, in <module>
    from metagpt.actions.action import Action
  File "/data2/11_metadata/MetaGPT/metagpt/actions/action.py", line 15, in <module>
    from metagpt.actions.action_node import ActionNode
  File "/data2/11_metadata/MetaGPT/metagpt/actions/action_node.py", line 22, in <module>
    from metagpt.llm import BaseLLM
  File "/data2/11_metadata/MetaGPT/metagpt/llm.py", line 11, in <module>
    from metagpt.context import Context
  File "/data2/11_metadata/MetaGPT/metagpt/context.py", line 14, in <module>
    from metagpt.config2 import Config
  File "/data2/11_metadata/MetaGPT/metagpt/config2.py", line 169, in <module>
    config = Config.default()
             ^^^^^^^^^^^^^^^^
  File "/data2/11_metadata/MetaGPT/metagpt/config2.py", line 110, in default
    final = merge_dict(dicts)
            ^^^^^^^^^^^^^^^^^
  File "/data2/11_metadata/MetaGPT/metagpt/config2.py", line 165, in merge_dict
    result.update(dictionary)
**### TypeError: 'NoneType' object is not iterable**
**Your Feature**

**Comment by voidking** [comment]
How is config2.yaml configured?

**Comment by baronbigghf** [comment]
> How is config2.yaml configured?

thank you  vidking.
