### ISSUE TITLE
执行demo时出现tenacity.RetryError: RetryError[<Future at 0x7f0a4fef12b0 state=finished raised AssertionError>]

### ISSUE THREAD

**Issue by simonaries** [geekan/MetaGPT#1607]
metagpt "Write a cli snake game"
2024-11-15 15:03:50.927 | INFO     | metagpt.const:get_metagpt_package_root:21 - Package root set to /app/metagpt
2024-11-15 15:03:55.243 | INFO     | metagpt.team:invest:93 - Investment: $3.0.
2024-11-15 15:03:55.246 | INFO     | metagpt.roles.role:_act:403 - Alice(Product Manager): to do PrepareDocuments(PrepareDocuments)
2024-11-15 15:03:55.319 | INFO     | metagpt.utils.file_repository:save:57 - save to: /app/metagpt/workspace/20241115150355/docs/requirement.txt
2024-11-15 15:03:55.321 | INFO     | metagpt.roles.role:_act:403 - Alice(Product Manager): to do WritePRD(WritePRD)
2024-11-15 15:03:55.323 | INFO     | metagpt.actions.write_prd:run:86 - New requirement detected: Write a cli snake game
2024-11-15 15:03:55.766 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.base_llm.BaseLLM.acompletion_text' after 0.441(s), this was the 1st time calling it.
2024-11-15 15:03:56.337 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 1.012(s), this was the 1st time calling it. exp: 
2024-11-15 15:03:56.581 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.base_llm.BaseLLM.acompletion_text' after 0.238(s), this was the 1st time calling it.
2024-11-15 15:03:57.182 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 1.857(s), this was the 2nd time calling it. exp: 
2024-11-15 15:03:58.808 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.base_llm.BaseLLM.acompletion_text' after 0.003(s), this was the 1st time calling it.
2024-11-15 15:03:58.992 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 3.667(s), this was the 3rd time calling it. exp: 
2024-11-15 15:04:02.819 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.base_llm.BaseLLM.acompletion_text' after 0.003(s), this was the 1st time calling it.
2024-11-15 15:04:02.896 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 7.571(s), this was the 4th time calling it. exp: 
2024-11-15 15:04:03.830 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.base_llm.BaseLLM.acompletion_text' after 0.003(s), this was the 1st time calling it.
2024-11-15 15:04:04.174 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 8.849(s), this was the 5th time calling it. exp: 
2024-11-15 15:04:16.136 | WARNING  | tenacity.after:log_it:44 - Finished call to 'metagpt.provider.base_llm.BaseLLM.acompletion_text' after 0.002(s), this was the 1st time calling it.
2024-11-15 15:04:16.423 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 21.098(s), this was the 6th time calling it. exp: 
2024-11-15 15:04:16.424 | WARNING  | metagpt.utils.common:wrapper:673 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.    
2024-11-15 15:04:16.441 | ERROR    | metagpt.utils.common:wrapper:655 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/metagpt/metagpt/actions/action_node.py", line 437, in _aask_v1
    content = await self.llm.aask(prompt, system_msgs, images=images, timeout=timeout)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/metagpt/metagpt/utils/common.py", line 664, in wrapper
    return await func(self, *args, **kwargs)
  File "/app/metagpt/metagpt/roles/role.py", line 551, in run
    rsp = await self.react()
tenacity.RetryError: RetryError[<Future at 0x7f0a4fef12b0 state=finished raised AssertionError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/metagpt/metagpt/utils/common.py", line 650, in wrapper
    result = await func(self, *args, **kwargs)
  File "/app/metagpt/metagpt/team.py", line 134, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/metagpt/metagpt/actions/action_node.py", line 437, in _aask_v1
    content = await self.llm.aask(prompt, system_msgs, images=images, timeout=timeout)
  File "/app/metagpt/metagpt/provider/base_llm.py", line 152, in aask
    rsp = await self.acompletion_text(message, stream=stream, timeout=self.get_timeout(timeout))
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/metagpt/metagpt/provider/base_llm.py", line 202, in acompletion_text
    return await self._achat_completion_stream(messages, timeout=self.get_timeout(timeout))
  File "/app/metagpt/metagpt/provider/spark_api.py", line 76, in _achat_completion_stream
    async for chunk in response:
  File "/usr/local/lib/python3.9/site-packages/sparkai/core/language_models/chat_models.py", line 309, in astream
    raise e
  File "/usr/local/lib/python3.9/site-packages/sparkai/core/language_models/chat_models.py", line 301, in astream
    assert generation is not None
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/metagpt/metagpt/utils/common.py", line 664, in wrapper
    return await func(self, *args, **kwargs)
  File "/app/metagpt/metagpt/roles/role.py", line 551, in run
    rsp = await self.react()
  File "/app/metagpt/metagpt/roles/role.py", line 520, in react
    rsp = await self._react()
  File "/app/metagpt/metagpt/roles/role.py", line 475, in _react
    rsp = await self._act()
  File "/app/metagpt/metagpt/roles/role.py", line 404, in _act
    response = await self.rc.todo.run(self.rc.history)
  File "/app/metagpt/metagpt/actions/write_prd.py", line 87, in run
    return await self._handle_new_requirement(req)
  File "/app/metagpt/metagpt/actions/write_prd.py", line 108, in _handle_new_requirement
    node = await WRITE_PRD_NODE.fill(context=context, llm=self.llm, exclude=exclude)  # schema=schema
  File "/app/metagpt/metagpt/actions/action_node.py", line 648, in fill
    return await self.simple_fill(schema=schema, mode=mode, images=images, timeout=timeout, exclude=exclude)
  File "/app/metagpt/metagpt/actions/action_node.py", line 473, in simple_fill
    content, scontent = await self._aask_v1(
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f0a4fef12b0 state=finished raised AssertionError>]

**Comment by voidking** [comment]
从报错看，是调用LLM不通。建议先不要使用metagpt，而是先调通你使用的LLM官方给的示例代码，保证base_url、model和key都是正确的，然后再填入metagpt的配置文件中。

**Comment by ZHAOFEGNSHUN** [comment]
> metagpt “编写一个 cli 贪吃蛇游戏” 2024-11-15 15:03:50.927 | INFO | metagpt.const:get_metagpt_package_root:21 - 将包根设置为 /app/metagpt 2024-11-15 15:03:55.243 | INFO | metagpt.team:invest:93 - 投资：3.0 美元。 2024-11-15 15:03:55.246 | INFO | metagpt.roles.role:_act:403 - Alice（产品经理）：待办 PrepareDocuments（PrepareDocuments） 2024-11-15 15:03:55.319 | INFO | metagpt.utils.file_repository:save:57 - 保存到：/app/metagpt/workspace/20241115150355/docs/requirement.txt 2024-11-15 15:03:55.321 | INFO | metagpt.roles.role:_act:403 - Alice（产品经理）：待办 WritePRD（WritePRD） 2024-11-15 15:03:55.323 | INFO | metagpt.actions.write_prd:run:86 - 检测到新需求：编写一个 cli 贪吃蛇游戏 2024-11-15 15:03:55.766 | 警告 | tenacity.after:log_it:44 - 在 0.441(s) 后完成对“metagpt.provider.base_llm.BaseLLM.acompletion_text”的调用，这是第一次调用它。2024-11-15 15:03:56.337 | 错误 | metagpt.utils.common:log_it:554 - 在 1.012(s) 后完成对“metagpt.actions.action_node.ActionNode._aask_v1”的调用，这是第一次调用它。exp： 2024-11-15 15:03:56.581 | 警告 | tenacity.after:log_it:44 - 在 0.238(s) 后完成对“metagpt.provider.base_llm.BaseLLM.acompletion_text”的调用，这是第一次调用它。2024-11-15 15:03:57.182 | 错误 | metagpt.utils.common:log_it:554 - 在 1.857(s) 后完成对“metagpt.actions.action_node.ActionNode._aask_v1”的调用，这是第二次调用它。exp: 2024-11-15 15:03:58.808 | 警告 | tenacity.after:log_it:44 - 0.003（秒）后完成对“metagpt.provider.base_llm.BaseLLM.acompletion_text”的调用，这是第一次调用它。2024-11-15 15:03:58.992 | 错误 | metagpt.utils.common:log_it:554 - 3.667（秒）后完成对“metagpt.actions.action_node.ActionNode._aask_v1”的调用，这是第三次调用它。exp： 2024-11-15 15:04:02.819 | 警告 | tenacity.after:log_it:44 - 0.003(s) 后完成对“metagpt.provider.base_llm.BaseLLM.acompletion_text”的调用，这是第一次调用它。2024-11-15 15:04:02.896 | 错误 | metagpt.utils.common:log_it:554 - 7.571(s) 后完成对“metagpt.actions.action_node.ActionNode._aask_v1”的调用，这是第四次调用它。exp： 2024-11-15 15:04:03.830 | 警告 | tenacity.after:log_it:44 - 在 0.003(s) 后完成对“metagpt.provider.base_llm.BaseLLM.acompletion_text”的调用，这是第一次调用它。2024-11-15 15:04:04.174 | 错误 | metagpt.utils.common:log_it:554 - 在 8.849(s) 后完成对“metagpt.actions.action_node.ActionNode._aask_v1”的调用，这是第五次调用它。exp: 2024-11-15 15:04:16.136 | 警告 | tenacity.after:log_it:44 - 0.002（秒）后完成对“metagpt.provider.base_llm.BaseLLM.acompletion_text”的调用，这是第一次调用它。2024-11-15 15:04:16.423 | 错误 | metagpt.utils.common:log_it:554 - 21.098（秒）后完成对“metagpt.actions.action_node.ActionNode._aask_v1”的调用，这是第六次调用它。exp： 2024-11-15 15:04:16.424 | 警告 | metagpt.utils.common:wrapper:673 - 角色执行时发生异常，为了恢复，我们删除角色内存中最新的角色通信消息。2024-11-15 15:04:16.441 | 错误 | metagpt.utils.common:wrapper:655 - 发生异常，开始序列化项目，exp： Traceback（最近一次调用最后一次）： 文件“/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py”，第 50 行，在**调用**中 结果 = await fn(*args, **kwargs) 文件“/app/metagpt/metagpt/actions/action_node.py”，第 437 行，在 _aask_v1 内容中 = await self.llm.aask(prompt, system_msgs, images=images, timeout=timeout) AssertionError
> 
> 上述异常是导致以下异常的直接原因：
> 
> 回溯（最近一次调用最后一次）： 文件“/app/metagpt/metagpt/utils/common.py”，第 664 行，在包装器中 返回 await func（self，* args，** kwargs） 文件“/app/metagpt/metagpt/roles/role.py”，第 551 行，在运行 rsp = await self.react（） tenacity.RetryError：RetryError [<Future at 0x7f0a4fef12b0 state=finished raised AssertionError>]
> 
> 在处理上述异常的过程中，又发生了另一个异常：
> 
> 回溯（最近一次调用最后一次）： 文件“/app/metagpt/metagpt/utils/common.py”，第 650 行，在包装器 结果中 = await func（self，* args，** kwargs） 文件“/app/metagpt/metagpt/team.py”，第 134 行，在运行中 等待 self.env.run（） 异常：回溯（最近一次调用最后一次）： 文件“/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py”，第 50 行，在**调用** 结果中 = await fn（* args，** kwargs） 文件“/app/metagpt/metagpt/actions/action_node.py”，第 437 行，在 _aask_v1 内容中 = await self.llm.aask（prompt，system_msgs，images=images，timeout=timeout） 文件“/app/metagpt/metagpt/provider/base_llm.py”，第 152 行，在 aask rsp = await self.acompletion_text(message, stream=stream, timeout=self.get_timeout(timeout)) 文件“/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py”，第 88 行，在 async_wrapped return await fn(*args, **kwargs) 文件“/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py”，第 47 行，在**call** do = self.iter(retry_state=retry_state) 文件“/usr/local/lib/python3.9/site-packages/tenacity/ **init** .py”，第 314 行，在 iter return fut.result() 文件“/usr/local/lib/python3.9/concurrent/futures/_base.py”，第 439 行，结果 返回 self.__get_result() 文件“/usr/local/lib/python3.9/concurrent/futures/_base.py”，第 391 行，在 __get_result 中 引发 self._exception 文件“/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py”，第 50 行，在**调用** 结果 = await fn(*args，**kwargs) 文件“/app/metagpt/metagpt/provider/base_llm.py”，第 202 行，在 acompletion_text 中 返回 await self._achat_completion_stream(messages, timeout=self.get_timeout(timeout)) 文件“/app/metagpt/metagpt/provider/spark_api.py”，第 76 行，在_achat_completion_stream 响应中的块异步： 文件“/usr/local/lib/python3.9/site-packages/sparkai/core/language_models/chat_models.py”，第 309 行，在 astream 中 引发 e 文件“/usr/local/lib/python3.9/site-packages/sparkai/core/language_models/chat_models.py”，第 301 行，在 astream 中 断言生成不是 None AssertionError
> 
> 上述异常是导致以下异常的直接原因：
> 
> 回溯（最近一次调用最后一次）： 文件“/app/metagpt/metagpt/utils/common.py”，第 664 行，在包装器中 返回 await func（self，* args，** kwargs） 文件“/app/metagpt/metagpt/roles/role.py”，第 551 行，在运行中 rsp = await self.react（） 文件“/app/metagpt/metagpt/roles/role.py”，第 520 行，在 react 中 rsp = await self._react（） 文件“/app/metagpt/metagpt/roles/role.py”，第 475 行，在 _react 中 rsp = await self._act（） 文件“/app/metagpt/metagpt/roles/role.py”，第 404 行，在 _act 中 response = await self.rc.todo.run（self.rc.history） 文件“/app/metagpt/metagpt/actions/write_prd.py”, 第 87 行，运行中 返回等待 self._handle_new_requirement(req) 文件“/app/metagpt/metagpt/actions/write_prd.py”, 第 108 行，在 _handle_new_requirement 中 node = await WRITE_PRD_NODE.fill(context=context, llm=self.llm, exclude=exclude) # schema=schema 文件“/app/metagpt/metagpt/actions/action_node.py”, 第 648 行，在填充中 返回等待 self.simple_fill(schema=schema, mode=mode, images=images, timeout=timeout, exclude=exclude) 文件“/app/metagpt/metagpt/actions/action_node.py”, 第 473 行，在 simple_fill 中 content, scontent = await self._aask_v1( 文件“/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py”，第 88 行，在 async_wrapped 中 返回 await fn（*args，**kwargs） 文件“/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py”，第 47 行，在**call** do = self.iter（retry_state=retry_state） 文件“/usr/local/lib/python3.9/site-packages/tenacity/ **init** .py”，第 326 行，在 iter 中 从 fut.exception（）引发 retry_exc tenacity.RetryError：RetryError [<Future at 0x7f0a4fef12b0 state=finished raised AssertionError>]



请问一下解决了嘛？我也是这个问题 调用智谱模型

**Comment by XMYaoyao** [comment]
我也是这个问题，怎么解决呀
