### ISSUE TITLE
from metagpt.tools.libs import calculate_factorial

### ISSUE THREAD

**Issue by fuckqqcom** [geekan/MetaGPT#1622]
**Bug description**

https://docs.deepwisdom.ai/main/en/guide/tutorials/create_and_use_tools.html

2024-12-04 14:07:41.562 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to /Users/xiaohan/soft/project/work/agents
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/xiaohan/soft/project/work/agents/demo2.py", line 4, in <module>
    from metagpt.tools.libs import calculate_factorial
ImportError: cannot import name 'calculate_factorial' from 'metagpt.tools.libs' (/opt/soft/venv/anaconda3/envs/elastic5/lib/python3.11/site-packages/metagpt/tools/libs/__init__.py)
python-BaseException

![image](https://github.com/user-attachments/assets/c70738a5-06c0-4b5a-b10f-d8614df7a5e5)

按照文档，我理解的是在这个目录下加libs，然后可以加一些tools？，如果要在site-packages/metagpt/tools/libs/，这对于上线来说就比较复杂了

- LLM type and model name:
- Python version: 3.11
- MetaGPT version or branch: main

<

**Comment by AstridRylan** [comment]
How do you fix it? I meet the same problem.
