### ISSUE TITLE
I tried to create an LLM instance, but it kept failing all the way! It's driving me crazy! It always returns none, but I don't know why!!!

### ISSUE THREAD

**Issue by jkkjjj** [geekan/MetaGPT#1645]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], [line 2](vscode-notebook-cell:?execution_count=5&line=2)
      [1](vscode-notebook-cell:?execution_count=5&line=1) llm_config = ModelsConfig.default().get("gpt-4o")
----> [2](vscode-notebook-cell:?execution_count=5&line=2) llm = create_llm_instance(llm_config)

File [d:\anaconda3\envs\metagpt\Lib\site-packages\metagpt-0.8.1-py3.11.egg\metagpt\provider\llm_provider_registry.py:40](file:///D:/anaconda3/envs/metagpt/Lib/site-packages/metagpt-0.8.1-py3.11.egg/metagpt/provider/llm_provider_registry.py:40), in create_llm_instance(config)
     [38](file:///D:/anaconda3/envs/metagpt/Lib/site-packages/metagpt-0.8.1-py3.11.egg/metagpt/provider/llm_provider_registry.py:38) def create_llm_instance(config: LLMConfig) -> BaseLLM:
     [39](file:///D:/anaconda3/envs/metagpt/Lib/site-packages/metagpt-0.8.1-py3.11.egg/metagpt/provider/llm_provider_registry.py:39)     """get the default llm provider"""
---> [40](file:///D:/anaconda3/envs/metagpt/Lib/site-packages/metagpt-0.8.1-py3.11.egg/metagpt/provider/llm_provider_registry.py:40)     llm = LLM_REGISTRY.get_provider(config.api_type)(config)
     [41](file:///D:/anaconda3/envs/metagpt/Lib/site-packages/metagpt-0.8.1-py3.11.egg/metagpt/provider/llm_provider_registry.py:41)     if llm.use_system_prompt and not config.use_system_prompt:
     [42](file:///D:/anaconda3/envs/metagpt/Lib/site-packages/metagpt-0.8.1-py3.11.egg/metagpt/provider/llm_provider_registry.py:42)         # for models like o1-series, default openai provider.use_system_prompt is True, but it should be False for o1-*
     [43](file:///D:/anaconda3/envs/metagpt/Lib/site-packages/metagpt-0.8.1-py3.11.egg/metagpt/provider/llm_provider_registry.py:43)         llm.use_system_prompt = config.use_system_prompt

AttributeError: 'NoneType' object has no attribute 'api_type'

**Comment by shenchucheng** [comment]
Why do you retrieve `llm_config` by calling `ModelsConfig.default().get("gpt-4o")`?

**Comment by shenchucheng** [comment]
Did you face the same issue as described in https://github.com/geekan/MetaGPT/issues/1626?

**Comment by jkkjjj** [comment]
Yes, I face the same issue as described in https://github.com/geekan/MetaGPT/issues/1626.

**Comment by jkkjjj** [comment]
I’ve referred to the example configuration file available in the MetaGPT repository: 
[GitHub - MetaGPT Example Config](https://github.com/geekan/MetaGPT/blob/main/examples/aflow/config2.example.yaml).


Here is the content of my `config2.yaml` （C:\Users\Administrator\.metagpt\config2.yaml）:

``` python
models:
 "gpt-3.5-turbo": # model: "gpt-4-turbo"  # or gpt-3.5-turbo
   api_type: "openai"  # or azure / ollama / groq etc.
   base_url: "https://api.openai.com/v1"
   api_key: "my_api_key"
   temperature: 0
 "gpt-4-turbo":  
   api_type: "openai"  
   base_url: "https://api.openai.com/v1"
   api_key: "my_api_key"
   temperature: 0
CALC_USAGE: True 

```

when I run: 
```python
(metagpt) PS E:\GithubRepositories\MetaGPT\examples\aflow>   python -m optimize.py --dataset MATH --opt_model_name gpt-3.5-turbo --exec_model_name gpt-3.5-turbo   
```

I receive the error: 
```python
         
2024-12-18 16:04:26.438 | INFO     | metagpt.const:get_metagpt_package_root:21 - Package root set to E:\GithubRepositories\MetaGPT\examples\aflow
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "E:\GithubRepositories\MetaGPT\examples\aflow\optimize.py", line 9, in <module>
    from metagpt.configs.models_config import ModelsConfig
  File "D:\anaconda3\envs\metagpt\Lib\site-packages\metagpt-0.8.1-py3.11.egg\metagpt\configs\models_config.py", line 20, in <module>
    from metagpt.config2 import merge_dict
  File "D:\anaconda3\envs\metagpt\Lib\site-packages\metagpt-0.8.1-py3.11.egg\metagpt\config2.py", line 169, in <module>
    config = Config.default()
             ^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\metagpt\Lib\site-packages\metagpt-0.8.1-py3.11.egg\metagpt\config2.py", line 111, in default
    return Config(**final)
           ^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\metagpt\Lib\site-packages\pydantic\main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
llm
  Field required [type=missing, input_value={'ALLUSERSPROFILE': 'C:\\...0}}, 'CALC_USAGE': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

```

**After comparing my local `config2.yaml` with the example, I’m unsure whether there are any discrepancies or missing settings.**


**I would appreciate it if you could help me identify any issues with the `config2.yaml` configuration and suggest any corrections needed to align it with the example provided.**

**Comment by jkkjjj** [comment]
I have solved the problem. Thanks!

**Comment by PyJulie** [comment]
> I have solved the problem. Thanks!

How did you solve the problem? I face the same issue as yours.
