### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by Chuyun-Shen** [geekan/MetaGPT#1648]
**Bug description**

I run `python -m examples.aflow.optimize --dataset MATH`, but get 

```
Evaluating MATH problems: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 119/119 [00:02<00:00, 55.82it/s]
2024-12-24 14:39:46.351 | INFO     | metagpt.ext.aflow.benchmark.benchmark:save_results_to_csv:45 - Results saved to metagpt/ext/aflow/scripts/optimized/MATH/workflows/round_1/0.00000_20241224_143946.csv
2024-12-24 14:39:46.351 | INFO     | metagpt.ext.aflow.benchmark.benchmark:run_evaluation:102 - Average score on MATH dataset: 0.00000
2024-12-24 14:39:46.351 | INFO     | metagpt.ext.aflow.benchmark.benchmark:run_evaluation:103 - Total Cost: 0.00000
2024-12-24 14:39:46.352 | INFO     | metagpt.ext.aflow.scripts.optimizer:optimize:93 - Error occurred: Unable to serialize unknown type: <class 'numpy.int64'>. Retrying... (Attempt 1/1)
2024-12-24 14:39:46.352 | INFO     | metagpt.ext.aflow.scripts.optimizer:optimize:95 - Max retries reached. Moving to next round.
2024-12-24 14:39:51.356 | INFO     | metagpt.ext.aflow.scripts.optimizer:optimize:106 - Score for round 2: None
Traceback (most recent call last):
  File "/Users/aaa/miniconda3/envs/metagpt/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/aaa/miniconda3/envs/metagpt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/aaa/Projects/MetaGPT_Aflow/examples/aflow/optimize.py", line 135, in <module>
    optimizer.optimize("Graph")
  File "/Users/aaa/Projects/MetaGPT_Aflow/metagpt/ext/aflow/scripts/optimizer.py", line 108, in optimize
    converged, convergence_round, final_round = self.convergence_utils.check_convergence(top_k=3)
  File "/Users/aaa/Projects/MetaGPT_Aflow/metagpt/ext/aflow/scripts/optimizer_utils/convergence_utils.py", line 74, in check_convergence
    self.avg_scores, self.stds = self.calculate_avg_and_std()
  File "/Users/aaa/Projects/MetaGPT_Aflow/metagpt/ext/aflow/scripts/optimizer_utils/convergence_utils.py", line 58, in calculate_avg_and_std
    self.rounds = self.process_rounds()
  File "/Users/aaa/Projects/MetaGPT_Aflow/metagpt/ext/aflow/scripts/optimizer_utils/convergence_utils.py", line 44, in process_rounds
    self.data = self.load_data(root_path=self.root_path)
  File "/Users/aaa/Projects/MetaGPT_Aflow/metagpt/ext/aflow/scripts/optimizer_utils/convergence_utils.py", line 38, in load_data
    return json.load(file)
  File "/Users/aaa/miniconda3/envs/metagpt/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/aaa/miniconda3/envs/metagpt/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/aaa/miniconda3/envs/metagpt/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/aaa/miniconda3/envs/metagpt/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 6 column 23 (char 97)
```

this json file (metagpt/ext/aflow/scripts/optimized/MATH/workflows/results.json) is :
```
[
    {
        "round": 1,
        "score": 0.0,
        "avg_cost": 0.0,
        "total_cost": 
   
```

I used zhipu API, and set my API in `config/config2.yaml`:
```
llm:
  api_type: "zhipuai"  # or azure / ollama / groq etc.
  model: "glm-4v-flash"
  #  base_url: "<your base url>" 
  api_key: "kkkkkkkkkkkkkk"
  temperature: 0 

models:
 "glm-4v-flash": # model: "gpt-4-turbo"  # or gpt-3.5-turbo
   api_type: "zhipuai"  # or azure / ollama / groq etc.
  #  base_url: "<your base url>" 
   api_key: "kkkkkkkkkkkkkkkkkkk" # Here, not the real api_key.
   temperature: 0
repair_llm_output: true
```

- LLM type and model name: API, glm-4v-flash
- System version: macos
- Python version: 3.9
- MetaGPT version or branch: main, 4954729e7564c806d7e58b3ed8b00ef991f889cc

- packages version:
- installation method:  git clone & pip install -e .

**Comment by Chuyun-Shen** [comment]
I found that using `glm-4-flash` instead of `glm-4v-flash` can fix this issue.
