### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by gaoxunyang** [geekan/MetaGPT#175]
env: mac intel 

→ metagpt (main) $ python startup.py "Write a cli snake game"
2023-08-09 15:33:42.370 | INFO     | metagpt.config:__init__:44 - Config loading done.
Traceback (most recent call last):
  File "/Users/xunyanggao/projects/ai/metagpt/startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer
  File "/Users/xunyanggao/projects/ai/metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/Users/xunyanggao/projects/ai/metagpt/metagpt/roles/role.py", line 19, in <module>
    from metagpt.memory import Memory, LongTermMemory
  File "/Users/xunyanggao/projects/ai/metagpt/metagpt/memory/__init__.py", line 10, in <module>
    from metagpt.memory.longterm_memory import LongTermMemory
  File "/Users/xunyanggao/projects/ai/metagpt/metagpt/memory/longterm_memory.py", line 10, in <module>
    from metagpt.memory.memory_storage import MemoryStorage
  File "/Users/xunyanggao/projects/ai/metagpt/metagpt/memory/memory_storage.py", line 8, in <module>
    from langchain.vectorstores.faiss import FAISS
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain-0.0.231-py3.9.egg/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain-0.0.231-py3.9.egg/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain-0.0.231-py3.9.egg/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain-0.0.231-py3.9.egg/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain-0.0.231-py3.9.egg/langchain/tools/__init__.py", line 3, in <module>
    from langchain.tools.arxiv.tool import ArxivQueryRun
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain-0.0.231-py3.9.egg/langchain/tools/arxiv/tool.py", line 12, in <module>
    from langchain.utilities.arxiv import ArxivAPIWrapper
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain-0.0.231-py3.9.egg/langchain/utilities/__init__.py", line 3, in <module>
    from langchain.utilities.apify import ApifyWrapper
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain-0.0.231-py3.9.egg/langchain/utilities/apify.py", line 5, in <module>
    from langchain.document_loaders import ApifyDatasetLoader
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain-0.0.231-py3.9.egg/langchain/document_loaders/__init__.py", line 55, in <module>
    from langchain.document_loaders.github import GitHubIssuesLoader
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/langchain-0.0.231-py3.9.egg/langchain/document_loaders/github.py", line 37, in <module>
    class GitHubIssuesLoader(BaseGitHubLoader):
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/main.py", line 197, in __new__
    fields[ann_name] = ModelField.infer(
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/fields.py", line 506, in infer
    return cls(
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/fields.py", line 436, in __init__
    self.prepare()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/fields.py", line 552, in prepare
    self._type_analysis()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/fields.py", line 663, in _type_analysis
    self.sub_fields = [self._create_sub_type(t, f'{self.name}_{display_as_type(t)}') for t in types_]
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/fields.py", line 663, in <listcomp>
    self.sub_fields = [self._create_sub_type(t, f'{self.name}_{display_as_type(t)}') for t in types_]
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/fields.py", line 808, in _create_sub_type
    return self.__class__(
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/fields.py", line 436, in __init__
    self.prepare()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/fields.py", line 552, in prepare
    self._type_analysis()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic-1.10.7-py3.9.egg/pydantic/fields.py", line 668, in _type_analysis
    elif issubclass(origin, Tuple):  # type: ignore
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by NextThread** [comment]
hey, I'd like to work on this issue

**Comment by voidking** [comment]
Check all your dependency versions please.
https://github.com/geekan/MetaGPT/blob/main/requirements.txt

**Comment by abanobboles** [comment]
The error is still existing

**Comment by abanobboles** [comment]
@voidking

**Comment by better629** [comment]
@abanobboles @gaoxunyang check the version of `typing-inspect` and `typing_extensions` to confirm if it matchs 
```
typing-inspect==0.8.0
typing_extensions==4.5.0
```

or update it to `pydantic==1.10.8`.

**Comment by royale1223** [comment]
Still happening

**Comment by better629** [comment]
@royale1223 Can you provide your python version、pkgs version about `langchain、faiss、pydantic、typing-inspect、typing_extensions` and platform(Mac or others)?

**Comment by royale1223** [comment]
@better629 

Python 3.11.5
langchain==0.0.231
faiss_cpu==1.7.4
pydantic==1.10.8
typing-inspect==0.8.0
typing_extensions==4.5.0
Mac OS Ventura

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
