### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by DavidARivkin** [geekan/MetaGPT#196]
I followed the directions for the Docker image exactly (exact version and every last detail)  (and I have written many docker images in my past so I do know what I am doing) and when trying to run the script from the container I get the following:

root@a9d034826561:/app/metagpt# python startup.py "Write a cli snake game"
Traceback (most recent call last):
  File "/app/metagpt/startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager
  File "/app/metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/app/metagpt/metagpt/roles/role.py", line 15, in <module>
    from metagpt.config import CONFIG
  File "/app/metagpt/metagpt/config.py", line 114, in <module>
    CONFIG = Config()
  File "/app/metagpt/metagpt/utils/singleton.py", line 21, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/app/metagpt/metagpt/config.py", line 43, in __init__
    self._init_with_config_files_and_env(self._configs, yaml_file)
  File "/app/metagpt/metagpt/config.py", line 100, in _init_with_config_files_and_env
    os.environ.update({k: v for k, v in yaml_data.items() if isinstance(v, str)})
AttributeError: 'str' object has no attribute 'items'

A Docker container should not have this bug.

**Comment by voidking** [comment]
Yes, `metagpt/metagpt:v0.3.1` has been verified to work normally. Which image version are you using?

**Comment by mgleavitt** [comment]
I'm getting what looks like the same error with a "Traditional Installation" of a freshly pulled v0.3.1 on macOS 13.3.1 (Ventura) executing ```python startup.py "Write a cli snake game"```

My exception traceback the same as reported by @DavidARivkin (allowing for differences between traditional/macOS and container installations):
```
% python startup.py "Write a cli snake game"
Traceback (most recent call last):
  File "/Users/marcleavitt/dev/MetaGPT/startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer
  File "/Users/marcleavitt/dev/MetaGPT/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/Users/marcleavitt/dev/MetaGPT/metagpt/roles/role.py", line 15, in <module>
    from metagpt.config import CONFIG
  File "/Users/marcleavitt/dev/MetaGPT/metagpt/config.py", line 113, in <module>
    CONFIG = Config()
  File "/Users/marcleavitt/dev/MetaGPT/metagpt/utils/singleton.py", line 21, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/Users/marcleavitt/dev/MetaGPT/metagpt/config.py", line 43, in __init__
    self._init_with_config_files_and_env(self._configs, yaml_file)
  File "/Users/marcleavitt/dev/MetaGPT/metagpt/config.py", line 99, in _init_with_config_files_and_env
    os.environ.update({k: v for k, v in yaml_data.items() if isinstance(v, str)})
AttributeError: 'str' object has no attribute 'items'
```

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
