### ISSUE TITLE
tenacity.RetryError: RetryError[<Future at 0x11cf6d4d0 state=finished raised InvalidRequestError>]

### ISSUE THREAD

**Issue by piotrtrojanowski** [geekan/MetaGPT#201]
Build successful, program starts, displays 3 lines of progress log:
2023-08-12 10:55:32.740 | INFO     | metagpt.config:__init__:44 - Config loading done.
2023-08-12 10:55:34.502 | INFO     | metagpt.software_company:invest:39 - Investment: $3.0.
2023-08-12 10:55:34.503 | INFO     | metagpt.roles.role:_act:167 - Alice(Product Manager): ready to WritePRD
and then throws 

tenacity.RetryError: RetryError[<Future at 0x11cf6d4d0 state=finished raised InvalidRequestError>]

**Comment by wangjie5540** [comment]
what is the whole error log of it?

**Comment by piotrtrojanowski** [comment]
piotrtrojanowski@macbook-pro-piotr MetaGPT % python3 startup.py "Write a Pack-Man game"
2023-08-12 22:12:26.069 | INFO     | metagpt.config:__init__:44 - Config loading done.
2023-08-12 22:12:27.901 | INFO     | metagpt.software_company:invest:39 - Investment: $3.0.
2023-08-12 22:12:27.901 | INFO     | metagpt.roles.role:_act:167 - Alice(Product Manager): ready to WritePRD
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/metagpt/actions/action.py", line 57, in _aask_v1
    content = await self.llm.aask(prompt, system_msgs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/metagpt/provider/base_gpt_api.py", line 44, in aask
    rsp = await self.acompletion_text(message, stream=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/metagpt/provider/openai_api.py", line 222, in acompletion_text
    return await self._achat_completion_stream(messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/metagpt/provider/openai_api.py", line 151, in _achat_completion_stream
    response = await openai.ChatCompletion.acreate(**self._cons_kwargs(messages), stream=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/api_requestor.py", line 726, in _interpret_async_response
    self._interpret_response_line(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/startup.py", line 40, in <module>
    fire.Fire(main)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/startup.py", line 36, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/startup.py", line 24, in startup
    await company.run(n_round=n_round)
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/metagpt/software_company.py", line 60, in run
    await self.environment.run()
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/metagpt/environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/metagpt/roles/role.py", line 240, in run
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/metagpt/roles/role.py", line 209, in _react
    return await self._act()
           ^^^^^^^^^^^^^^^^^
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/metagpt/roles/role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrtrojanowski/Documents/ML/startup.py_generator/MetaGPT/metagpt/actions/write_prd.py", line 145, in run
    prd = await self._aask_v1(prompt, "prd", OUTPUT_MAPPING)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x127979d50 state=finished raised InvalidRequestError>]
piotrtrojanowski@macbook-pro-piotr MetaGPT % 

Thanks!

**Comment by piotrtrojanowski** [comment]
and now given the bigger fonts I can see this is an issue with openai APIs...

**Comment by piotrtrojanowski** [comment]
I configured gpt-3.5-turbo-16k. Prepaid openai, et spend limits. Building a simple game cost : $0.16
