### ISSUE TITLE
Can't get result when running docker run from Readme.md file

### ISSUE THREAD

**Issue by ziki99** [geekan/MetaGPT#203]
Can't get result when running docker run from Readme.md file

root@DESKTOP-PF44J5J:/mnt/c/Users/guylo# docker run --rm \
>     --privileged \
>     -v /opt/metagpt/config/key.yaml:/app/metagpt/config/key.yaml \
>     -v /opt/metagpt/workspace:/app/metagpt/workspace \
>     metagpt/metagpt:v0.3.1 \
>     python startup.py "Write a cli snake game"
2023-08-12 12:10:53.579 | INFO     | metagpt.config:__init__:44 - Config loading done.
2023-08-12 12:10:55.467 | INFO     | metagpt.software_company:invest:39 - Investment: $3.0.
2023-08-12 12:10:55.468 | INFO     | metagpt.roles.role:_act:166 - Alice(Product Manager): ready to WritePRD
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/metagpt/metagpt/actions/action.py", line 57, in _aask_v1
    content = await self.llm.aask(prompt, system_msgs)
  File "/app/metagpt/metagpt/provider/base_gpt_api.py", line 44, in aask
    rsp = await self.acompletion_text(message, stream=True)
  File "/app/metagpt/metagpt/provider/openai_api.py", line 32, in wrapper
    return await f(*args, **kwargs)
  File "/app/metagpt/metagpt/provider/openai_api.py", line 218, in acompletion_text
    return await self._achat_completion_stream(messages)
  File "/app/metagpt/metagpt/provider/openai_api.py", line 151, in _achat_completion_stream
    response = await openai.ChatCompletion.acreate(
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 214, in acreate
    ) = cls.__prepare_create_request(
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 83, in __prepare_create_request
    raise error.InvalidRequestError(
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/metagpt/startup.py", line 36, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/app/metagpt/startup.py", line 32, in main
    asyncio.run(startup(idea, investment, n_round, code_review))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/metagpt/startup.py", line 20, in startup
    await company.run(n_round=n_round)
  File "/app/metagpt/metagpt/software_company.py", line 60, in run
    await self.environment.run()
  File "/app/metagpt/metagpt/environment.py", line 56, in run
    await asyncio.gather(*futures)
  File "/app/metagpt/metagpt/roles/role.py", line 239, in run
    rsp = await self._react()
  File "/app/metagpt/metagpt/roles/role.py", line 208, in _react
    return await self._act()
  File "/app/metagpt/metagpt/roles/role.py", line 167, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "/app/metagpt/metagpt/actions/write_prd.py", line 145, in run
    prd = await self._aask_v1(prompt, "prd", OUTPUT_MAPPING)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f6b5d762580 state=finished raised InvalidRequestError>]

**Comment by wangjie5540** [comment]
Please paste your config, I think there is something wrong with it.

**Comment by ziki99** [comment]
The following lines are enabled in key.yml
#### if AZURE, check https://github.com/openai/openai-cookbook/blob/main/examples/azure/chat.ipynb
OPENAI_API_TYPE: "azure"
OPENAI_API_BASE: "MY_AZURE_ENDPOINT"
OPENAI_API_KEY: "MY_AZURE_API_KEY"
OPENAI_API_VERSION: "2023-05-15"

all the rest lines in key.yml are comment out

**Comment by arian-kh** [comment]
@ziki99 Are you missing the `DEPLOYMENT_ID` in your config?

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
