### ISSUE TITLE
RateLimitError

### ISSUE THREAD

**Issue by Tommyz123** [geekan/MetaGPT#206]
2023-08-12 20:50:50.843 | INFO     | metagpt.actions.write_code_review:run:77 - Code review data_handler.py..
2023-08-12 20:50:52.150 | ERROR    | metagpt.roles.engineer:_act_sp_precision:187 - code review failed!
2023-08-12 20:50:52.150 | INFO     | metagpt.actions.write_code:run:77 - Writing trading_strategy.py..
Traceback (most recent call last):
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity-8.2.2-py3.11.egg\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\actions\write_code.py", line 71, in write_code
    code_rsp = await self._aask(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\actions\action.py", line 47, in _aask
    return await self.llm.aask(prompt, system_msgs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\provider\base_gpt_api.py", line 44, in aask
    rsp = await self.acompletion_text(message, stream=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity-8.2.2-py3.11.egg\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity-8.2.2-py3.11.egg\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity-8.2.2-py3.11.egg\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity-8.2.2-py3.11.egg\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\provider\openai_api.py", line 222, in acompletion_text
    return await self._achat_completion_stream(messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\provider\openai_api.py", line 151, in _achat_completion_stream
    response = await openai.ChatCompletion.acreate(**self._cons_kwargs(messages), stream=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 726, in _interpret_async_response
    self._interpret_response_line(
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Rate limit reached for default-gpt-4 in organization org-177AldkctYFIPq5UqCZI74Wc on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\startup.py", line 40, in <module>
    fire.Fire(main)
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\startup.py", line 36, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests))
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\startup.py", line 24, in startup
    await company.run(n_round=n_round)
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\software_company.py", line 60, in run
    await self.environment.run()
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\roles\role.py", line 240, in run
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\roles\role.py", line 209, in _react
    return await self._act()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\roles\engineer.py", line 207, in _act
    return await self._act_sp_precision()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\roles\engineer.py", line 173, in _act_sp_precision
    code = await WriteCode().run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\OneDrive\Desktop\META\metagpt\metagpt\actions\write_code.py", line 78, in run
    code = await self.write_code(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity-8.2.2-py3.11.egg\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity-8.2.2-py3.11.egg\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tom\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity-8.2.2-py3.11.egg\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1d6d9c0c250 state=finished raised RateLimitError>]

**Comment by voidking** [comment]
Reduce the `RPM` value in `config/key.yaml` or `config/config.yaml`.

**Comment by ashishawasthi** [comment]
Please review pull request https://github.com/geekan/MetaGPT/pull/213 to retry (with exponential backoff) if OpenAI rate limit is hit. Please leave your comments.

It is (arguably) better to retry on error instead of slowing down all requests, as this slows it down only if the rate limit is hit.

**Comment by Tommyz123** [comment]
I set PRM to 3, but still not work for it.
so I just change some code.
async def _achat_completion_stream(self, messages: list[dict]) -> str:
        await self.wait_if_needed(1)  # 1 代表一个请求
        response = await openai.ChatCompletion.acreate(**self._cons_kwargs(messages), stream=True)
        try:
            response = await openai.ChatCompletion.acreate(**self._cons_kwargs(messages), stream=True)
        except RateLimitError as e:
            logger.error(f"Rate limit error: {e}")
            raise  # 重新引发错误，以便上层可以处理
            
now is work good.

**Comment by voidking** [comment]
> Please review pull request #213 to retry (with exponential backoff) if OpenAI rate limit is hit. Please leave your comments.
> 
> It is (arguably) better to retry on error instead of slowing down all requests, as this slows it down only if the rate limit is hit.

Nice! We will review your code.

**Comment by Nerway** [comment]
> I set PRM to 3, but still not work for it. so I just change some code. async def _achat_completion_stream(self, messages: list[dict]) -> str: await self.wait_if_needed(1) # 1 代表一个请求 response = await openai.ChatCompletion.acreate(**self._cons_kwargs(messages), stream=True) try: response = await openai.ChatCompletion.acreate(**self._cons_kwargs(messages), stream=True) except RateLimitError as e: logger.error(f"Rate limit error: {e}") raise # 重新引发错误，以便上层可以处理
> 
> now is work good.

This actually works for me as well.
