### ISSUE TITLE
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

### ISSUE THREAD

**Issue by hamzahjazi** [geekan/MetaGPT#211]
I tried to run the project and an error appears says : tenacity.RetryError: RetryError[<Future at 0x1c858b59910 state=finished raised InvalidRequestError>] and i saw the issues before and tried all the possible solutions and nothing worked for me I've tried to change the  OPENAI_API_BASE = "https://api.openai-forward.com/v1" and nothing worked and i tried to change the gpt model to 3.5 or 3.5-16k and nothing worked, here is the full error message: 

2023-08-13 11:26:34.869 | INFO     | metagpt.config:__init__:44 - Config loading done.
2023-08-13 11:26:36.923 | INFO     | metagpt.software_company:invest:39 - Investment: $3.0.
2023-08-13 11:26:36.925 | INFO     | metagpt.roles.role:_act:167 - Alice(Product Manager): ready to WritePRD
Traceback (most recent call last):
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\actions\action.py", line 57, in _aask_v1
    content = await self.llm.aask(prompt, system_msgs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\provider\base_gpt_api.py", line 44, in aask
    rsp = await self.acompletion_text(message, stream=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\provider\openai_api.py", line 222, in acompletion_text
    return await self._achat_completion_stream(messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\provider\openai_api.py", line 151, in _achat_completion_stream
    response = await openai.ChatCompletion.acreate(**self._cons_kwargs(messages), stream=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\openai\api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\openai\api_requestor.py", line 726, in _interpret_async_response
    self._interpret_response_line(
  File "D:\Python Enviroment\myenv\Lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Sahara Watira\MetaGPT\metagpt\startup.py", line 40, in <module>
    fire.Fire(main)
  File "D:\Python Enviroment\myenv\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\startup.py", line 36, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests))
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\startup.py", line 24, in startup
    await company.run(n_round=n_round)
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\software_company.py", line 60, in run
    await self.environment.run()
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\roles\role.py", line 240, in run
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\roles\role.py", line 209, in _react
    return await self._act()
           ^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\roles\role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\actions\write_prd.py", line 145, in run
    prd = await self._aask_v1(prompt, "prd", OUTPUT_MAPPING)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1c858b59910 state=finished raised InvalidRequestError>]

**Comment by anara-adam** [comment]
If you can run a `curl` command with your API key, you can see which models you have access to.

`curl https://api.openai.com/v1/models \
  -H "Authorization: Bearer $YOUR_OPENAI_KEY" > models.txt`

This command would pipe it into a file named models.txt. Alternatively, you can try gpt-3.5-turbo as a model name.

**Comment by zhumeisongsong** [comment]
>curl https://api.openai.com/v1/models \ -H "Authorization: Bearer $YOUR_OPENAI_KEY" > models.txt
I got curl: (3) URL rejected: Malformed input to a URL function
