### ISSUE TITLE
Problem when try to startup!!

### ISSUE THREAD

**Issue by Jcplabrana** [geekan/MetaGPT#216]
H:\MetaGPT-main\MetaGPT-main>python startup.py
Traceback (most recent call last):
  File "startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer
  File "H:\MetaGPT-main\MetaGPT-main\metagpt\roles\__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "H:\MetaGPT-main\MetaGPT-main\metagpt\roles\role.py", line 15, in <module>
    from metagpt.config import CONFIG
  File "H:\MetaGPT-main\MetaGPT-main\metagpt\config.py", line 14, in <module>
    from metagpt.utils.singleton import Singleton
  File "H:\MetaGPT-main\MetaGPT-main\metagpt\utils\__init__.py", line 11, in <module>
    from metagpt.utils.token_counter import (
  File "H:\MetaGPT-main\MetaGPT-main\metagpt\utils\token_counter.py", line 99, in <module>
    def get_max_completion_tokens(messages: list[dict], model: str, default: int) -> int:
TypeError: 'type' object is not subscriptable

**Comment by MiesnerJacob** [comment]
I believe this results from the Python version in your environment being < 3.9.0. Please double check you are using => 3.9.0

**Comment by Jcplabrana** [comment]
YHeah, you are right, it's fixed!
