### ISSUE TITLE
运行python startup.py "Write a cli snake game based on pygame"报错

### ISSUE THREAD

**Issue by JustinZhangGIS** [geekan/MetaGPT#222]
Traceback (most recent call last):
  File "D:\GitProject\metagpt\startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer
  File "D:\GitProject\metagpt\metagpt\roles\__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "D:\GitProject\metagpt\metagpt\roles\role.py", line 12, in <module>
    from pydantic import BaseModel, Field
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
  File "pydantic\dataclasses.py", line 48, in init pydantic.dataclasses
    # +=========+=========================================+
  File "pydantic\main.py", line 120, in init pydantic.main
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'

**Comment by JustinZhangGIS** [comment]
pydantic的版本太高了，其他包的版本跟不上，安装指定的包就可以解决
`pip install pydantic==1.10`
