### ISSUE TITLE
ModuleNotFoundError: No module named 'termcolor'

### ISSUE THREAD

**Issue by KernAlan** [geekan/MetaGPT#23]
Ran through the installation steps. Noticed that after running the install command, I see the following error at the very end:
`error: Setup script exited with error: command 'swig.exe' failed: None`

No biggie. But when I run the startup.py with a command, I get the following:

```
Traceback (most recent call last):
  File "C:\Users\kerna\source\repos\metagpt\startup.py", line 4, in <module>
    import fire
  File "C:\Python310\lib\site-packages\fire-0.5.0-py3.10.egg\fire\__init__.py", line 21, in <module>
    from fire.core import Fire
  File "C:\Python310\lib\site-packages\fire-0.5.0-py3.10.egg\fire\core.py", line 67, in <module>
    from fire import formatting
  File "C:\Python310\lib\site-packages\fire-0.5.0-py3.10.egg\fire\formatting.py", line 22, in <module>
    import termcolor
ModuleNotFoundError: No module named 'termcolor'
```

Digging into the startup file, the following imports are not found:
```
import fire
from metagpt.software_company import SoftwareCompany
from metagpt.roles
```

Running Windows 11, using Powershell as a terminal. Ran through the steps exactly as stated. Tried deleting and re-cloning the repo. Tried running Powershell as admin.

**Comment by geekan** [comment]
Googled this: https://stackoverflow.com/questions/51530437/no-module-named-termcolor

Don't know if this link will help?
If it is not resolved, you can share the pip freeze result

**Comment by dolev765** [comment]
pip install termcolor

**Comment by KernAlan** [comment]
Installing termcolor solved this exception. Running the startup again has yet another exception:
```
Traceback (most recent call last):
  File "C:\Users\kerna\source\repos\metagpt\startup.py", line 5, in <module>
    from metagpt.software_company import SoftwareCompany
  File "C:\Users\kerna\source\repos\metagpt\metagpt\software_company.py", line 8, in <module>
    from pydantic import BaseModel
  File "C:\Python310\lib\site-packages\pydantic-2.0.2-py3.10.egg\pydantic\__init__.py", line 13, in <module>
    from . import dataclasses
  File "C:\Python310\lib\site-packages\pydantic-2.0.2-py3.10.egg\pydantic\dataclasses.py", line 11, in <module>
    from ._internal import _config, _decorators, _typing_extra
  File "C:\Python310\lib\site-packages\pydantic-2.0.2-py3.10.egg\pydantic\_internal\_decorators.py", line 15, in <module>
    from ..fields import ComputedFieldInfo
  File "C:\Python310\lib\site-packages\pydantic-2.0.2-py3.10.egg\pydantic\fields.py", line 13, in <module>
    import annotated_types
ModuleNotFoundError: No module named 'annotated_types'
```

pip freeze result:
```
aiohttp==3.8.4
aiosignal==1.3.1
async-generator==1.10
async-timeout==4.0.2
attrs==22.2.0
azure-cognitiveservices-speech==1.30.0
beautifulsoup4==4.12.2
black==23.3.0
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
cfgv==3.3.1
chardet==5.1.0
charset-normalizer==3.1.0
chromadb==0.3.26
click==8.1.3
colorama==0.4.6
coverage==7.2.3
cssselect==1.2.0
distlib==0.3.6
dnspython==2.3.0
docker==6.0.1
duckduckgo-search==2.8.6
exceptiongroup==1.1.1
filelock==3.11.0
fire==0.5.0
flake8==6.0.0
frozenlist==1.3.3
google-api-core==2.11.0
google-api-python-client==2.85.0
google-auth==2.17.3
google-auth-httplib2==0.1.0
googleapis-common-protos==1.59.0
gTTS==2.3.1
h11==0.14.0
httplib2==0.22.0
identify==2.5.22
idna==3.4
isort==5.12.0
loguru==0.7.0
lxml==4.9.2
mccabe==0.7.0
meilisearch==0.28.1
metagpt==0.1
multidict==6.0.4
mypy-extensions==1.0.0
nodeenv==1.7.0
numpy==1.24.2
oauth2client==4.1.3
openai==0.27.2
openpyxl==3.2.0b1
orjson==3.8.10
outcome==1.2.0
packaging==23.1
pathspec==0.11.1
Pillow==9.5.0
pinecone-client==2.2.1
platformdirs==3.2.0
playsound==1.2.2
pre-commit==3.2.2
protobuf==4.22.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybind11==2.10.4
pycodestyle==2.10.0
pycparser==2.21
pydantic==2.0.2
pydantic_core==2.1.2
pyflakes==3.0.1
pymilvus==2.3.0b1
pyparsing==3.0.9
PySocks==1.7.1
pytest-xdist==3.3.1
python-dateutil==2.8.2
python-dotenv==1.0.0
pywin32==306
PyYAML==6.0
readability-lxml==0.8.1
redis==4.5.4
regex==2023.3.23
requests==2.28.2
rsa==4.9
selenium==4.8.3
six==1.16.0
sniffio==1.3.0
SocksiPy-branch==1.1
sortedcontainers==2.4.0
soupsieve==2.4
sourcery==1.2.0
termcolor==2.3.0
tiktoken==0.3.3
tomli==2.0.1
tqdm==4.65.0
trio==0.22.0
trio-websocket==0.10.2
typing_extensions==4.7.1
unstructured==0.8.0
uritemplate==4.1.1
urllib3==1.26.15
virtualenv==20.21.0
webdriver-manager==3.8.6
websocket-client==1.5.1
win32-setctime==1.1.0
wsproto==1.2.0
yarl==1.8.2
```
Some kind of setup problem with Windows perhaps?

**Comment by dolev765** [comment]
It is working great now I just didn't realise my PC wanted me to download each model manually maybe it is because I used python 2.7

**Comment by geekan** [comment]
looks like the pydantic version is different.
```
 ~/github/metagpt/ [main*] pip freeze | grep pydantic
WARNING: Could not find a Python project for directory /Users/alexanderwu/git/gpt4free (tried all parent directories)
openapi-schema-pydantic==1.2.4
pydantic==1.10.7
pydantic-sqlalchemy==0.0.9
```

Could you try this version?

**Comment by atekle10** [comment]
I'm having the same issue with the fire dependency,  manual pip of six isn't working

**Comment by jenilxo** [comment]
Same issue @atekle10

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
