### ISSUE TITLE
我已经设置了anthropic的apikey但是还是提示让我设置openai的key

### ISSUE THREAD

**Issue by Minweiwangaaaa** [geekan/MetaGPT#230]
python startup.py "帮我写一个贪吃蛇" --code_review True

2023-08-15 14:57:56.005 | INFO | metagpt.config:__init__:44 - Config loading done.

Traceback (most recent call last):

File "/Users//Downloads/MetaGPT/startup.py", line 7, in <module>

from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer

File "/Users//Downloads/MetaGPT/metagpt/roles/__init__.py", line 9, in <module>

from metagpt.roles.role import Role

File "/Users//Downloads/MetaGPT/metagpt/roles/role.py", line 15, in <module>

from metagpt.config import CONFIG

File "/Users//Downloads/MetaGPT/metagpt/config.py", line 114, in <module>

CONFIG = Config()

File "/Users//Downloads/MetaGPT/metagpt/utils/singleton.py", line 21, in call

cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)

File "/Users//Downloads/MetaGPT/metagpt/config.py", line 48, in init

raise NotConfiguredException("Set OPENAI_API_KEY first")

metagpt.config.NotConfiguredException: Set OPENAI_API_KEY first

**Comment by yhyu13** [comment]
You probably just need to comment that out at this moment, I guess. But it should be a bug that needs to be fixed.

**Comment by stellaHSR** [comment]
Please update the code. The config.py has been updated to support the anthropic key.thropic key.
