### ISSUE TITLE
2 validation errors for system_design Program call flow

### ISSUE THREAD

**Issue by hamzahjazi** [geekan/MetaGPT#231]
Error appears at the last stage of the running process : 

Traceback (most recent call last):
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\actions\action.py", line 62, in _aask_v1
    instruct_content = output_class(**parsed_data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for system_design
Program call flow
  field required (type=value_error.missing)
Anything UNCLEAR
  field required (type=value_error.missing)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Sahara Watira\MetaGPT\metagpt\startup.py", line 40, in <module>
    fire.Fire(main)
  File "D:\Python Enviroment\myenv\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\startup.py", line 36, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests))
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\startup.py", line 24, in startup
    await company.run(n_round=n_round)
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\software_company.py", line 60, in run
    await self.environment.run()
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\roles\role.py", line 240, in run
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\roles\role.py", line 209, in _react
    return await self._act()
           ^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\roles\role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Sahara Watira\MetaGPT\metagpt\metagpt\actions\design_api.py", line 141, in run
    system_design = await self._aask_v1(prompt, "system_design", OUTPUT_MAPPING)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Enviroment\myenv\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1eaee4ba690 state=finished raised ValidationError>]

The error message appears after starting the project and the MetaGPT start creating the asked command and before it finish the process i got this

**Comment by Apro123** [comment]
@hamzahjazi how did you resolve this?

**Comment by hamzahjazi** [comment]
Ensure that NPM is installed on your system. Then install mermaid-js: 
npm install -g @mermaid-js/mermaid-cli

**Comment by Apro123** [comment]
I did that, but I am still receiving the same error. I tested out the mmdc command and it works within the docker container where I am running it:

```
mmdc -p config/puppeteer-config.json -i test.md -o output.md
```
