### ISSUE TITLE
it runs for a while but before finishing it gives me a UnboundLocalError>]

### ISSUE THREAD

**Issue by ragnarlodbrok19** [geekan/MetaGPT#235]
2023-08-15 11:04:56.720 | INFO     | metagpt.actions.write_code_review:run:77 - Code review products/models.py..
2023-08-15 11:05:00.465 | ERROR    | metagpt.roles.engineer:_act_sp_precision:187 - code review failed!
2023-08-15 11:05:00.468 | INFO     | metagpt.actions.write_code:run:77 - Writing products/forms.py..
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\actions\write_code.py", line 71, in write_code
    code_rsp = await self._aask(prompt)
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\actions\action.py", line 47, in _aask
    return await self.llm.aask(prompt, system_msgs)
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\provider\base_gpt_api.py", line 44, in aask
    rsp = await self.acompletion_text(message, stream=True)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\provider\openai_api.py", line 232, in acompletion_text
    return await self._achat_completion_stream(messages)
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\provider\openai_api.py", line 161, in _achat_completion_stream
    raise e
UnboundLocalError: local variable 'e' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\metagpt2\metagpt\startup.py", line 40, in <module>
    fire.Fire(main)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\PC\Desktop\metagpt2\metagpt\startup.py", line 36, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\PC\Desktop\metagpt2\metagpt\startup.py", line 24, in startup
    await company.run(n_round=n_round)
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\software_company.py", line 60, in run
    await self.environment.run()
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\roles\role.py", line 240, in run
    rsp = await self._react()
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\roles\role.py", line 209, in _react
    return await self._act()
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\roles\engineer.py", line 207, in _act
    return await self._act_sp_precision()
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\roles\engineer.py", line 173, in _act_sp_precision
    code = await WriteCode().run(
  File "C:\Users\PC\Desktop\metagpt2\metagpt\metagpt\actions\write_code.py", line 78, in run
    code = await self.write_code(prompt)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x2447bed7220 state=finished raised UnboundLocalError>]

hello it works for a while but it stops working after a while and this is what it shows me i might be asking him a too large task

**Comment by ragnarlodbrok19** [comment]
i also did the following cause i was running into rate reached error

git fetch origin pull/213/head:pr213
git checkout pr213

**Comment by mettaversesociety** [comment]
there is an RPM setting in the config/config.yaml that you need to set. For example, if my api service limits me to 5 requests per minute, I should set it to no more than 5. In my experience, this still has a chance to error, so I set it to 4 per minute, and I haven't run into the problem since.

**Comment by voidking** [comment]
Try to use python 3.9.x
Or try the cloud environment.
https://deepwisdom.feishu.cn/wiki/CyY9wdJc4iNqArku3Lncl4v8n2b
