### ISSUE TITLE
AttributeError: module 'httpcore' has no attribute 'CloseError'

### ISSUE THREAD

**Issue by pranavvr-lumiq** [geekan/MetaGPT#254]
I have successfully cloned the repo, run the installation and done all the steps for a traditional installation. However, I am stuck on this one problem when I try to run python startup.py "Write a cli snake game".

Traceback (most recent call last):
  File "/home/pranav/LUMIQ/Text Generation/metagpt/metagpt/startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer
  File "/home/pranav/LUMIQ/Text Generation/metagpt/metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/home/pranav/LUMIQ/Text Generation/metagpt/metagpt/metagpt/roles/role.py", line 16, in <module>
    from metagpt.actions import Action, ActionOutput
  File "/home/pranav/LUMIQ/Text Generation/metagpt/metagpt/metagpt/actions/__init__.py", line 10, in <module>
    from metagpt.actions.action import Action
  File "/home/pranav/LUMIQ/Text Generation/metagpt/metagpt/metagpt/actions/action.py", line 14, in <module>
    from metagpt.llm import LLM
  File "/home/pranav/LUMIQ/Text Generation/metagpt/metagpt/metagpt/llm.py", line 9, in <module>
    from metagpt.provider.anthropic_api import Claude2 as Claude
  File "/home/pranav/LUMIQ/Text Generation/metagpt/metagpt/metagpt/provider/anthropic_api.py", line 9, in <module>
    import anthropic
  File "/home/pranav/anaconda3/envs/metaGPT/lib/python3.10/site-packages/anthropic-0.3.6-py3.10.egg/anthropic/__init__.py", line 3, in <module>
    from . import types
  File "/home/pranav/anaconda3/envs/metaGPT/lib/python3.10/site-packages/anthropic-0.3.6-py3.10.egg/anthropic/types/__init__.py", line 5, in <module>
    from .completion import Completion as Completion
  File "/home/pranav/anaconda3/envs/metaGPT/lib/python3.10/site-packages/anthropic-0.3.6-py3.10.egg/anthropic/types/completion.py", line 3, in <module>
    from .._models import BaseModel
  File "/home/pranav/anaconda3/envs/metaGPT/lib/python3.10/site-packages/anthropic-0.3.6-py3.10.egg/anthropic/_models.py", line 15, in <module>
    from ._types import (
  File "/home/pranav/anaconda3/envs/metaGPT/lib/python3.10/site-packages/anthropic-0.3.6-py3.10.egg/anthropic/_types.py", line 19, in <module>
    import httpx
  File "/home/pranav/anaconda3/envs/metaGPT/lib/python3.10/site-packages/httpx-1.0.0b0-py3.10.egg/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/home/pranav/anaconda3/envs/metaGPT/lib/python3.10/site-packages/httpx-1.0.0b0-py3.10.egg/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/home/pranav/anaconda3/envs/metaGPT/lib/python3.10/site-packages/httpx-1.0.0b0-py3.10.egg/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/home/pranav/anaconda3/envs/metaGPT/lib/python3.10/site-packages/httpx-1.0.0b0-py3.10.egg/httpx/_transports/default.py", line 92, in <module>
    httpcore.CloseError: CloseError,
AttributeError: module 'httpcore' has no attribute 'CloseError'

**Comment by voidking** [comment]
Try to use python3.9.x

**Comment by mbulling83** [comment]
I was able to resolve a similar (maybe the same) issue by forcing an install of an earlier version of httpcore. 

pip install "httpcore<0.14"

**Comment by Anish2802** [comment]
@mbulling83 it is showing the same error

**Comment by Dubeyji1233** [comment]
please any solution ?

**Comment by ip-rw** [comment]
pip install -U httpcore httpx

python 3.10
