### ISSUE TITLE
Times out at "Generating single mermaid chart" stage

### ISSUE THREAD

**Issue by jontstaz** [geekan/MetaGPT#27]
Hi,

First of all, nice repo! I've been using gpt-engineer a fair bit and just heard about metagpt so I thought I'd try it out. Unfortunately the program doesn't seem to be able to get past the "Generating single mermaid chart" step. I've ensured that mermaid-chart is installed globally via NPM and everything so I'm not sure what the issue is. The program runs fine and outputs the Implementation approach, package name, file list, data structures and interface definitions as well as the Program call flow. However when it gets to "Generating single mermaid chart" it just hangs after printing that for around 5mins and then outputs the following:

```
ProtocolError: Page.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at new Callback (file:///home/me/.local/share/pnpm/global/5/.pnpm/puppeteer-core@19.11.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:58:35)
    at CallbackRegistry.create (file:///home/me/.local/share/pnpm/global/5/.pnpm/puppeteer-core@19.11.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:103:26)      
    at Connection._rawSend (file:///home/me/.local/share/pnpm/global/5/.pnpm/puppeteer-core@19.11.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:212:26)
    at CDPSessionImpl.send (file:///home/me/.local/share/pnpm/global/5/.pnpm/puppeteer-core@19.11.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:419:78)
    at FrameManager.initialize (file:///home/me/.local/share/pnpm/global/5/.pnpm/puppeteer-core@19.11.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/FrameManager.js:133:24)    
    at CDPPage._CDPPage_initialize (file:///home/me/.local/share/pnpm/global/5/.pnpm/puppeteer-core@19.11.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:834:70)        
    at CDPPage._create (file:///home/me/.local/share/pnpm/global/5/.pnpm/puppeteer-core@19.11.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:57:90)
    at file:///home/me/.local/share/pnpm/global/5/.pnpm/puppeteer-core@19.11.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Target.js:125:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Target.page (file:///home/me/.local/share/pnpm/global/5/.pnpm/puppeteer-core@19.11.1/node_modules/puppeteer-core/lib/esm/puppeteer/common/Target.js:128:23)
```

And then it tries to generate the mermaid chart again and again but fails each time with the same error output. Any idea what's wrong? Any help would be appreciated. Thanks,

**Comment by geekan** [comment]
Please provide OS, Python version, NPM version information
Other than that, you can see if the docker version can meet your needs

**Comment by jontstaz** [comment]
> Please provide OS, Python version, NPM version information
> Other than that, you can see if the docker version can meet your needs

Thanks, yes I'm using the Docker version now which is working. I just had too many conflicting Python packages installed on my main environment and it didn't seem to play nicely with virtual environments either. It was Windows 11 WSL (Ubuntu 20) with Python 3.10 Anyway, all good now.

Quick question: is it possible to use metagpt to improve/fix/modify existing codebases? Like edit the prompt to be "I have an existing project, <PROJECT>, located at '/home/ubuntu/projects/<PROJECT>' which needs some modifications. Complete all the functions which currently contain comment placeholders, review the code and fix any errors/bugs, ....." ? That would be a super useful feature if possible.

Cheers,

**Comment by geekan** [comment]
The development team has identified this issue. This problem is because it seems that the browser kernel cannot be pulled up correctly in the docker environment, and it will take some time to solve.

Difference modification: This is a feature on the roadmap and will be released in the future

**Comment by geekan** [comment]
@voidking

**Comment by geekan** [comment]
https://github.com/geekan/MetaGPT/pull/43 almost fix this issue. pull & retry.
