### ISSUE TITLE
Snake demo issue

### ISSUE THREAD

**Issue by mick-spc** [geekan/MetaGPT#273]
Process starts well but then fails post ##Anything UNCLEAR

`## Anything UNCLEAR
The requirement is clear to me.
Warning: gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.
2023-08-29 15:02:29.974 | INFO     | metagpt.provider.openai_api:update_cost:81 - Total running cost: $0.124 | Max budget: $3.000 | Current cost: $0.059, prompt_tokens: 1198, completion_tokens: 379
2023-08-29 15:02:29.980 | INFO     | metagpt.utils.mermaid:mermaid_to_file:37 - Generating /home/parallels/metagpt/workspace/cli_snake_game/resources/competitive_analysis.pdf..
Traceback (most recent call last):
  File "/home/parallels/metagpt/startup.py", line 42, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/dist-packages/fire-0.4.0-py3.10.egg/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire-0.4.0-py3.10.egg/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire-0.4.0-py3.10.egg/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/parallels/metagpt/startup.py", line 38, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/parallels/metagpt/startup.py", line 24, in startup
    await company.run(n_round=n_round)
  File "/home/parallels/metagpt/metagpt/software_company.py", line 60, in run
    await self.environment.run()
  File "/home/parallels/metagpt/metagpt/environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "/home/parallels/metagpt/metagpt/roles/role.py", line 240, in run
    rsp = await self._react()
  File "/home/parallels/metagpt/metagpt/roles/role.py", line 209, in _react
    return await self._act()
  File "/home/parallels/metagpt/metagpt/roles/role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "/home/parallels/metagpt/metagpt/actions/design_api.py", line 142, in run
    self._save(context, system_design)
  File "/home/parallels/metagpt/metagpt/actions/design_api.py", line 135, in _save
    self._save_prd(docs_path, resources_path, context[-1].content)
  File "/home/parallels/metagpt/metagpt/actions/design_api.py", line 109, in _save_prd
    mermaid_to_file(quadrant_chart, resources_path / 'competitive_analysis')
  File "/home/parallels/metagpt/metagpt/utils/mermaid.py", line 40, in mermaid_to_file
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './node_modules/.bin/mmdc'
`

**Comment by voidking** [comment]
Please follow README.md to install mermaid first.

**Comment by mick-spc** [comment]
this is post mermaid install

**Comment by gvaatstra** [comment]
@mick-spc , this is only if you installed it locally. Install it locally and it should be able to find it
