### ISSUE TITLE
ImportError: cannot import name 'ModelField' from 'pydantic.fields'

### ISSUE THREAD

**Issue by htksgamev** [geekan/MetaGPT#282]
2023-08-31 17:22:09.757 | INFO     | metagpt.config:__init__:44 - Config loading done.
Traceback (most recent call last):
  File "/Users/tianfei/Documents/personal/metagpt/metagpt/metagpt/startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager, ProjectManager, QaEngineer
  File "/Users/tianfei/Documents/personal/metagpt/metagpt/metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/Users/tianfei/Documents/personal/metagpt/metagpt/metagpt/metagpt/roles/role.py", line 16, in <module>
    from metagpt.actions import Action, ActionOutput
  File "/Users/tianfei/Documents/personal/metagpt/metagpt/metagpt/metagpt/actions/__init__.py", line 10, in <module>
    from metagpt.actions.action import Action
  File "/Users/tianfei/Documents/personal/metagpt/metagpt/metagpt/metagpt/actions/action.py", line 14, in <module>
    from metagpt.llm import LLM
  File "/Users/tianfei/Documents/personal/metagpt/metagpt/metagpt/metagpt/llm.py", line 9, in <module>
    from metagpt.provider.anthropic_api import Claude2 as Claude
  File "/Users/tianfei/Documents/personal/metagpt/metagpt/metagpt/metagpt/provider/anthropic_api.py", line 9, in <module>
    import anthropic
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/anthropic-0.3.6-py3.9.egg/anthropic/__init__.py", line 3, in <module>
    from . import types
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/anthropic-0.3.6-py3.9.egg/anthropic/types/__init__.py", line 5, in <module>
    from .completion import Completion as Completion
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/anthropic-0.3.6-py3.9.egg/anthropic/types/completion.py", line 3, in <module>
    from .._models import BaseModel
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/anthropic-0.3.6-py3.9.egg/anthropic/_models.py", line 11, in <module>
    from pydantic.fields import ModelField
ImportError: cannot import name 'ModelField' from 'pydantic.fields' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydantic/fields.py)

**Comment by rahulvramesh** [comment]
@htksgamev got any luck ?

**Comment by rahulvramesh** [comment]
`pip install "pydantic<2"`        might be useful

**Comment by mcavaliere** [comment]
I worked around this for now by setting `pydantic==1.10.8` in `requirements.txt` and re-running the install script/
