### ISSUE TITLE
🐛🐞 getting error out of the box : `TypeError: 'type' object is not subscriptable`

### ISSUE THREAD

**Issue by hemangjoshi37a** [geekan/MetaGPT#287]
command : `python startup.py "write a cli snake game"`

Error : 
```python
Traceback (most recent call last):
  File "startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager
  File "/home/hemang/Documents/GitHub/metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/home/hemang/Documents/GitHub/metagpt/metagpt/roles/role.py", line 15, in <module>
    from metagpt.config import CONFIG
  File "/home/hemang/Documents/GitHub/metagpt/metagpt/config.py", line 14, in <module>
    from metagpt.utils.singleton import Singleton
  File "/home/hemang/Documents/GitHub/metagpt/metagpt/utils/__init__.py", line 11, in <module>
    from metagpt.utils.token_counter import (
  File "/home/hemang/Documents/GitHub/metagpt/metagpt/utils/token_counter.py", line 99, in <module>
    def get_max_completion_tokens(messages: list[dict], model: str, default: int) -> int:
TypeError: 'type' object is not subscriptable
```

**Comment by voidking** [comment]
Try to use python3.9.x
