### ISSUE TITLE
pydantic error

### ISSUE THREAD

**Issue by jasleen549** [geekan/MetaGPT#288]
python startup.py "Write a cli snake game"
2023-09-04 11:11:53.376 | INFO     | metagpt.config:__init__:44 - Config loading done.
Traceback (most recent call last):
  File "startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager
  File "/home/ubuntu/jasleen/metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/home/ubuntu/jasleen/metagpt/metagpt/roles/role.py", line 65, in <module>
    class RoleContext(BaseModel):
  File "pydantic/main.py", line 179, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 399, in pydantic.typing.resolve_annotations
    """Special type construct to mark class variables.
  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable

**Comment by voidking** [comment]
Try to use python3.9.x
