### ISSUE TITLE
Avaiable openai models? gpt-3.5-turbo-16k has failed

### ISSUE THREAD

**Issue by yhyu13** [geekan/MetaGPT#303]
Hi,

Maybe a stupid question, since the api we are using is

```
openai.ChatCompletion.acreate
```

chat models listed in this page https://platform.openai.com/docs/models/overview
should be our available models at this moment, right?

**Comment by yhyu13** [comment]
I tried gpt-3.5-turbo-16k with the docker meta-gpt:v.0.3.1 cli_snake example. it fails, but gpt4 succeeded.

It seems to me gpt3.5 has failed with code syntax check? Am I getting it wrong?

```
2023-09-09 14:17:27.444 | INFO     | metagpt.config:__init__:44 - Config loading done.
2023-09-09 14:17:29.222 | INFO     | metagpt.software_company:invest:39 - Investment: $3.0.
2023-09-09 14:17:29.222 | INFO     | metagpt.roles.role:_act:166 - Alice(Product Manager): ready to WritePRD
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/metagpt/metagpt/actions/action.py", line 62, in _aask_v1
    instruct_content = output_class(**parsed_data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
## Original Requirements:
The boss wants a command-line interface (CLI) snake game.

## Product Goals:
- Create a fun and engaging snake game that can be played in the command line.
- Provide a user-friendly interface with intuitive controls.
- Ensure smooth gameplay and high performance.

## User Stories:
- As a user, I want to be able to control the snake using arrow keys.
- As a user, I want the snake to grow longer when it eats food.
- As a user, I want the game to end when the snake hits the wall or its own body.
- As a user, I want to see my current score and high score displayed on the screen.
- As a user, I want to be able to start a new game or quit the game at any time.

## Competitive Analysis:
- Python Snake Game: A popular snake game implemented in Python with a graphical user interface (GUI).
- CLI Snake Game: A simple snake game implemented in the command line using ASCII characters.
- Snake Game App: A mobile app that allows users to play snake game on their smartphones.
- Online Snake Game: A multiplayer snake game that can be played online with other players.
- Snake Game Console: A snake game implemented on a gaming console with enhanced graphics and features.
- Snake Game Website: A website that offers a snake game playable in the browser.
- Snake Game AI: An AI-powered snake game that can be played against computer-controlled opponents.

## Competitive Quadrant Chart:
```mermaid
quadrantChart
    title Reach and engagement of snake game variants
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 Need to promote
    quadrant-2 May be improved
    quadrant-3 Re-evaluate
    quadrant-4 We should expand
    "Python Snake Game": [0.8, 0.9]
    "CLI Snake Game": [0.6, 0.7]
    "Snake Game App": [0.9, 0.8]
    "Online Snake Game": [0.7, 0.6]
    "Snake Game Console": [0.7, 0.7]
    "Snake Game Website": [0.8, 0.6]
    "Snake Game AI": [0.6, 0.8]
    "Our Target Product": [0.5, 0.6]
```

## Requirement Analysis:
The product should be a command-line interface (CLI) snake game that provides a fun and engaging gameplay experience. It should have intuitive controls, smooth gameplay, and high performance. The game should end when the snake hits the wall or its own body, and the player's score should be displayed on the screen. The game should also have a high score feature and allow the player to start a new game or quit at any time.

## Requirement Pool:
- End game when the snake hits the wall or its own body (P0)
- Display the player's score on the screen (P1)
- Implement a high score feature (P1)
- Allow the player to start a new game or quit at any time (P2)

## UI Design draft:
The game will be displayed in the command line interface. The snake will be represented by a series of characters, such as "O", and the food will be represented by a different character, such as "*". The player will control the snake using arrow keys. The current score and high score will be displayed on the screen. The game will have a simple layout with the snake and food positioned within the boundaries of the command line window. The game will have a clean and minimalistic style, with clear and easy-to-read characters.
## Original Requirements:
The boss wants a command-line snake game.

## Product Goals:
- Create a fun and engaging snake game.
- Provide a user-friendly command-line interface.
- Ensure smooth and responsive gameplay.

## User Stories:
- As a user, I want to be able to control the snake using arrow keys.
- As a user, I want to see my score and the length of the snake displayed on the screen.
- As a user, I want the game to end when the snake hits the wall or itself.
- As a user, I want the game to get progressively harder as I score more points.
- As a user, I want to be able to pause and resume the game.

## Competitive Analysis:
- Python Snake Game: A simple snake game implemented in Python with basic features.
- Command-line Snake: Another command-line snake game with additional features like power-ups and obstacles.
- Snake Game Deluxe: A graphical snake game with multiple levels and power-ups.
- Snake Mania: A mobile snake game with colorful graphics and various game modes.
- Snake.io: An online multiplayer snake game with competitive gameplay.
- Snake Escape: A puzzle-based snake game with challenging levels.
- Snake Attack: A snake game with a twist, where the snake can attack other creatures.

## Competitive Quadrant Chart:
```mermaid
quadrantChart
    title Reach and engagement of snake games
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Python Snake Game": [0.3, 0.6]
    "Command-line Snake": [0.45, 0.23]
    "Snake Game Deluxe": [0.57, 0.69]
    "Snake Mania": [0.78, 0.34]
    "Snake.io": [0.40, 0.34]
    "Snake Escape": [0.35, 0.78]
    "Snake Attack": [0.6, 0.7]
    "Our Target Product": [0.5, 0.6]
```

## Requirement Analysis:
The product should be a command-line snake game with smooth and responsive gameplay. It should have a user-friendly interface and display the score and length of the snake on the screen. The game should end when the snake hits the wall or itself. It should also progressively increase in difficulty as the player scores more points. The game should have a pause and resume functionality.

## Requirement Pool:
- End game when the snake hits the wall or itself (P0)
- Display the score and length of the snake on the screen (P1)
- Increase the difficulty as the player scores more points (P1)
- Implement pause and resume functionality (P2)

## UI Design draft:
The game will be displayed in the command-line interface. The snake will be represented by a character, such as an 'O', and the food will be represented by a different character, such as an 'X'. The score and length of the snake will be displayed at the top of the screen. The arrow keys will be used to control the snake's movement. The game will have a simple and minimalistic style, with clear and easy-to-read text. The layout will be organized, with the game area in the center of the screen and the score and length displayed at the top.
pydantic.error_wrappers.ValidationError: 5 validation errors for prd
Requirement Pool -> 0
  value is not a valid tuple (type=type_error.tuple)
Requirement Pool -> 1
  value is not a valid tuple (type=type_error.tuple)
Requirement Pool -> 2
  value is not a valid tuple (type=type_error.tuple)
Requirement Pool -> 3
  value is not a valid tuple (type=type_error.tuple)
Anything UNCLEAR
  field required (type=value_error.missing)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/metagpt/startup.py", line 36, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/app/metagpt/startup.py", line 32, in main
    asyncio.run(startup(idea, investment, n_round, code_review))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/metagpt/startup.py", line 20, in startup
    await company.run(n_round=n_round)
  File "/app/metagpt/metagpt/software_company.py", line 60, in run
    await self.environment.run()
  File "/app/metagpt/metagpt/environment.py", line 56, in run
    await asyncio.gather(*futures)
  File "/app/metagpt/metagpt/roles/role.py", line 239, in run
    rsp = await self._react()
  File "/app/metagpt/metagpt/roles/role.py", line 208, in _react
    return await self._act()
  File "/app/metagpt/metagpt/roles/role.py", line 167, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "/app/metagpt/metagpt/actions/write_prd.py", line 145, in run
    prd = await self._aask_v1(prompt, "prd", OUTPUT_MAPPING)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f833e6c1b50 state=finished raised ValidationError>]
```

**Comment by yhyu13** [comment]
Another try with gpt3.5-turbo which is 4096 token maxed, metagpt fails with token max out even though I set MAX_TOKEN in yaml to be 1500 which is the default option:

---
2023-09-09 14:32:04.840 | INFO     | metagpt.config:__init__:44 - Config loading done.
2023-09-09 14:32:06.661 | INFO     | metagpt.software_company:invest:39 - Investment: $3.0.
2023-09-09 14:32:06.661 | INFO     | metagpt.roles.role:_act:166 - Alice(Product Manager): ready to WritePRD
2023-09-09 14:32:37.106 | INFO     | metagpt.roles.role:_act:166 - Bob(Architect): ready to WriteDesign
2023-09-09 14:33:10.803 | INFO     | metagpt.utils.mermaid:mermaid_to_file:40 - Generating /app/metagpt/workspace/cli_snake_game/resources/competitive_analysis.pdf..
2023-09-09 14:33:11.884 | INFO     | metagpt.utils.mermaid:mermaid_to_file:40 - Generating /app/metagpt/workspace/cli_snake_game/resources/competitive_analysis.svg..
2023-09-09 14:33:12.930 | INFO     | metagpt.utils.mermaid:mermaid_to_file:40 - Generating /app/metagpt/workspace/cli_snake_game/resources/competitive_analysis.png..
2023-09-09 14:33:14.123 | INFO     | metagpt.actions.design_api:_save_prd:110 - Saving PRD to /app/metagpt/workspace/cli_snake_game/docs/prd.md
2023-09-09 14:33:14.125 | INFO     | metagpt.utils.mermaid:mermaid_to_file:40 - Generating /app/metagpt/workspace/cli_snake_game/resources/data_api_design.pdf..
2023-09-09 14:33:15.291 | INFO     | metagpt.utils.mermaid:mermaid_to_file:40 - Generating /app/metagpt/workspace/cli_snake_game/resources/data_api_design.svg..
2023-09-09 14:33:16.437 | INFO     | metagpt.utils.mermaid:mermaid_to_file:40 - Generating /app/metagpt/workspace/cli_snake_game/resources/data_api_design.png..
2023-09-09 14:33:17.760 | INFO     | metagpt.utils.mermaid:mermaid_to_file:40 - Generating /app/metagpt/workspace/cli_snake_game/resources/seq_flow.pdf..
2023-09-09 14:33:18.946 | INFO     | metagpt.utils.mermaid:mermaid_to_file:40 - Generating /app/metagpt/workspace/cli_snake_game/resources/seq_flow.svg..
2023-09-09 14:33:20.042 | INFO     | metagpt.utils.mermaid:mermaid_to_file:40 - Generating /app/metagpt/workspace/cli_snake_game/resources/seq_flow.png..
2023-09-09 14:33:21.408 | INFO     | metagpt.actions.design_api:_save_system_design:119 - Saving System Designs to /app/metagpt/workspace/cli_snake_game/docs/system_design.md
2023-09-09 14:33:21.411 | INFO     | metagpt.roles.role:_act:166 - Eve(Project Manager): ready to WriteTasks
2023-09-09 14:33:45.424 | INFO     | metagpt.actions.write_code:run:77 - Writing snake.py..
2023-09-09 14:33:59.786 | INFO     | metagpt.actions.write_code:run:77 - Writing food.py..
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/metagpt/metagpt/actions/write_code.py", line 71, in write_code
    code_rsp = await self._aask(prompt)
  File "/app/metagpt/metagpt/actions/action.py", line 47, in _aask
    return await self.llm.aask(prompt, system_msgs)
  File "/app/metagpt/metagpt/provider/base_gpt_api.py", line 44, in aask
    rsp = await self.acompletion_text(message, stream=True)
  File "/app/metagpt/metagpt/provider/openai_api.py", line 32, in wrapper
    return await f(*args, **kwargs)
  File "/app/metagpt/metagpt/provider/openai_api.py", line 218, in acompletion_text
    return await self._achat_completion_stream(messages)
  File "/app/metagpt/metagpt/provider/openai_api.py", line 151, in _achat_completion_stream
    response = await openai.ChatCompletion.acreate(
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 726, in _interpret_async_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 4308 tokens (2808 in the messages, 1500 in the completion). Please reduce the length of the messages or completion.

The above exception was the direct cause of the following exception:

**Comment by shenchucheng** [comment]
Due to the uncertainty of LLM's output, we cannot guarantee a successful outcome with every run. However, what we can ascertain is that the success rate of the GPT-4.0 model is higher than that of the GPT-3.5-turbo.

**Comment by HuntZhaozq** [comment]
> pydantic.error_wrappers.ValidationError: 5 validation errors for prd
> Requirement Pool -> 0
> value is not a valid tuple (type=type_error.tuple)
> Requirement Pool -> 1
> value is not a valid tuple (type=type_error.tuple)
> Requirement Pool -> 2
> value is not a valid tuple (type=type_error.tuple)
> Requirement Pool -> 3
> value is not a valid tuple (type=type_error.tuple)
> Anything UNCLEAR
> field required (type=value_error.missing)

Hello, I also meet this problem when replace GPT4 with local LLM. Have you solved this problem? How to process this error. Thank you!
