### ISSUE TITLE
当我运行(metagpt) D:\metagpt>python startup.py "Write a cli snake game based on pygame" --code_review True时，在中途得到这个错误，怎么解决呢？

### ISSUE THREAD

**Issue by Vodkasxr** [geekan/MetaGPT#330]
2023-09-17 11:24:57.022 | INFO     | metagpt.utils.mermaid:mermaid_to_file:44 - Generating D:\metagpt\workspace\snake_game\resources\competitive_analysis.pdf..
Traceback (most recent call last):
  File "D:\metagpt\startup.py", line 68, in <module>
    fire.Fire(main)
  File "D:\Programs\Anaconda3\envs\metagpt\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Anaconda3\envs\metagpt\Lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Anaconda3\envs\metagpt\Lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\metagpt\startup.py", line 63, in main
    asyncio.run(startup(idea, investment, n_round,
  File "D:\Programs\Anaconda3\envs\metagpt\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Programs\Anaconda3\envs\metagpt\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Anaconda3\envs\metagpt\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\metagpt\startup.py", line 40, in startup
    await company.run(n_round=n_round)
  File "D:\metagpt\metagpt\software_company.py", line 60, in run
    await self.environment.run()
  File "D:\metagpt\metagpt\environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "D:\metagpt\metagpt\roles\role.py", line 240, in run
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "D:\metagpt\metagpt\roles\role.py", line 209, in _react
    return await self._act()
           ^^^^^^^^^^^^^^^^^
  File "D:\metagpt\metagpt\roles\role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\metagpt\metagpt\actions\design_api.py", line 142, in run
    await self._save(context, system_design)
  File "D:\metagpt\metagpt\actions\design_api.py", line 135, in _save
    await self._save_prd(docs_path, resources_path, context[-1].content)
  File "D:\metagpt\metagpt\actions\design_api.py", line 109, in _save_prd
    await mermaid_to_file(quadrant_chart, resources_path / 'competitive_analysis')
  File "D:\metagpt\metagpt\utils\mermaid.py", line 62, in mermaid_to_file
    process = await asyncio.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Anaconda3\envs\metagpt\Lib\asyncio\subprocess.py", line 221, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Anaconda3\envs\metagpt\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Anaconda3\envs\metagpt\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by rsager2001** [comment]
I also get this error.

**Comment by MelkorBalrog** [comment]
I am also getting this error, I tried to install Mermaid several times, to use Playwright, change the configuration, but nothing works, I still get similar errors, always ending on NotImplementedError

**Comment by shenchucheng** [comment]
This issue was caused by using the `WindowsSelectorEventLoopPolicy` in starup.py to fix #107. Howerer, on Windows, the default event loop [ProactorEventLoop](https://docs.python.org/3.9/library/asyncio-eventloop.html#asyncio.ProactorEventLoop) supports subprocesses, whereas [SelectorEventLoop](https://docs.python.org/3.9/library/asyncio-eventloop.html#asyncio.SelectorEventLoop) does not<sup>[\[1\]](https://docs.python.org/3.9/library/asyncio-platforms.html#subprocess-support-on-windows)</sup>. We have now resolved #107 using a different approach and no longer need to utilize WindowsSelectorEventLoopPolicy to fix this issue.
