### ISSUE TITLE
Erroring While Running Startup Prompt, While Generating Competitive analysis

### ISSUE THREAD

**Issue by Pvision71** [geekan/MetaGPT#334]
2023-09-17 23:07:53.888 | INFO     | metagpt.provider.openai_api:update_cost:89 - Total running cost: $0.140 | Max budget: $3.000 | Current cost: $0.065, prompt_tokens: 1353, completion_tokens: 410
C:\Users\xxxx\AppData\Roaming\npm\mmdc
C:\Users\xxxx\AppData\Roaming\npm\mmdc.cmd
2023-09-17 23:07:54.028 | INFO     | metagpt.utils.mermaid:mermaid_to_file:44 - Generating C:\Research\Projects\metagpt\workspace\supply_chain_optimization\resources\competitive_analysis.pdf..
Traceback (most recent call last):
  File "C:\Research\Projects\metagpt\startup.py", line 68, in <module>
    fire.Fire(main)
  File "C:\Users\xxxx\.conda\envs\metagpt\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\.conda\envs\metagpt\Lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\.conda\envs\metagpt\Lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Research\Projects\metagpt\startup.py", line 63, in main
    asyncio.run(startup(idea, investment, n_round,
  File "C:\Users\xxxx\.conda\envs\metagpt\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\.conda\envs\metagpt\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\.conda\envs\metagpt\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Research\Projects\metagpt\startup.py", line 40, in startup
    await company.run(n_round=n_round)
  File "C:\Research\Projects\metagpt\metagpt\software_company.py", line 60, in run
    await self.environment.run()
  File "C:\Research\Projects\metagpt\metagpt\environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "C:\Research\Projects\metagpt\metagpt\roles\role.py", line 240, in run
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Research\Projects\metagpt\metagpt\roles\role.py", line 209, in _react
    return await self._act()
           ^^^^^^^^^^^^^^^^^
  File "C:\Research\Projects\metagpt\metagpt\roles\role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Research\Projects\metagpt\metagpt\actions\design_api.py", line 142, in run
    await self._save(context, system_design)
  File "C:\Research\Projects\metagpt\metagpt\actions\design_api.py", line 135, in _save
    await self._save_prd(docs_path, resources_path, context[-1].content)
  File "C:\Research\Projects\metagpt\metagpt\actions\design_api.py", line 109, in _save_prd
    await mermaid_to_file(quadrant_chart, resources_path / 'competitive_analysis')
  File "C:\Research\Projects\metagpt\metagpt\utils\mermaid.py", line 62, in mermaid_to_file
    process = await asyncio.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\.conda\envs\metagpt\Lib\asyncio\subprocess.py", line 221, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\.conda\envs\metagpt\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\.conda\envs\metagpt\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by Pvision71** [comment]
Thank you, Shall i reclone and run the same, Plz Advise

**Comment by shenchucheng** [comment]
> Thank you, Shall i reclone and run the same, Plz Advise

Just do a `git pull` and rerun the same.

**Comment by ijuubs** [comment]
2023-09-23 06:10:55.974 | INFO     | metagpt.utils.mermaid:mermaid_to_file:43 - Generating C:\Users\nandn\AppData\Local\apps\Meta\metagpt\workspace\fast_food_landing_page\resources\competitive_analysis.pdf..
Traceback (most recent call last):
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\startup.py", line 73, in <module>
    fire.Fire(main)
  File "c:\users\nandn\appdata\local\programs\python\python311\lib\site-packages\fire-0.4.0-py3.11.egg\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\nandn\appdata\local\programs\python\python311\lib\site-packages\fire-0.4.0-py3.11.egg\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "c:\users\nandn\appdata\local\programs\python\python311\lib\site-packages\fire-0.4.0-py3.11.egg\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\startup.py", line 69, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests, implement))
  File "C:\Users\nandn\.conda\envs\metagpt\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\nandn\.conda\envs\metagpt\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nandn\.conda\envs\metagpt\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\startup.py", line 46, in startup
    await company.run(n_round=n_round)
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\metagpt\software_company.py", line 60, in run
    await self.environment.run()
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\metagpt\environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\metagpt\roles\role.py", line 240, in run
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\metagpt\roles\role.py", line 209, in _react
    return await self._act()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\metagpt\roles\role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\metagpt\actions\design_api.py", line 210, in run
    await self._save(context, system_design)
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\metagpt\actions\design_api.py", line 202, in _save
    await self._save_prd(docs_path, resources_path, context)
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\metagpt\actions\design_api.py", line 172, in _save_prd
    await mermaid_to_file(quadrant_chart, resources_path / "competitive_analysis")
  File "C:\Users\nandn\AppData\Local\apps\Meta\metagpt\metagpt\utils\mermaid.py", line 61, in mermaid_to_file
    process = await asyncio.create_subprocess_shell(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nandn\.conda\envs\metagpt\Lib\asyncio\subprocess.py", line 208, in create_subprocess_shell
    transport, protocol = await loop.subprocess_shell(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nandn\.conda\envs\metagpt\Lib\asyncio\base_events.py", line 1661, in subprocess_shell
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nandn\.conda\envs\metagpt\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

i am still facing this issue. crashes after competitive analysis.

**Comment by JaCoderX** [comment]
having the same issue with competitive analysis
