### ISSUE TITLE
incompatible architecture (have 'x86_64', need 'arm64'

### ISSUE THREAD

**Issue by erbrito** [geekan/MetaGPT#340]
I installed using virtualenv (not conda) when try to execute on macbook pro m2 I got the following error (% python --version
Python 3.10.8):
```
 python startup.py "Write a cli snake game based on pygame"
Traceback (most recent call last):
  File "/Users/ebrito/metagpt/startup.py", line 7, in <module>
    from metagpt.roles import Architect, Engineer, ProductManager
  File "/Users/ebrito/metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/Users/ebrito/metagpt/metagpt/roles/role.py", line 15, in <module>
    from metagpt.config import CONFIG
  File "/Users/ebrito/metagpt/metagpt/config.py", line 14, in <module>
    from metagpt.utils.singleton import Singleton
  File "/Users/ebrito/metagpt/metagpt/utils/__init__.py", line 9, in <module>
    from metagpt.utils.read_document import read_docx
  File "/Users/ebrito/metagpt/metagpt/utils/read_document.py", line 9, in <module>
    import docx
  File "/Users/ebrito/metagpt/metagpt-env/lib/python3.10/site-packages/docx/__init__.py", line 3, in <module>
    from docx.api import Document  # noqa
  File "/Users/ebrito/metagpt/metagpt-env/lib/python3.10/site-packages/docx/api.py", line 14, in <module>
    from docx.package import Package
  File "/Users/ebrito/metagpt/metagpt-env/lib/python3.10/site-packages/docx/package.py", line 9, in <module>
    from docx.opc.package import OpcPackage
  File "/Users/ebrito/metagpt/metagpt-env/lib/python3.10/site-packages/docx/opc/package.py", line 9, in <module>
    from docx.opc.part import PartFactory
  File "/Users/ebrito/metagpt/metagpt-env/lib/python3.10/site-packages/docx/opc/part.py", line 12, in <module>
    from .oxml import serialize_part_xml
  File "/Users/ebrito/metagpt/metagpt-env/lib/python3.10/site-packages/docx/opc/oxml.py", line 12, in <module>
    from lxml import etree
ImportError: dlopen(/Users/ebrito/metagpt/metagpt-env/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so, 0x0002): tried: '/Users/ebrito/metagpt/metagpt-env/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ebrito/metagpt/metagpt-env/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so' (no such file), '/Users/ebrito/metagpt/metagpt-env/lib/python3.10/site-packages/lxml/etree.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by alitrack** [comment]
lxml 4.9.3(depended by python_docx) has no Python 3.10 version built distribution for macOS M1/M2, so when you install MetaGPT, you have to install lxml from source code.


<img width="856" alt="image" src="https://github.com/geekan/MetaGPT/assets/20972179/72a261bb-850d-4080-9553-e3eeb10ea4a3">

from Python 3.11 it has  macosx_11_0_universal2 version.
