### ISSUE TITLE
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by veithly** [geekan/MetaGPT#344]
env: Windows11, Anaconda, python3.10
I try to run startup.py, when it make pdf, an error occur:
```
2023-09-20 15:20:35.175 | INFO     | metagpt.provider.openai_api:update_cost:89 - Total running cost: $0.009 | Max budget: $3.000 | Current cost: $0.003, prompt_tokens: 1188, completion_tokens: 601
C:\Program Files\nodejs\mmdc
C:\Program Files\nodejs\mmdc.cmd
2023-09-20 15:20:35.543 | INFO     | metagpt.utils.mermaid:mermaid_to_file:44 - Generating D:\Project\metagpt\workspace\cryptocurrency_quantification\resources\competitive_analysis.pdf..
Traceback (most recent call last):
  File "D:\Project\metagpt\startup.py", line 72, in <module>
    fire.Fire(main)
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:\Project\metagpt\startup.py", line 68, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests, implement))
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\Project\metagpt\startup.py", line 47, in startup
    await company.run(n_round=n_round)
  File "D:\Project\metagpt\metagpt\software_company.py", line 60, in run
    await self.environment.run()
  File "D:\Project\metagpt\metagpt\environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "D:\Project\metagpt\metagpt\roles\role.py", line 240, in run
    rsp = await self._react()
  File "D:\Project\metagpt\metagpt\roles\role.py", line 209, in _react
    return await self._act()
  File "D:\Project\metagpt\metagpt\roles\role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "D:\Project\metagpt\metagpt\actions\design_api.py", line 142, in run
    await self._save(context, system_design)
  File "D:\Project\metagpt\metagpt\actions\design_api.py", line 135, in _save
    await self._save_prd(docs_path, resources_path, context[-1].content)
  File "D:\Project\metagpt\metagpt\actions\design_api.py", line 109, in _save_prd
    await mermaid_to_file(quadrant_chart, resources_path / 'competitive_analysis')
  File "D:\Project\metagpt\metagpt\utils\mermaid.py", line 62, in mermaid_to_file
    process = await asyncio.create_subprocess_exec(
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\asyncio\base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\asyncio\windows_events.py", line 389, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\asyncio\windows_events.py", line 885, in _start
    self._proc = windows_utils.Popen(
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Ricky\anaconda3\envs\metagpt\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
```

**Comment by shenchucheng** [comment]
It encounters several challenges when running on the Windows platform with the Node.js version of Mermaid-CLI. Fortunately, there are alternative solutions available, such as Python libraries like Playwright, pyppeteer, or mermaid.ink, which can be used to convert Mermaid charts into SVG, PNG, and PDF formats. For more information, please refer to the latest README at [MetaGPT](https://github.com/geekan/MetaGPT).

**Comment by veithly** [comment]
Thanks your PR, it worked!
