### ISSUE TITLE
_make_subprocess_transport raise NotImplementedError

### ISSUE THREAD

**Issue by dmagalw** [geekan/MetaGPT#346]
I tried a few installs and configurations but get the same result every time "NotImplementedError"

`C:\Users\danie\AppData\Roaming\npm\mmdc
C:\Users\danie\AppData\Roaming\npm\mmdc.cmd
2023-09-20 09:27:30.266 | INFO     | metagpt.utils.mermaid:mermaid_to_file:44 - Generating C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\workspace\tic_tac_toe\resources\competitive_analysis.pdf..
Traceback (most recent call last):
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\startup.py", line 72, in <module>
    fire.Fire(main)
  File "C:\Users\danie\.virtualenvs\metaGPT-JC72EhXR\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\.virtualenvs\metaGPT-JC72EhXR\Lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\.virtualenvs\metaGPT-JC72EhXR\Lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\startup.py", line 68, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests, implement))
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\startup.py", line 47, in startup
    await company.run(n_round=n_round)
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\metagpt\software_company.py", line 60, in run
    await self.environment.run()
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\metagpt\environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\metagpt\roles\role.py", line 240, in run
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\metagpt\roles\role.py", line 209, in _react
    return await self._act()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\metagpt\roles\role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\metagpt\actions\design_api.py", line 142, in run
    await self._save(context, system_design)
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\metagpt\actions\design_api.py", line 135, in _save
    await self._save_prd(docs_path, resources_path, context[-1].content)
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\metagpt\actions\design_api.py", line 109, in _save_prd
    await mermaid_to_file(quadrant_chart, resources_path / 'competitive_analysis')
  File "C:\Users\danie\PycharmProjects\metaGPT\MetaGPT\metagpt\utils\mermaid.py", line 62, in mermaid_to_file
    process = await asyncio.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\asyncio\subprocess.py", line 221, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
(metaGPT) PS C:\Users\danie\PycharmProjects\metaGPT\MetaGPT> 
`

**Comment by shenchucheng** [comment]
On Windows, the default event loop [ProactorEventLoop](https://docs.python.org/3.8/library/asyncio-eventloop.html#asyncio.ProactorEventLoop) supports subprocesses, whereas [SelectorEventLoop](https://docs.python.org/3.8/library/asyncio-eventloop.html#asyncio.SelectorEventLoop) does not. Did you manually set the event loop to SelectorEventLoop?

**Comment by Noorsimar** [comment]
same error:

```
  File "C:\Users\mar\PycharmProjects\MetaGPT\metagpt\actions\design_api.py", line 142, in run
    await self._save(context, system_design)
  File "C:\Users\mar\PycharmProjects\MetaGPT\metagpt\actions\design_api.py", line 135, in _save
    await self._save_prd(docs_path, resources_path, context[-1].content)
  File "C:\Users\mar\PycharmProjects\MetaGPT\metagpt\actions\design_api.py", line 109, in _save_prd
    await mermaid_to_file(quadrant_chart, resources_path / 'competitive_analysis')
  File "C:\Users\mar\PycharmProjects\MetaGPT\metagpt\utils\mermaid.py", line 62, in mermaid_to_file
    process = await asyncio.create_subprocess_exec(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mar\anaconda3\envs\metagpt\Lib\asyncio\subprocess.py", line 221, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mar\anaconda3\envs\metagpt\Lib\asyncio\base_events.py", line 1694, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mar\anaconda3\envs\metagpt\Lib\asyncio\base_events.py", line 502, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```
How can we change the eventloop to ProactorEventLoop?

**Comment by shenchucheng** [comment]
@Noorsimar This issue is caused by the fact that we are using the sk_function from [semantic-kernel](https://github.com/microsoft/semantic-kernel) in our recent commit. It sets the event loop policy to SelectorEventLoopPolicy within the semantic-kernel on windows, as can be seen here: https://github.com/microsoft/semantic-kernel/blob/ef4c5a53a5f1e9c3bd7821b6631763082123cfc1/python/semantic_kernel/orchestration/sk_function.py#L43. However, the SelectorEventLoop on Windows does not support subprocesses. I have submitted a [PR](https://github.com/geekan/MetaGPT/pull/355) to Metagpt to resolve this issue temporarily.
