### ISSUE TITLE
windows运行报错

### ISSUE THREAD

**Issue by RyanLookchard** [geekan/MetaGPT#4]
PS D:\MetaGPT\metagpt> python startup.py "写一个命令行贪吃蛇"
2023-07-04 13:05:13.298 | INFO     | metagpt.config:__init__:43 - Config loading done.
2023-07-04 13:05:13.299 | INFO     | metagpt.config:__init__:49 - Set OPENAI_API_BASE in case of network issues
Traceback (most recent call last):
  File "D:\MetaGPT\metagpt\startup.py", line 5, in <module>
    from metagpt.software_company import SoftwareCompany
  File "D:\MetaGPT\metagpt\metagpt\software_company.py", line 13, in <module>
    from metagpt.actions import BossRequirement
  File "D:\MetaGPT\metagpt\metagpt\actions\__init__.py", line 14, in <module>
    from metagpt.actions.design_api import WriteDesign
  File "D:\MetaGPT\metagpt\metagpt\actions\design_api.py", line 15, in <module>
    from metagpt.utils.common import mermaid_to_file
ImportError: cannot import name 'mermaid_to_file' from 'metagpt.utils.common' (D:\MetaGPT\metagpt\metagpt\utils\common.py)
PS D:\MetaGPT\metagpt>

**Comment by geekan** [comment]
fixed, pull again. @RyanLookchard
