### ISSUE TITLE
tenacity.RetryError: RetryError[<Future at 0xffff670e6bb0 state=finished raised ValidationError>] when using --code_review True

### ISSUE THREAD

**Issue by reijin90** [geekan/MetaGPT#447]
I'm getting this error when trying to run with `--code_review True`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/metagpt/metagpt/actions/action.py", line 84, in _aask_v1
    instruct_content = output_class(**parsed_data)
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 4 validation errors for task
Logic Analysis -> 0 -> 1
  str type expected (type=type_error.str)
Logic Analysis -> 1 -> 1
  str type expected (type=type_error.str)
Logic Analysis -> 2 -> 1
  str type expected (type=type_error.str)
Logic Analysis -> 3 -> 1
  str type expected (type=type_error.str)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/metagpt/startup.py", line 72, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/app/metagpt/startup.py", line 68, in main
    asyncio.run(startup(idea, investment, n_round, code_review, run_tests, implement))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/metagpt/startup.py", line 47, in startup
    await company.run(n_round=n_round)
  File "/app/metagpt/metagpt/software_company.py", line 60, in run
    await self.environment.run()
  File "/app/metagpt/metagpt/environment.py", line 67, in run
    await asyncio.gather(*futures)
  File "/app/metagpt/metagpt/roles/role.py", line 240, in run
    rsp = await self._react()
  File "/app/metagpt/metagpt/roles/role.py", line 209, in _react
    return await self._act()
  File "/app/metagpt/metagpt/roles/role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "/app/metagpt/metagpt/actions/project_management.py", line 184, in run
    rsp = await self._aask_v1(prompt, "task", OUTPUT_MAPPING, format=format)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0xffff670e6bb0 state=finished raised ValidationError>]
```

Sorry for not providing more details, I'm absolutely clueless about the code base. I'd love to help, but I don't quite know how I can be of more help here.

**Comment by iorisa** [comment]
The following piece of code is a result of LLM not returning the desired output as per the prompt's requirements. I recommend using GPT-4.

```
pydantic.error_wrappers.ValidationError: 4 validation errors for task
Logic Analysis -> 0 -> 1
  str type expected (type=type_error.str)
Logic Analysis -> 1 -> 1
  str type expected (type=type_error.str)
Logic Analysis -> 2 -> 1
  str type expected (type=type_error.str)
Logic Analysis -> 3 -> 1
  str type expected (type=type_error.str)

```

**Comment by reijin90** [comment]
I am using GPT 4? 
```
...
OPENAI_API_MODEL: "gpt-4"
...
### for Research
MODEL_FOR_RESEARCHER_SUMMARY: gpt-3.5-turbo
MODEL_FOR_RESEARCHER_REPORT: gpt-3.5-turbo-16k
```

**Comment by iorisa** [comment]
It looks like you're using GPT-4 for the configuration.
This version of Software Company is executed step by step in a waterfall fashion, and if any step in the middle encounters an error, the entire process terminates abnormally. A version that supports iteration is still under development and has not been released yet.
