### ISSUE TITLE
Local LLama Model and LM Studio

### ISSUE THREAD

**Issue by MikeyBeez** [geekan/MetaGPT#459]
I edited config,yaml like this:

## Or, you can configure OPENAI_PROXY to access official OPENAI_API_BASE.
OPENAI_API_BASE: "https://localhost:1234/v1"
#OPENAI_PROXY: "http://127.0.0.1:8118"
OPENAI_API_KEY: NULL
#OPENAI_API_MODEL: "gpt-4"
MAX_TOKENS: 1500
RPM: 10

and when I run ❯ python startup.py "write a snake game based on pygame"  I get the following error:

Traceback (most recent call last):
  File "/Users/bard/Code/metagpt/startup.py", line 7, in <module>
    from metagpt.roles import (
  File "/Users/bard/Code/metagpt/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/Users/bard/Code/metagpt/metagpt/roles/role.py", line 15, in <module>
    from metagpt.config import CONFIG
  File "/Users/bard/Code/metagpt/metagpt/config.py", line 124, in <module>
    CONFIG = Config()
  File "/Users/bard/Code/metagpt/metagpt/utils/singleton.py", line 21, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/Users/bard/Code/metagpt/metagpt/config.py", line 51, in __init__
    raise NotConfiguredException("Set OPENAI_API_KEY or Anthropic_API_KEY first")
metagpt.config.NotConfiguredException: Set OPENAI_API_KEY or Anthropic_API_KEY first

I've even set an environment variable❯ echo $OPENAI_API_KEY
NULL

**Comment by stellaHSR** [comment]
OPENAI_API_KEY: NULL

**Comment by syaikhipin** [comment]
Can you set become ->  '' is that work?

**Comment by rastinder** [comment]
how did you solve it ? pls share config

**Comment by jbuck95** [comment]
I get a similar Error, can you maybe share your Config File/Explain how you configured it if you got it running with LM Studio? 

`File "C:\Users\Jan\miniconda3\envs\metagpt\Lib\site-packages\metagpt-0.5.2-py3.11.egg\metagpt\config.py", line 92, in get_default_llm_provider_enum
    raise NotConfiguredException("You should config a LLM configuration first")
metagpt.config.NotConfiguredException: You should config a LLM configuration first`

**Comment by 222gate** [comment]
bruh... you had it set to 'https'.... should be 'http'
this is the first line of your config lol "OPENAI_API_BASE: "https://localhost:1234/v1" "
simply remove the s

**Comment by 222gate** [comment]
> `OPENAI_API_KEY: NULL` You need to set the value here (set your gpt-4 key) , this cannot be NULL

somewhat true. i make it a habit of setting the model in my code to "OPENAI_MODEL: "local-model" whenever i use lm studio inference as thats how they have it in the example code. ive left it blank, ive seen people type in the actual model name, but find its easiest to just leave it at "local-model"

**Comment by jblogs** [comment]
You should set both base_url and api_base to local to make it work.

```
from llama_index.llms.openai import OpenAI

llm = OpenAI(base_url="http://localhost:1234/v1", api_base="http://localhost:1234/v1", api_key="not-needed", temperature=0)

Settings.llm = llm

```
