### ISSUE TITLE
Handling Rate Limit Reached

### ISSUE THREAD

**Issue by zerofill** [geekan/MetaGPT#46]
How do you handle rate limit issues? Hit this 3 times now.

Traceback (most recent call last):
  File "/home/user/repos/mgptphp/startup.py", line 32, in <module>
    fire.Fire(main)
  File "/home/user/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/repos/mgptphp/startupphp.py", line 28, in main
    asyncio.run(startup(idea, investment, n_round))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/repos/mgptphp/startupphp.py", line 15, in startup
    await company.run(n_round=n_round)
  File "/home/user/repos/mgptphp/metagpt/software_company.py", line 60, in run
    await self.environment.run()
  File "/home/user/repos/mgptphp/metagpt/environment.py", line 58, in run
    await asyncio.gather(*futures)
  File "/home/user/repos/mgptphp/metagpt/roles/role.py", line 223, in run
    rsp = await self._react()
  File "/home/user/repos/mgptphp/metagpt/roles/role.py", line 194, in _react
    return await self._act()
  File "/home/user/repos/mgptphp/metagpt/roles/engineer.py", line 139, in _act
    return await self._act_sp()
  File "/home/user/repos/mgptphp/metagpt/roles/engineer.py", line 124, in _act_sp
    code_rsp = await WriteCode().run(
  File "/home/user/repos/mgptphp/metagpt/actions/write_code.py", line 65, in run
    code_rsp = await self._aask(prompt)
  File "/home/user/repos/mgptphp/metagpt/actions/action.py", line 41, in _aask
    return await self.llm.aask(prompt, system_msgs)
  File "/home/user/repos/mgptphp/metagpt/provider/base_gpt_api.py", line 44, in aask
    rsp = await self.acompletion_text(message, stream=True)
  File "/home/user/repos/mgptphp/metagpt/provider/openai_api.py", line 27, in wrapper
    return await f(*args, **kwargs)
  File "/home/user/repos/mgptphp/metagpt/provider/openai_api.py", line 213, in acompletion_text
    return await self._achat_completion_stream(messages)
  File "/home/user/repos/mgptphp/metagpt/provider/openai_api.py", line 146, in _achat_completion_stream
    response = await openai.ChatCompletion.acreate(
  File "/home/user/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/home/user/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "/home/user/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 726, in _interpret_async_response
    self._interpret_response_line(
  File "/home/user/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-3Gxxxxxxxxxxxxxxxxxxxxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.

My startup.py is a bit different since I am feeding it a txt file:
`#!/usr/bin/env python
# -*- coding: utf-8 -*-
import asyncio
import fire
from metagpt.software_company import SoftwareCompany
from metagpt.roles import ProjectManager, ProductManager, Architect, Engineer

async def startup(idea: list, investment: float = 3.0, n_round: int = 5):
    """Run a startup. Be a boss."""
    company = SoftwareCompany()
    company.hire([ProductManager(), Architect(), ProjectManager(), Engineer(n_borg=5)])
    company.invest(investment)
    company.start_project("\n".join(idea))
    await company.run(n_round=n_round)

def main(idea_file: str, investment: float = 3.0, n_round: int = 5):
    """
    We are a software startup comprised of AI. By investing in us, you are empowering a future filled with limitless possibilities.
    :param idea_file: Path to the file containing the innovative idea.
    :param investment: As an investor, you have the opportunity to contribute a certain dollar amount to this AI company.
    :return:
    """
    with open(idea_file, 'r') as file:
        idea = file.read().splitlines()

    asyncio.run(startup(idea, investment, n_round))

if __name__ == '__main__':
    fire.Fire(main)
`

Also I have changed all Python to PHP and PHP PSR-2 Compliant for now... as I am having it generate PHP code.

But, on this particular run I am hitting rate limit issues. Is there a way people are handling that?

**Comment by zerofill** [comment]
Actually trying setting the config to:

MAX_TOKENS: 1000
RPM: 10

Will see how that goes.

**Comment by zerofill** [comment]
OK that kept it under the rate limit.
