### ISSUE TITLE
How to use FaissStore?

### ISSUE THREAD

**Issue by TITC** [geekan/MetaGPT#476]
I saw an example listed under the examples folder, https://github.com/geekan/MetaGPT/blob/ccc4c9e04debfdb8296c342d7a3f9606f407e007/examples/search_kb.py#L14-L16

but the example.json not provided.

I have try to make a fake data that's structure follow the code.
```json
[
    {
        "source": "Which facial cleanser is good for oily skin?",
        "output": "ABC cleanser is preferred by many with oily skin."
    },
    {
        "source": "Which facial cleanser is good for oily skin?",
        "output": "For oily skin, consider using DEF facial wash."
    },
    {
        "source": "Which facial cleanser is good for oily skin?",
        "output": "XYZ facial cleanser is suitable for oily skin."
    },
    {
        "source": "Which facial cleanser is good for oily skin?",
        "output": "XYZ facial cleanser is suitable for oily skin."
    },
    {
        "source": "Which facial cleanser is good for oily skin?",
        "output": "XYZ facial cleanser is suitable for oily skin."
    },
    {
        "source": "Is L'Oreal good to use?",
        "output": "L'Oreal is a reputable brand and is generally considered good."
    },
    {
        "source": "Is L'Oreal good to use?",
        "output": "L'Oreal is a popular brand with many positive reviews."
    },
    {
        "source": "Is L'Oreal good to use?",
        "output": "Many people find L'Oreal products effective."
    },
    {
        "source": "Is L'Oreal good to use?",
        "output": "L'Oreal is a popular brand with many positive reviews."
    },
    {
        "source": "Is L'Oreal good to use?",
        "output": "Many people find L'Oreal products effective."
    }
]
```
but the console gives me the below information, it seems my fake data is irrelevant to the SearchAndSummarize.
```shell
(metagpt) yhtao@PC:/mnt/d/github_repo/MetaGPT$ /home/yhtao/anaconda3/envs/metagpt/bin/python /mnt/d/github_repo/MetaGPT/examples/search_kb.py
2023-11-02 13:36:56.963 | INFO     | metagpt.config:__init__:44 - Config loading done.
2023-11-02 13:36:57.744 | INFO     | __main__:search:20 - User: Which facial cleanser is good for oily skin?
2023-11-02 13:36:57.745 | INFO     | metagpt.roles.role:_act:167 - Xiaomei(Sales): ready to SearchAndSummarize
Traceback (most recent call last):
  File "/mnt/d/github_repo/MetaGPT/examples/search_kb.py", line 26, in <module>
    asyncio.run(search())
  File "/home/yhtao/anaconda3/envs/metagpt/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/yhtao/anaconda3/envs/metagpt/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/mnt/d/github_repo/MetaGPT/examples/search_kb.py", line 21, in search
    result = await role.run(query)
  File "/mnt/d/github_repo/MetaGPT/metagpt/roles/role.py", line 240, in run
    rsp = await self._react()
  File "/mnt/d/github_repo/MetaGPT/metagpt/roles/role.py", line 209, in _react
    return await self._act()
  File "/mnt/d/github_repo/MetaGPT/metagpt/roles/role.py", line 168, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "/mnt/d/github_repo/MetaGPT/metagpt/actions/search_and_summarize.py", line 121, in run
    query = context[-1].content
IndexError: list index out of range
```

**Comment by seehi** [comment]
The fake data is ok, if you want to use FaissStore, you can directly use FaissStore("file_path").search("query"). 
The example needs code update to work.
