### ISSUE TITLE
have set https_proxy http_proxy but still meet a except "Error communicating with OpenAI" 

### ISSUE THREAD

**Issue by wodo2008** [geekan/MetaGPT#49]
I have set https_proxy http_proxy but still meet a except "Error communicating with OpenAI" . I find It can work when using `openai.Completion.create`. So why it cause exception when using `await openai.ChatCompletion.acreate` ? thanks 

**script:** 
jjxx@SH-jjxx-1 MetaGPT % /Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/bin/python startup.py "Write a cli snake game"

**logs:**
2023-07-15 17:37:57.233 | INFO     | metagpt.config:__init__:43 - Config loading done.
2023-07-15 17:37:57.233 | INFO     | metagpt.config:__init__:49 - Set OPENAI_API_BASE in case of network issues
2023-07-15 17:37:58.835 | INFO     | metagpt.software_company:invest:39 - Investment: $3.0.
2023-07-15 17:37:58.836 | INFO     | metagpt.roles.role:_act:153 - Alice(Product Manager): ready to WritePRD
2023-07-15 17:37:58.836 | WARNING  | metagpt.actions.search_and_summarize:run:114 - Configure SERPAPI_API_KEY to unlock full feature
Traceback (most recent call last):
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/asyncio/base_events.py", line 1080, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/asyncio/base_events.py", line 1110, in _create_connection_transport
    await waiter
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 54] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 668, in arequest_raw
    result = await session.request(**request_kwargs)
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.openai.com:443 ssl:default [Connection reset by peer]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/startup.py", line 29, in <module>
    fire.Fire(main)
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/startup.py", line 25, in main
    asyncio.run(startup(idea, investment, n_round))
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/startup.py", line 15, in startup
    await company.run(n_round=n_round)
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/software_company.py", line 60, in run
    await self.environment.run()
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/environment.py", line 58, in run
    await asyncio.gather(*futures)
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/roles/role.py", line 223, in run
    rsp = await self._react()
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/roles/role.py", line 194, in _react
    return await self._act()
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/roles/role.py", line 154, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/actions/write_prd.py", line 76, in run
    prd = await self._aask(prompt)
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/actions/action.py", line 41, in _aask
    return await self.llm.aask(prompt, system_msgs)
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/provider/base_gpt_api.py", line 44, in aask
    rsp = await self.acompletion_text(message, stream=True)
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/provider/openai_api.py", line 27, in wrapper
    return await f(*args, **kwargs)
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/provider/openai_api.py", line 213, in acompletion_text
    return await self._achat_completion_stream(messages)
  File "/Users/jjxx/wwwxx/workspace/mltasks/llmapp-ws/MetaGPT/metagpt/provider/openai_api.py", line 146, in _achat_completion_stream
    response = await openai.ChatCompletion.acreate(
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 372, in arequest
    result = await self.arequest_raw(
  File "/Users/jjxx/wwwxx/software/miniconda3/envs/py3.10/lib/python3.10/site-packages/openai/api_requestor.py", line 685, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI

**Comment by geekan** [comment]
Check this https://github.com/beidongjiedeguang/openai-forward and set proper FORWARD
