### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by lucas-tal** [geekan/MetaGPT#58]
'type' object is not subscriptable

**Comment by geekan** [comment]
could you provide more log?

**Comment by andotorg** [comment]
> could you provide more log?

2023-07-20 19:45:04.191 | INFO     | metagpt.config:__init__:43 - Config loading done.
Traceback (most recent call last):
  File "/Users/lucas/tal/github/ai/MetaGPT/startup.py", line 5, in <module>
    from metagpt.software_company import SoftwareCompany
  File "/Users/lucas/tal/github/ai/MetaGPT/metagpt/software_company.py", line 11, in <module>
    from metagpt.actions import BossRequirement
  File "/Users/lucas/tal/github/ai/MetaGPT/metagpt/actions/__init__.py", line 10, in <module>
    from metagpt.actions.action import Action
  File "/Users/lucas/tal/github/ai/MetaGPT/metagpt/actions/action.py", line 11, in <module>
    from metagpt.llm import LLM
  File "/Users/lucas/tal/github/ai/MetaGPT/metagpt/llm.py", line 9, in <module>
    from metagpt.provider.openai_api import OpenAIGPTAPI as LLM
  File "/Users/lucas/tal/github/ai/MetaGPT/metagpt/provider/__init__.py", line 9, in <module>
    from metagpt.provider.openai_api import OpenAIGPTAPI
  File "/Users/lucas/tal/github/ai/MetaGPT/metagpt/provider/openai_api.py", line 15, in <module>
    from metagpt.provider.base_gpt_api import BaseGPTAPI
  File "/Users/lucas/tal/github/ai/MetaGPT/metagpt/provider/base_gpt_api.py", line 15, in <module>
    class BaseGPTAPI(BaseChatbot):
  File "/Users/lucas/tal/github/ai/MetaGPT/metagpt/provider/base_gpt_api.py", line 19, in BaseGPTAPI
    def _user_msg(self, msg: str) -> dict[str, str]:
TypeError: 'type' object is not subscriptable

Process finished with exit code 1

**Comment by geekan** [comment]
Provide OS, python version, pip freeze result

**Comment by lucas-tal** [comment]
macos   python3.8.8

**Comment by geekan** [comment]
# Step 1: Ensure that NPM is installed on your system. Then install mermaid-js.
npm --version
sudo npm install -g @mermaid-js/mermaid-cli

# Step 2: Ensure that Python 3.9+ is installed on your system. You can check this by using:
python --version

# Step 3: Clone the repository to your local machine, and install it.
git clone https://github.com/geekan/metagpt
cd metagpt
python setup.py install

**Comment by lucas-tal** [comment]
thanks
