### ISSUE TITLE
llm configuration with ollama 

### ISSUE THREAD

**Issue by MARYAMJAHANIR** [geekan/MetaGPT#614]
@geekan i am using ollama model codellama and i configured this correctly:

#### if use self-host open llm model with openai-compatible interface
OPEN_LLM_API_BASE: "http://0.0.0.0:8000/v1"
OPEN_LLM_API_MODEL: "ollama/codellama"

but right now i am facing this issue kindly help:
(metagpt) (base) maryam_linux@Maryam:/mnt/c/Users/Hp/autogen_wsl/MetaGPT$ cd metagpt
(metagpt) (base) maryam_linux@Maryam:/mnt/c/Users/Hp/autogen_wsl/MetaGPT/metagpt$ python startup.py "Create a 2048 game in python"
2023-12-23 22:12:25.742 | INFO     | metagpt.const:get_metagpt_package_root:32 - Package root set to /mnt/c/Users/Hp/autogen_wsl/MetaGPT/metagpt
Key: http://0.0.0.0:8000/v1, Value: LLMProviderEnum.OPEN_LLM
Key: http://0.0.0.0:8000/v1, Value: LLMProviderEnum.OPEN_LLM
2023-12-23 22:12:26.816 | INFO     | metagpt.team:invest:84 - Investment: $3.0.
2023-12-23 22:12:26.820 | INFO     | metagpt.roles.role:_act:379 - Alice(Product Manager): ready to PrepareDocuments
2023-12-23 22:12:27.497 | INFO     | metagpt.utils.file_repository:save:60 - save to: /mnt/c/Users/Hp/autogen_wsl/MetaGPT/metagpt/workspace/20231223221226/docs/requirement.txt
2023-12-23 22:12:27.504 | INFO     | metagpt.roles.role:_act:379 - Alice(Product Manager): ready to WritePRD
2023-12-23 22:12:27.526 | ERROR    | metagpt.utils.common:log_it:433 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 0.001(s), this was the 1st time calling it. exp: 'OpenLLMGPTAPI' object has no attribute 'async_client'
2023-12-23 22:12:28.378 | ERROR    | metagpt.utils.common:log_it:433 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 0.853(s), this was the 2nd time calling it. exp: 'OpenLLMGPTAPI' object has no attribute 'async_client'
2023-12-23 22:12:29.130 | ERROR    | metagpt.utils.common:log_it:433 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 1.604(s), this was the 3rd time calling it. exp: 'OpenLLMGPTAPI' object has no attribute 'async_client'
2023-12-23 22:12:30.206 | ERROR    | metagpt.utils.common:log_it:433 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 2.680(s), this was the 4th time calling it. exp: 'OpenLLMGPTAPI' object has no attribute 'async_client'
2023-12-23 22:12:33.927 | ERROR    | metagpt.utils.common:log_it:433 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 6.402(s), this was the 5th time calling it. exp: 'OpenLLMGPTAPI' object has no attribute 'async_client'
2023-12-23 22:12:41.111 | ERROR    | metagpt.utils.common:log_it:433 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 13.585(s), this was the 6th time calling it. exp: 'OpenLLMGPTAPI' object has no attribute 'async_client'
2023-12-23 22:12:41.112 | WARNING  | metagpt.utils.common:wrapper:505 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2023-12-23 22:12:41.119 | ERROR    | metagpt.utils.common:wrapper:487 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/actions/action_node.py", line 256, in _aask_v1
    content = await self.llm.aask(prompt, system_msgs)
AttributeError: 'OpenLLMGPTAPI' object has no attribute 'async_client'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/utils/common.py", line 496, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/roles/role.py", line 528, in run
    rsp = await self.react()
tenacity.RetryError: RetryError[<Future at 0x7f1c30578070 state=finished raised AttributeError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/utils/common.py", line 482, in wrapper
    result = await func(self, *args, **kwargs)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/team.py", line 124, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/actions/action_node.py", line 256, in _aask_v1
    content = await self.llm.aask(prompt, system_msgs)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/provider/base_gpt_api.py", line 53, in aask
    rsp = await self.acompletion_text(message, stream=stream)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/provider/openai_api.py", line 274, in acompletion_text
    return await self._achat_completion_stream(messages)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/provider/openai_api.py", line 211, in _achat_completion_stream
    response: AsyncStream[ChatCompletionChunk] = await self.async_client.chat.completions.create(
AttributeError: 'OpenLLMGPTAPI' object has no attribute 'async_client'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/utils/common.py", line 496, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/roles/role.py", line 528, in run
    rsp = await self.react()
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/roles/role.py", line 479, in react
    rsp = await self._react()
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/roles/role.py", line 459, in _react
    rsp = await self._act()  # 这个rsp是否需要publish_message？
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/roles/role.py", line 380, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/actions/write_prd.py", line 105, in run
    prd_doc = await self._update_prd(
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/actions/write_prd.py", line 146, in _update_prd
    prd = await self._run_new_requirement(
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/actions/write_prd.py", line 126, in _run_new_requirement
    node = await WRITE_PRD_NODE.fill(context=context, llm=self.llm, schema=schema)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/actions/action_node.py", line 314, in fill
    return await self.simple_fill(schema, mode)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/metagpt-0.5.2-py3.9.egg/metagpt/actions/action_node.py", line 288, in simple_fill
    content, scontent = await self._aask_v1(prompt, class_name, mapping, schema=schema)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/maryam_linux/miniconda3/envs/metagpt/lib/python3.9/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f1c30578070 state=finished raised AttributeError>]

(metagpt) (base) maryam_linux@Maryam:/mnt/c/Users/Hp/autogen_wsl/MetaGPT/metagpt$

**Comment by geekan** [comment]
@better629

**Comment by better629** [comment]
@MARYAMJAHANIR Yes, there is a problem with ollama in main branch. Can you checkout with dev branch and have a try, and you can ref to doc `https://docs.deepwisdom.ai/main/en/guide/tutorials/integration_with_open_llm.html#ollama-api-interface`. We plan to merge main from dev this week.
