### ISSUE TITLE
用智普AI运行例子报错

### ISSUE THREAD

**Issue by xudengke** [geekan/MetaGPT#654]
**Bug description**
用智普AI运行例子llm_hello_world.py 报错

**Bug solved method**

**Environment information**

- LLM type and model name:
- System version:windows11
- Python version:3.10

- packages version:
- installation method: 

**Screenshots or logs**
C:/Programs/Python/Python310/python.exe d:/AI/MetaGPT-main/examples/llm_hello_world.py
2023-12-29 16:14:44.661 | INFO     | metagpt.const:get_metagpt_package_root:32 - Package root set to D:\AI\MetaGPT-main 
2023-12-29 16:14:49.173 | INFO     | metagpt.provider.openai_api:update_cost:91 - Total running cost: $0.000 | Max budget: $10.000 | Current cost: $0.000, prompt_tokens: 2, completion_tokens: 60
2023-12-29 16:14:49.174 | INFO     | __main__:main:16 -  Hello! I'm ZhiPuQingYan（智谱清言）, a language model jointly trained by KEG Lab of Tsinghua University and Zhipu AI Company. I'm here to answer your questions and provide help. How can I assist you today?
 Hello! I'm ZhiPuQingYan（智谱清言）, a language model jointly trained by KEG Lab of Tsinghua University and Zhipu AI Company. I'm here to answer your questions and provide help. How can I assist you today?Traceback (most recent call last):
  File "d:\AI\MetaGPT-main\examples\llm_hello_world.py", line 28, in <module>
    asyncio.run(main())
  File "C:\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "d:\AI\MetaGPT-main\examples\llm_hello_world.py", line 17, in main
    logger.info(await llm.aask_batch(["hi", "write python hello world."]))
  File "C:\Programs\Python\Python310\lib\site-packages\metagpt\provider\base_gpt_api.py", line 76, in aask_batch        
    rsp_text = await self.acompletion_text(context)
  File "C:\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line ity\__init__.py", line 314, in iter
    return fut.result()
  File "C:\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Programs\Python\Python310\lib\site-packages\metagpt\provider\zhipuai_api.py", line 134, in acompletion_text
    resp = await self._achat_completion(messages)
  File "C:\Programs\Python\Python310\lib\site-packages\metagpt\provider\zhipuai_api.py", line 80, in _achat_completion
    usage = resp.get("data").get("usage")
AttributeError: 'bytes' object has no attribute 'get'

**Comment by better629** [comment]
@xudengke Thanks to report it. Here has a fix pr https://github.com/geekan/MetaGPT/pull/662, wait to merge and try out with the dev branch. Thank you!

**Comment by better629** [comment]
@xudengke it fixed.
