### ISSUE TITLE
TypeError: 'async for' requires an object with __aiter__ method, got bytes

### ISSUE THREAD

**Issue by zjj1999** [geekan/MetaGPT#672]
**Bug description**
当我运行例子脚本比如https://github.com/geekan/MetaGPT/blob/main/examples/build_customized_agent.py的时候会报错TypeError: 'async for' requires an object with __aiter__ method, got bytes

**Screenshots or logs**
以下是报错log，不太确定发生了什么
Traceback (most recent call last):
  File "/Users/zhangjiajie/Documents/code/ConfigAgent/test/01firstagent.py", line 144, in <module>
    fire.Fire(main)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/fire/core.py", line 689, in _CallAndUpdateTrace
    component = loop.run_until_complete(fn(*varargs, **kwargs))
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/zhangjiajie/Documents/code/ConfigAgent/test/01firstagent.py", line 140, in main
    await team.run(n_round=n_round)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/team.py", line 79, in run
    await self.env.run()
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/environment.py", line 84, in run
    await asyncio.gather(*futures)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/roles/role.py", line 400, in run
    rsp = await self.react()
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/roles/role.py", line 352, in react
    rsp = await self._react()
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/roles/role.py", line 333, in _react
    rsp = await self._act()  # 这个rsp是否需要publish_message？
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/roles/role.py", line 269, in _act
    response = await self._rc.todo.run(self._rc.important_memory)
  File "/Users/zhangjiajie/Documents/code/ConfigAgent/test/01firstagent.py", line 35, in run
    rsp = await self._aask(prompt)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/actions/action.py", line 59, in _aask
    return await self.llm.aask(prompt, system_msgs)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/provider/base_gpt_api.py", line 53, in aask
    rsp = await self.acompletion_text(message, stream=stream)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/provider/zhipuai_api.py", line 133, in acompletion_text
    return await self._achat_completion_stream(messages)
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/provider/zhipuai_api.py", line 91, in _achat_completion_stream
    async for event in response.async_events():
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/provider/zhipuai/async_sse_client.py", line 22, in async_events
    async for chunk in self._aread():
  File "/Users/zhangjiajie/miniforge3/envs/metagpt/lib/python3.9/site-packages/metagpt/provider/zhipuai/async_sse_client.py", line 12, in _aread
    async for chunk in self._event_source:
TypeError: 'async for' requires an object with __aiter__ method, got bytes

**Comment by better629** [comment]
@zjj1999 you can try the latest main code.
