### ISSUE TITLE
MetaGPT\examples> python build_customized_agent.py 运行报错

### ISSUE THREAD

**Issue by LinightKira** [geekan/MetaGPT#686]
**Bug description**

官方Example 无法运行

**Bug solved method**

**Environment information**

- LLM type and model name: gpt-3.5-turbo-1106
- System version: Windows11
- Python version:3.11.3

- packages version: "0.5.2",
- installation method: git clone

**Screenshots or logs**

2024-01-04 20:59:56.816 | INFO     | metagpt.const:get_metagpt_package_root:32 - Package root set to f:\pythonproject\gpt_projects\agents\metagpt
2024-01-04 20:59:58.562 | INFO     | metagpt.config:get_default_llm_provider_enum:90 - OpenAI API Model: gpt-3.5-turbo-1106
2024-01-04 20:59:58.639 | INFO     | __main__:main:99 - write a function that calculates the product of a list and run it
2024-01-04 20:59:58.643 | INFO     | __main__:_act:83 - Alice(RunnableCoder): to do SimpleWriteCode()
```python
def calculate_product(lst):
    product = 1
    for num in lst:
        product *= num
    return product

# Runnable test cases
print(calculate_product([1, 2, 3, 4]))  # Output: 24
print(calculate_product([5, 6, 7]))     # Output: 210
```
2024-01-04 21:00:01.233 | INFO     | metagpt.provider.openai_api:update_cost:103 - Total running cost: $0.000 | Max budget: $10.000 | Current cost: $0.000, prompt_tokens: 73, completion_tokens: 78
2024-01-04 21:00:01.236 | INFO     | __main__:_act:83 - Alice(RunnableCoder): to do SimpleRunCode()
2024-01-04 21:00:01.262 | WARNING  | metagpt.utils.common:wrapper:505 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
Traceback (most recent call last):
  File "f:\pythonproject\gpt_projects\agents\metagpt\metagpt\utils\common.py", line 496, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\pythonproject\gpt_projects\agents\metagpt\metagpt\roles\role.py", line 542, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
  File "f:\pythonproject\gpt_projects\agents\metagpt\metagpt\roles\role.py", line 495, in react
    rsp = await self._act_by_order()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\pythonproject\gpt_projects\agents\metagpt\metagpt\roles\role.py", line 482, in _act_by_order
    rsp = await self._act()
          ^^^^^^^^^^^^^^^^^
  File "F:\PythonProject\GPT_Projects\Agents\MetaGPT\examples\build_customized_agent.py", line 89, in _act
    result = await todo.run(msg.content)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PythonProject\GPT_Projects\Agents\MetaGPT\examples\build_customized_agent.py", line 48, in run
    result = subprocess.run(["python3", "-c", code_text], capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\PythonProject\GPT_Projects\Agents\MetaGPT\examples\build_customized_agent.py", line 105, in <module>
    fire.Fire(main)
  File "F:\PythonProject\GPT_Projects\Agents\MetaGPT\venv\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PythonProject\GPT_Projects\Agents\MetaGPT\venv\Lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "F:\PythonProject\GPT_Projects\Agents\MetaGPT\venv\Lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PythonProject\GPT_Projects\Agents\MetaGPT\examples\build_customized_agent.py", line 100, in main
    result = asyncio.run(role.run(msg))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "f:\pythonproject\gpt_projects\agents\metagpt\metagpt\utils\common.py", line 512, in wrapper
    raise Exception(format_trackback_info(limit=None))
Exception: Traceback (most recent call last):
  File "f:\pythonproject\gpt_projects\agents\metagpt\metagpt\utils\common.py", line 496, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\pythonproject\gpt_projects\agents\metagpt\metagpt\roles\role.py", line 542, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
  File "f:\pythonproject\gpt_projects\agents\metagpt\metagpt\roles\role.py", line 495, in react
    rsp = await self._act_by_order()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\pythonproject\gpt_projects\agents\metagpt\metagpt\roles\role.py", line 482, in _act_by_order
    rsp = await self._act()
          ^^^^^^^^^^^^^^^^^
  File "F:\PythonProject\GPT_Projects\Agents\MetaGPT\examples\build_customized_agent.py", line 89, in _act
    result = await todo.run(msg.content)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PythonProject\GPT_Projects\Agents\MetaGPT\examples\build_customized_agent.py", line 48, in run
    result = subprocess.run(["python3", "-c", code_text], capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。

**Comment by voidking** [comment]
可以试一下最新版本，修复了很多问题。

**Comment by geekan** [comment]
If there are still problems, please reopen at any time
