### ISSUE TITLE
chatgml3 start example error

### ISSUE THREAD

**Issue by SuperbDong** [geekan/MetaGPT#705]
**Bug description**
I want to use the metaGPT with example mysql tutorial doc,then I start failed when I flower the guide with two case: write_tutorial.py and "write a cli blackjack game"

**Bug solved method**
write_tutorial.py show error :
2024-01-07 23:46:10.295 | ERROR    | metagpt.utils.common:extract_struct:233 - No <class 'dict'> found in the text.
2024-01-07 23:46:10.295 | INFO     | metagpt.roles.tutorial_assistant:_act:79 - {}
2024-01-07 23:46:10.295 | WARNING  | metagpt.utils.common:wrapper:511 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
Traceback (most recent call last):
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/common.py", line 502, in wrapper
    return await func(self, *args, **kwargs)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 482, in run
    rsp = await self.react()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/tutorial_assistant.py", line 90, in react
    msg = await super().react()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 452, in react
    rsp = await self._act_by_order()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 439, in _act_by_order
    rsp = await self._act()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/tutorial_assistant.py", line 80, in _act
    await self._handle_directory(resp)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/tutorial_assistant.py", line 60, in _handle_directory
    for first_dir in titles.get("directory"):
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/e/ml/1/write_tutorial.py", line 22, in <module>
    asyncio.run(main())
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/mnt/e/ml/1/write_tutorial.py", line 18, in main
    await role.run(topic)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/common.py", line 518, in wrapper
    raise Exception(format_trackback_info(limit=None))
Exception: Traceback (most recent call last):
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/common.py", line 502, in wrapper
    return await func(self, *args, **kwargs)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 482, in run
    rsp = await self.react()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/tutorial_assistant.py", line 90, in react
    msg = await super().react()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 452, in react
    rsp = await self._act_by_order()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 439, in _act_by_order
    rsp = await self._act()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/tutorial_assistant.py", line 80, in _act
    await self._handle_directory(resp)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/tutorial_assistant.py", line 60, in _handle_directory
    for first_dir in titles.get("directory"):
TypeError: 'NoneType' object is not iterable

 "write a cli blackjack game" show error:
metagpt "write a cli blackjack game"
2024-01-07 20:51:10.803 | INFO     | metagpt.const:get_metagpt_package_root:32 - Package root set to /mnt/e/ml/MetaGPT
2024-01-07 20:51:11.966 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPEN_LLM
^[[1;3D2024-01-07 20:51:24.215 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPEN_LLM
2024-01-07 20:51:24.327 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPEN_LLM
2024-01-07 20:51:24.352 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPEN_LLM
2024-01-07 20:51:24.365 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPEN_LLM
2024-01-07 20:51:24.384 | INFO     | metagpt.team:invest:86 - Investment: $3.0.
2024-01-07 20:51:24.386 | INFO     | metagpt.roles.role:_act:357 - Alice(Product Manager): to do PrepareDocuments(PrepareDocuments)
2024-01-07 20:51:24.689 | INFO     | metagpt.utils.file_repository:save:60 - save to: /mnt/e/ml/MetaGPT/workspace/20240107205124/docs/requirement.txt
2024-01-07 20:51:24.691 | INFO     | metagpt.roles.role:_act:357 - Alice(Product Manager): to do WritePRD(WritePRD)
Alice, I understand your goal. To create a successful product that meets market demands and user expectations, I will follow the instructions of the nodes and generate the output in the format example.

[CONTENT]
{
    "Language": "en_us",
    "Programming Language": "Python",
    "Original Requirements": "Write a CLI blackjack game",
    "Project Name": "blackjack_cli",
    "Product Goals": [
        "Create an engaging user experience",
        "Enhance accessibility and responsiveness",
        "Implement a more beautiful UI"
    ],
    "User Stories": [
        "As a user, I want to be able to choose difficulty levels",
        "As a user, I want to see my score after each game",
        "As a user, I want to get a restart button when I lose",
        "As a user, I want to see a beautiful UI that makes me feel good",
        "As a user, I want to play the game via the command line"
    ],
    "Competitive Analysis": [
        "Blackjack CLI A: Basic interface, lacks engagement features",
        "blackjackcli.com: Engaging UI with my best score shown",
        "blackjack.co: Responsive UI with my best score shown, but many ads"
    ],
    "Competitive Quadrant Chart": "quadrantChart\n    title \"Reach and engagement of campaigns\"\n    x-axis \"Low Reach\" --> \"High Reach\"\n    y-axis \"Low Engagement\" --> \"High Engagement\"\n    quadrant-1 \"We should expand\"\n    quadrant-2 \"Need to promote\"\n    quadrant-3 \"Re-evaluate\"\n    quadrant-4 \"May be improved\"\n    \"Campaign A\": [0.3, 0.6]\n    \"Campaign B\": [0.45, 0.23]\n    \"Campaign C\": [0.57, 0.69]\n    \"Campaign D\": [0.78, 0.34]\n    \"Campaign E\": [0.40, 0.34]\n    \"Campaign F\": [0.35, 0.78]\n    \"Our Target Product\": [0.5, 0.6]",
    "Requirement Analysis": "P0: Implement the game algorithm\nP1: Implement the user interface\nP2: Add difficulty levels\nP3: Add a best score feature\nP4: Add a restart button\nP5: Add a beautiful UI",
    "Requirement Pool": [
        [
            "P0",
            "Implement the game algorithm ..."
        ],
        [
            "P1",
            "Implement the user interface ..."
        ],
        [
            "P2",
            "Add difficulty levels ..."
        ],
        [
            "P3",
            "Add a best score feature ..."
        ],
        [
            "P4",
            "Add a restart button ..."
        ],
        [
            "P5",
            "Add a beautiful UI ..."
        ]
    ],
    "UI Design draft": "Basic blackjack game with a simple style and layout.",
    "Anything UNCLEAR": ""
}
[/CONTENT]Warning: model not found. Using cl100k_base encoding.
Warning: model not found. Using cl100k_base encoding.
2024-01-07 20:52:07.063 | INFO     | metagpt.provider.open_llm_api:update_cost:30 - Max budget: $3.000 | reference prompt_tokens: 942, completion_tokens: 649
2024-01-07 20:52:07.067 | INFO     | metagpt.utils.git_repository:rename_root:200 - Delete directory /mnt/e/ml/MetaGPT/workspace/blackjack_cli
2024-01-07 20:52:07.107 | INFO     | metagpt.utils.git_repository:rename_root:206 - Rename directory /mnt/e/ml/MetaGPT/workspace/20240107205124 to /mnt/e/ml/MetaGPT/workspace/blackjack_cli
2024-01-07 20:52:07.108 | WARNING  | metagpt.utils.common:wrapper:506 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-01-07 20:52:07.124 | ERROR    | metagpt.utils.common:wrapper:488 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/common.py", line 497, in wrapper
    return await func(self, *args, **kwargs)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 482, in run
    rsp = await self.react()
git.exc.NoSuchPathError: /mnt/e/ml/MetaGPT/workspace/blackjack_cli

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/common.py", line 483, in wrapper
    result = await func(self, *args, **kwargs)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/team.py", line 133, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/common.py", line 497, in wrapper
    return await func(self, *args, **kwargs)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 482, in run
    rsp = await self.react()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 450, in react
    rsp = await self._react()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 429, in _react
    rsp = await self._act()  # 这个rsp是否需要publish_message？
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 358, in _act
    response = await self.rc.todo.run(self.rc.history)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/actions/write_prd.py", line 102, in run
    prd_doc = await self._update_prd(
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/actions/write_prd.py", line 144, in _update_prd
    prd = await self._run_new_requirement(
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/actions/write_prd.py", line 125, in _run_new_requirement
    await self._rename_workspace(node)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/actions/write_prd.py", line 189, in _rename_workspace
    CONFIG.git_repo.rename_root(CONFIG.project_name)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/git_repository.py", line 207, in rename_root
    self._repository = Repo(new_path)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/git/repo/base.py", line 215, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /mnt/e/ml/MetaGPT/workspace/blackjack_cli

/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/schema.py:93: UserWarning: Pydantic serializer warnings:
  Expected `str` but got `dict` - serialized value may not be as expected
  ret = handler(value)
/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/pydantic/functional_serializers.py:272: UserWarning: Pydantic serializer warnings:
  Expected `str` but got `dict` - serialized value may not be as expected
  lambda x, h: h(x), schema=core_schema.any_schema()
**Environment information**
win11 WSL
conda python 3.9
chatGML3 6B

finllay I want to known that how to join the wechat ,thanks u.

**Comment by better629** [comment]
The `write_tutorial.py show error` is due to that chatglm3-6b can't follow the instruction inside `DIRECTORY_PROMPT` to output a json structure. So maybe you can have openai models or other bigger llm to have a try.

**Comment by iorisa** [comment]
>git.exc.NoSuchPathError: /mnt/e/ml/MetaGPT/workspace/blackjack_cli
Is this path writable?

**Comment by SuperbDong** [comment]
> The `write_tutorial.py show error` is due to that chatglm3-6b can't follow the instruction inside `DIRECTORY_PROMPT` to output a json structure. So maybe you can have openai models or other bigger llm to have a try.

I hava use the fastchat with openapi server(guide is show that fastchat support chatgml3 with openai api server). Then I hava try to config json or markdown both fail.Whether I can follow link doc(fastchat doc) content,just can use openai or guide have show models.

**Comment by SuperbDong** [comment]
> > git.exc.NoSuchPathError: /mnt/e/ml/MetaGPT/workspace/blackjack_cli
> 
> Is the path `/mnt/e/ml/MetaGPT/` writable?

The path had writeable and workspace tmp dir was made.

**Comment by iorisa** [comment]
I noticed that your code path is under `python3.9/site-packages`. Are you using the "import metagpt" method to use its code?

**Comment by iorisa** [comment]
```
2024-01-07 20:52:07.107 | INFO | metagpt.utils.git_repository:rename_root:206 - Rename directory /mnt/e/ml/MetaGPT/workspace/20240107205124 to /mnt/e/ml/MetaGPT/workspace/blackjack_cli
2024-01-07 20:52:07.124 | ERROR | metagpt.utils.common:wrapper:488 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/common.py", line 497, in wrapper
return await func(self, *args, **kwargs)
File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 482, in run
rsp = await self.react()
git.exc.NoSuchPathError: /mnt/e/ml/MetaGPT/workspace/blackjack_cli
```

**Comment by iorisa** [comment]
Judging from the logs, it seems that the folder renaming failed. What operating system are you using?

```text
2024-01-07 20:51:24.689 | INFO | metagpt.utils.file_repository:save:60 - save to: /mnt/e/ml/MetaGPT/workspace/20240107205124/docs/requirement.txt

2024-01-07 20:52:07.107 | INFO | metagpt.utils.git_repository:rename_root:206 - Rename directory /mnt/e/ml/MetaGPT/workspace/20240107205124 to /mnt/e/ml/MetaGPT/workspace/blackjack_cli

2024-01-07 20:52:07.124 | ERROR | .....
git.exc.NoSuchPathError: /mnt/e/ml/MetaGPT/workspace/blackjack_cli
```

**Comment by SuperbDong** [comment]
> Judging from the logs, it seems that the folder renaming failed. What operating system are you using?
> 
> ```
> 2024-01-07 20:51:24.689 | INFO | metagpt.utils.file_repository:save:60 - save to: /mnt/e/ml/MetaGPT/workspace/20240107205124/docs/requirement.txt
> 
> 2024-01-07 20:52:07.107 | INFO | metagpt.utils.git_repository:rename_root:206 - Rename directory /mnt/e/ml/MetaGPT/workspace/20240107205124 to /mnt/e/ml/MetaGPT/workspace/blackjack_cli
> 
> 2024-01-07 20:52:07.124 | ERROR | .....
> git.exc.NoSuchPathError: /mnt/e/ml/MetaGPT/workspace/blackjack_cli
> ```

I use the win11 WSL,and I find the path that make succesful.I don't known why the error log was shown.

**Comment by iorisa** [comment]
Can you confirm whether the folder /mnt/e/ml/MetaGPT/workspace/20240107205124 still exists?
I've encountered issues with folder renaming on Windows 10 before.

**Comment by SuperbDong** [comment]
> Can you confirm whether the folder `/mnt/e/ml/MetaGPT/workspace/20240107205124` still exists? I've encountered issues with folder renaming on Windows 10 before.

ok.I'm working on the company now, when I go home to confirm it, 3Q for u answer.

**Comment by iorisa** [comment]
Also, please check whether the `/mnt/e/ml/MetaGPT/workspace/blackjack_cli` folder is present. 
Based on the logs, it seems that during the renaming process, the existence of `blackjack_cli` was detected, leading to a "delete directory" operation before the subsequent rename operation from `20240107205124` to `blackjack_cli`.


```
2024-01-07 20:52:07.067 | INFO | metagpt.utils.git_repository:rename_root:200 - Delete directory /mnt/e/ml/MetaGPT/workspace/blackjack_cli
2024-01-07 20:52:07.107 | INFO | metagpt.utils.git_repository:rename_root:206 - Rename directory /mnt/e/ml/MetaGPT/workspace/20240107205124 to /mnt/e/ml/MetaGPT/workspace/blackjack_cli
```

**Comment by better629** [comment]
> Whether I can follow link doc(fastchat doc) content,just can use openai or guide have show models

@SuperbDong what does this means? 
Maybe you can use openai models to run the project firstly, and then try the open llms since open llms can't have the same instruction following ability as openai models.

**Comment by SuperbDong** [comment]
> Also, please check whether the `/mnt/e/ml/MetaGPT/workspace/blackjack_cli` folder is present. Based on the logs, it seems that during the renaming process, the existence of `blackjack_cli` was detected, leading to a "delete directory" operation before the subsequent rename operation from `20240107205124` to `blackjack_cli`.
> 
> ```
> 2024-01-07 20:52:07.067 | INFO | metagpt.utils.git_repository:rename_root:200 - Delete directory /mnt/e/ml/MetaGPT/workspace/blackjack_cli
> 2024-01-07 20:52:07.107 | INFO | metagpt.utils.git_repository:rename_root:206 - Rename directory /mnt/e/ml/MetaGPT/workspace/20240107205124 to /mnt/e/ml/MetaGPT/workspace/blackjack_cli
> ```

metagpt "write a cli blackjack game"
2024-01-09 00:18:14.624 | INFO     | metagpt.const:get_metagpt_package_root:32 - Package root set to /mnt/e/ml/1
2024-01-09 00:18:15.723 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPEN_LLM
2024-01-09 00:18:26.587 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPEN_LLM
2024-01-09 00:18:26.615 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPEN_LLM
2024-01-09 00:18:26.630 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPEN_LLM
2024-01-09 00:18:26.644 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPEN_LLM
2024-01-09 00:18:26.656 | INFO     | metagpt.team:invest:86 - Investment: $3.0.


2024-01-09 00:18:26.658 | INFO     | metagpt.roles.role:_act:357 - Alice(Product Manager): to do PrepareDocuments(PrepareDocuments)






2024-01-09 00:18:26.946 | INFO     | metagpt.utils.file_repository:save:60 - save to: /mnt/e/ml/1/workspace/20240109001826/docs/requirement.txt


2024-01-09 00:18:26.951 | INFO     | metagpt.roles.role:_act:357 - Alice(Product Manager): to do WritePRD(WritePRD)






Alice, I understand your goal is to efficiently create a successful product that meets market demands and user expectations. The constraint is to use the same language as the user requirements for seamless communication. Can you please provide me with the output based on the given context?

[CONTENT]
{
    "Language": "en_us",
    "Programming Language": "Python",
    "Original Requirements": "Write a CLI blackjack game",
    "Project Name": "blackjack_cli",
    "Product Goals": [
        "Create an engaging user experience",
        "Enhance accessibility and responsiveness",
        "Implement a more beautiful UI"
    ],
    "User Stories": [
        "As a player, I want to be able to choose difficulty levels",
        "As a player, I want to see my score after each game",
        "As a player, I want to get a restart button when I lose",
        "As a player, I want to see a beautiful UI that makes me feel good",
        "As a player, I want to play the game via the command line"
    ],
    "Competitive Analysis": [
        "Blackjack CLI A: Basic interface, lacks user experience",
        "blackjack-cli.com: Engaging user experience with my best score shown",
        "blackjackgame.com: Responsive UI with my best score shown, but many ads"
    ],
    "Competitive Quadrant Chart": "quadrantChart\n    title \"Reach and engagement of campaigns\"\n    x-axis \"Low Reach\" --> \"High Reach\"\n    y-axis \"Low Engagement\" --> \"High Engagement\"\n    quadrant-1 \"We should expand\"\n    quadrant-2 \"Need to promote\"\n    quadrant-3 \"Re-evaluate\"\n    quadrant-4 \"May be improved\"\n    \"Campaign A\": [0.3, 0.6]\n    \"Campaign B\": [0.45, 0.23]\n    \"Campaign C\": [0.57, 0.69]\n    \"Campaign D\": [0.78, 0.34]\n    \"Campaign E\": [0.40, 0.34]\n    \"Campaign F\": [0.35, 0.78]\n    \"Our Target Product\": [0.5, 0.6]",
    "Requirement Analysis": "P0: Implement the game logic and rules\nP1: Implement the user interface\nP2: Add support for different game modes\nP3: Implement a command-line interface\nP4: Ensure the game is accessible and responsive\nP5: Implement a more beautiful UI",
    "Requirement Pool": [
        [
            "P0",
            "Implement the game logic and rules"
        ],
        [
            "P1",
            "Implement the user interface"
        ],
        [
            "P2",
            "Add support for different game modes"
        ],
        [
            "P3",
            "Implement a command-line interface"
        ],
        [
            "P4",
            "Ensure the game is accessible and responsive"
        ],
        [
            "P5",
            "Implement a more beautiful UI"
        ]
    ],
    "UI Design draft": "A simple blackjack game with a clean and minimalistic design.",
    "Anything UNCLEAR": ""
}Warning: model not found. Using cl100k_base encoding.
Warning: model not found. Using cl100k_base encoding.
2024-01-09 00:18:49.773 | INFO     | metagpt.provider.open_llm_api:update_cost:30 - Max budget: $3.000 | reference prompt_tokens: 942, completion_tokens: 682
2024-01-09 00:18:49.777 | INFO     | metagpt.utils.git_repository:rename_root:206 - Rename directory /mnt/e/ml/1/workspace/20240109001826 to /mnt/e/ml/1/workspace/blackjack_cli
2024-01-09 00:18:49.778 | WARNING  | metagpt.utils.common:wrapper:511 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-01-09 00:18:49.828 | ERROR    | metagpt.utils.common:wrapper:491 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/common.py", line 502, in wrapper
    return await func(self, *args, **kwargs)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 482, in run
    rsp = await self.react()
git.exc.NoSuchPathError: /mnt/e/ml/1/workspace/blackjack_cli

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/common.py", line 486, in wrapper
    result = await func(self, *args, **kwargs)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/team.py", line 133, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/common.py", line 502, in wrapper
    return await func(self, *args, **kwargs)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 482, in run
    rsp = await self.react()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 450, in react
    rsp = await self._react()
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 429, in _react
    rsp = await self._act()  # 这个rsp是否需要publish_message？
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/roles/role.py", line 358, in _act
    response = await self.rc.todo.run(self.rc.history)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/actions/write_prd.py", line 102, in run
    prd_doc = await self._update_prd(
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/actions/write_prd.py", line 144, in _update_prd
    prd = await self._run_new_requirement(
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/actions/write_prd.py", line 125, in _run_new_requirement
    await self._rename_workspace(node)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/actions/write_prd.py", line 189, in _rename_workspace
    CONFIG.git_repo.rename_root(CONFIG.project_name)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/utils/git_repository.py", line 207, in rename_root
    self._repository = Repo(new_path)
  File "/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/git/repo/base.py", line 215, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /mnt/e/ml/1/workspace/blackjack_cli


/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/metagpt/schema.py:93: UserWarning: Pydantic serializer warnings:
  Expected `str` but got `dict` - serialized value may not be as expected
  ret = handler(value)
/mnt/e/linux/conda/envs/metagpt_new/lib/python3.9/site-packages/pydantic/functional_serializers.py:272: UserWarning: Pydantic serializer warnings:
  Expected `str` but got `dict` - serialized value may not be as expected
  lambda x, h: h(x), schema=core_schema.any_schema()

![image](https://github.com/geekan/MetaGPT/assets/19252849/fc07f5f9-1b92-4ef0-b027-a48c8ae6ea63)

I confirmd that before run metagpt the dir is empty, then two dirs blackjack_cli and storage to appear on the workspace

**Comment by iorisa** [comment]
From the logs, it appears that after renaming the folder, the code had attempted to access the folder twice but still failed. 
However, upon later inspection using `ll` command, the folder renaming was successful. 
I speculate that the operating system, upon receiving the folder renaming operation, immediately returned success without waiting for the operation to be completed, causing this issue. 

```text
2024-01-09 00:18:26.946 | INFO | metagpt.utils.file_repository:save:60 - save to: /mnt/e/ml/1/workspace/20240109001826/docs/requirement.txt

2024-01-09 00:18:49.777 | INFO | metagpt.utils.git_repository:rename_root:206 - Rename directory /mnt/e/ml/1/workspace/20240109001826 to /mnt/e/ml/1/workspace/blackjack_cli

2024-01-09 00:18:49.828 | ERROR | metagpt.utils.common:wrapper:491 - ......
git.exc.NoSuchPathError: /mnt/e/ml/1/workspace/blackjack_cli

During handling of the above exception, another exception occurred:

......
git.exc.NoSuchPathError: /mnt/e/ml/1/workspace/blackjack_cli

```

You can manually specify the folder name by using the `--project-name` command parameter to bypass the renaming of the project folder at this point.

For example:
```shell
metagpt "write a cli blackjack game" --project-name "blackjack_cli"
```

**Comment by SuperbDong** [comment]
> From the logs, it appears that after renaming the folder, the code had attempted to access the folder twice but still failed. However, upon later inspection using `ll` command, the folder renaming was successful. I speculate that the operating system, upon receiving the folder renaming operation, immediately returned success without waiting for the operation to be completed, causing this issue.
> 
> ```
> 2024-01-09 00:18:26.946 | INFO | metagpt.utils.file_repository:save:60 - save to: /mnt/e/ml/1/workspace/20240109001826/docs/requirement.txt
> 
> 2024-01-09 00:18:49.777 | INFO | metagpt.utils.git_repository:rename_root:206 - Rename directory /mnt/e/ml/1/workspace/20240109001826 to /mnt/e/ml/1/workspace/blackjack_cli
> 
> 2024-01-09 00:18:49.828 | ERROR | metagpt.utils.common:wrapper:491 - ......
> git.exc.NoSuchPathError: /mnt/e/ml/1/workspace/blackjack_cli
> 
> During handling of the above exception, another exception occurred:
> 
> ......
> git.exc.NoSuchPathError: /mnt/e/ml/1/workspace/blackjack_cli
> ```
> 
> You can manually specify the folder name by using the `--project-name` command parameter to bypass the renaming of the project folder at this point.
> 
> For example:
> 
> ```shell
> metagpt "write a cli blackjack game" --project-name "blackjack_cli"
> ```

Thanks a lot, I will try again tonight.

**Comment by SuperbDong** [comment]
> > Whether I can follow link doc(fastchat doc) content,just can use openai or guide have show models
> 
> @SuperbDong what does this means? Maybe you can use openai models to run the project firstly, and then try the open llms since open llms can't have the same instruction following ability as openai models.

When I replace the model to gpt-3.5-tubor-16k,It dose work. I try to use the local llm model to run it again.3ks

**Comment by better629** [comment]
> > > Whether I can follow link doc(fastchat doc) content,just can use openai or guide have show models
> > 
> > 
> > @SuperbDong what does this means? Maybe you can use openai models to run the project firstly, and then try the open llms since open llms can't have the same instruction following ability as openai models.
> 
> When I replace the model to gpt-3.5-tubor-16k,It dose work. I try to use the local llm model to run it again.3ks

@SuperbDong 
OK. open and small size llms allways have poor instruction following ability to generate required structure. 
Currently, we have tried llama2-7b/13b and so on, it will works but not allways. Maybe you can try more times.

**Comment by SuperbDong** [comment]
> > From the logs, it appears that after renaming the folder, the code had attempted to access the folder twice but still failed. However, upon later inspection using `ll` command, the folder renaming was successful. I speculate that the operating system, upon receiving the folder renaming operation, immediately returned success without waiting for the operation to be completed, causing this issue.
> > ```
> > 2024-01-09 00:18:26.946 | INFO | metagpt.utils.file_repository:save:60 - save to: /mnt/e/ml/1/workspace/20240109001826/docs/requirement.txt
> > 
> > 2024-01-09 00:18:49.777 | INFO | metagpt.utils.git_repository:rename_root:206 - Rename directory /mnt/e/ml/1/workspace/20240109001826 to /mnt/e/ml/1/workspace/blackjack_cli
> > 
> > 2024-01-09 00:18:49.828 | ERROR | metagpt.utils.common:wrapper:491 - ......
> > git.exc.NoSuchPathError: /mnt/e/ml/1/workspace/blackjack_cli
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > ......
> > git.exc.NoSuchPathError: /mnt/e/ml/1/workspace/blackjack_cli
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can manually specify the folder name by using the `--project-name` command parameter to bypass the renaming of the project folder at this point.
> > For example:
> > ```shell
> > metagpt "write a cli blackjack game" --project-name "blackjack_cli"
> > ```
> 
> Thanks a lot, I will try again tonight.

It works for me.3ks. And I find the project doesn't instability, It should try more times
