### ISSUE TITLE
调用本地模型测试报错

### ISSUE THREAD

**Issue by flychatin** [geekan/MetaGPT#730]
key.yaml配置：
OLLAMA_API_BASE: http://127.0.0.1:11434/api
OLLAMA_API_MODEL: mixtral:latest

运行示例：metagpt --code-review "Create a 2048 game in python"

报错信息：
2024-01-09 16:53:20.793 | ERROR    | metagpt.utils.common:log_it:438 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 267.975(s), this was the 6th time calling it. exp: RetryError[<Future at 0x10ea95bd0 state=finished raised JSONDecodeError>]
2024-01-09 16:53:20.793 | WARNING  | metagpt.utils.common:wrapper:510 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-01-09 16:53:20.797 | ERROR    | metagpt.utils.common:wrapper:492 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/utils/repair_llm_raw_output.py", line 263, in retry_parse_json_text
    parsed_data = CustomDecoder(strict=False).decode(output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/actions/action_node.py", line 273, in _aask_v1
    parsed_data = llm_output_postprocess(
                  ^^^^^^^^^^^^^^^^^^^^^^^
tenacity.RetryError: RetryError[<Future at 0x10ea95bd0 state=finished raised JSONDecodeError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxxxxx/git/metagpt/metagpt/utils/common.py", line 501, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/roles/role.py", line 485, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
tenacity.RetryError: RetryError[<Future at 0x14d23b9d0 state=finished raised RetryError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxxxx/git/metagpt/metagpt/utils/common.py", line 487, in wrapper
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/team.py", line 133, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/utils/repair_llm_raw_output.py", line 263, in retry_parse_json_text
    parsed_data = CustomDecoder(strict=False).decode(output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/utils/custom_decoder.py", line 297, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/actions/action_node.py", line 273, in _aask_v1
    parsed_data = llm_output_postprocess(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/provider/postprocess/llm_output_postprocess.py", line 19, in llm_output_postprocess
    result = postprocess_plugin.run(output=output, schema=schema, req_key=req_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/provider/postprocess/base_postprocess_plugin.py", line 68, in run
    new_output = self.run_repair_llm_output(output=output, schema=schema, req_key=req_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/provider/postprocess/base_postprocess_plugin.py", line 32, in run_repair_llm_output
    parsed_data = self.run_retry_parse_json_text(content)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/provider/postprocess/base_postprocess_plugin.py", line 47, in run_retry_parse_json_text
    parsed_data = retry_parse_json_text(output=content)  # should use output=content
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x10ea95bd0 state=finished raised JSONDecodeError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxxxxx/git/metagpt/metagpt/utils/common.py", line 501, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/roles/role.py", line 485, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/roles/role.py", line 453, in react
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/roles/role.py", line 432, in _react
    rsp = await self._act()  # 这个rsp是否需要publish_message？
          ^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/roles/role.py", line 361, in _act
    response = await self.rc.todo.run(self.rc.history)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/actions/design_api.py", line 61, in run
    doc = await self._update_system_design(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/actions/design_api.py", line 93, in _update_system_design
    system_design = await self._new_system_design(context=prd.content)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/actions/design_api.py", line 80, in _new_system_design
    node = await DESIGN_API_NODE.fill(context=context, llm=self.llm, schema=schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/actions/action_node.py", line 338, in fill
    return await self.simple_fill(schema=schema, mode=mode, timeout=timeout, exclude=exclude)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/git/metagpt/metagpt/actions/action_node.py", line 303, in simple_fill
    content, scontent = await self._aask_v1(prompt, class_name, mapping, schema=schema, timeout=timeout)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x14d23b9d0 state=finished raised RetryError>]

/opt/homebrew/lib/python3.11/site-packages/pydantic/functional_serializers.py:272: UserWarning: Pydantic serializer warnings:
  Expected `str` but got `dict` - serialized value may not be as expected
  lambda x, h: h(x), schema=core_schema.any_schema()
/Users/xxxxxx/git/metagpt/metagpt/schema.py:93: UserWarning: Pydantic serializer warnings:
  Expected `str` but got `dict` - serialized value may not be as expected
  ret = handler(value)

**Comment by flychatin** [comment]
已解决，在 key.yaml 开启以下配置正常执行完毕
REPAIR_LLM_OUTPUT: true
