### ISSUE TITLE
Windows下的docker安装的 出现这个错误解决不了了

### ISSUE THREAD

**Issue by chxgzs** [geekan/MetaGPT#757]
root@276984af64c8:/app/metagpt# metagpt "Write a cli snake game"
2024-01-15 06:19:02.162 | INFO     | metagpt.const:get_metagpt_package_root:32 - Package root set to /app/metagpt
2024-01-15 06:19:02.372 | INFO     | metagpt.config:get_default_llm_provider_enum:124 - LLMProviderEnum.OPENAI Model: gpt-4-1106-preview
2024-01-15 06:19:02.373 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPENAI
2024-01-15 06:19:04.494 | INFO     | metagpt.config:get_default_llm_provider_enum:124 - LLMProviderEnum.OPENAI Model: gpt-4-1106-preview
2024-01-15 06:19:04.494 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPENAI
2024-01-15 06:19:04.545 | INFO     | metagpt.config:get_default_llm_provider_enum:124 - LLMProviderEnum.OPENAI Model: gpt-4-1106-preview
2024-01-15 06:19:04.545 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPENAI
2024-01-15 06:19:04.588 | INFO     | metagpt.config:get_default_llm_provider_enum:124 - LLMProviderEnum.OPENAI Model: gpt-4-1106-preview
2024-01-15 06:19:04.588 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPENAI
2024-01-15 06:19:04.636 | INFO     | metagpt.config:get_default_llm_provider_enum:124 - LLMProviderEnum.OPENAI Model: gpt-4-1106-preview
2024-01-15 06:19:04.636 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.OPENAI
2024-01-15 06:19:04.672 | INFO     | metagpt.team:invest:86 - Investment: $3.0.
2024-01-15 06:19:04.675 | INFO     | metagpt.roles.role:_act:357 - Alice(Product Manager): to do PrepareDocuments(PrepareDocuments)
2024-01-15 06:19:05.282 | INFO     | metagpt.utils.file_repository:save:60 - save to: /app/metagpt/workspace/20240115061904/docs/requirement.txt
2024-01-15 06:19:05.285 | INFO     | metagpt.roles.role:_act:357 - Alice(Product Manager): to do WritePRD(WritePRD)
[CONTENT]
{
    "Language": "en_us",
    "Programming Language": "Python",
    "Original Requirements": "Write a cli snake game",
    "Project Name": "cli_snake_game",
    "Product Goals": [
        "Create a fun and engaging command line interface snake game",
        "Ensure game performance and responsiveness",
        "Provide user-friendly instructions and game rules"
    ],
    "User Stories": [
        "As a player, I want to be able to control the snake using keyboard arrows",
        "As a player, I want to see my score after each game",
        "As a player, I want to be able to restart the game when I lose",
        "As a player, I want to see the game boundaries clearly",
        "As a player, I want to have a pause/resume option"
    ],
    "Competitive Analysis": [
        "Snake Game A: Simple interface, lacks responsiveness",
        "Snake Game B: Good performance but lacks clear instructions",
        "Snake Game C: Responsive and clear instructions, but lacks pause/resume option"
    ],
    "Competitive Quadrant Chart": "quadrantChart\n    title \"Performance and User Experience of Snake Games\"\n    x-axis \"Low Performance\" --> \"High Performance\"\n    y-axis \"Poor User Experience\" --> \"Great User Experience\"\n    quadrant-1 \"We should expand\"\n    quadrant-2 \"Need to promote\"\n    quadrant-3 \"Re-evaluate\"\n    quadrant-4 \"May be improved\"\n    \"Snake Game A\": [0.3, 0.6]\n    \"Snake Game B\": [0.45, 0.23]\n    \"Snake Game C\": [0.57, 0.69]\n    \"Our Target Product\": [0.7, 0.8]",
    "Requirement Analysis": "The main requirement is to create a command line interface snake game. The game should be responsive and provide a fun and engaging user experience. The player should be able to control the snake using keyboard arrows, see their score after each game, restart the game when they lose, see the game boundaries clearly, and have a pause/resume option.",
    "Requirement Pool": [
        [
            "P0",
            "The main code should be written in Python and should create a command line interface snake game."
        ],
        [
            "P0",
            "The game should be responsive and the snake should be controllable using keyboard arrows."
        ],
        [
            "P1",
            "The player's score should be displayed after each game."
        ],
        [
            "P1",
            "There should be an option to restart the game when the player loses."
        ],
        [
            "P2",
            "The game boundaries should be clearly visible."
        ]
    ],
    "UI Design draft": "The user interface will be a simple command line interface. The game boundaries will be clearly marked, and the snake will be represented by a line of characters. The player's score will be displayed at the top of the screen.",
    "Anything UNCLEAR": ""
}
2024-01-15 06:19:38.075 | INFO     | metagpt.utils.cost_manager:update_cost:48 - Total running cost: $0.029 | Max budget: $10.000 | Current cost: $0.029, prompt_tokens: 948, completion_tokens: 655
2024-01-15 06:19:38.084 | WARNING  | metagpt.utils.git_repository:rename_root:211 - Failed to move /app/metagpt/workspace/20240115061904 to /app/metagpt/workspace/cli_snake_game
2024-01-15 06:19:38.099 | INFO     | metagpt.utils.file_repository:save:60 - save to: /app/metagpt/workspace/20240115061904/docs/prds/20240115061938.json
2024-01-15 06:19:38.121 | INFO     | metagpt.utils.mermaid:mermaid_to_file:50 - Generating /app/metagpt/workspace/20240115061904/resources/competitive_analysis/20240115061938.pdf..
2024-01-15 06:19:39.536 | INFO     | metagpt.utils.mermaid:mermaid_to_file:74 - Generating single mermaid chart

2024-01-15 06:19:39.536 | INFO     | metagpt.utils.mermaid:mermaid_to_file:50 - Generating /app/metagpt/workspace/20240115061904/resources/competitive_analysis/20240115061938.svg..
2024-01-15 06:19:40.824 | INFO     | metagpt.utils.mermaid:mermaid_to_file:74 - Generating single mermaid chart

2024-01-15 06:19:40.825 | INFO     | metagpt.utils.mermaid:mermaid_to_file:50 - Generating /app/metagpt/workspace/20240115061904/resources/competitive_analysis/20240115061938.png..
2024-01-15 06:19:42.162 | INFO     | metagpt.utils.mermaid:mermaid_to_file:74 - Generating single mermaid chart

2024-01-15 06:19:42.182 | INFO     | metagpt.utils.file_repository:save:60 - save to: /app/metagpt/workspace/20240115061904/resources/prd/20240115061938.md
2024-01-15 06:19:42.186 | INFO     | metagpt.roles.role:_act:357 - Bob(Architect): to do WriteDesign(WriteDesign)
2024-01-15 06:19:42.268 | INFO     | metagpt.actions.design_api:run:74 - Nothing has changed.
2024-01-15 06:19:42.272 | INFO     | metagpt.roles.role:_act:357 - Eve(Project Manager): to do WriteTasks(WriteTasks)
2024-01-15 06:19:42.348 | INFO     | metagpt.actions.project_management:run:68 - Nothing has changed.
/usr/local/lib/python3.9/site-packages/pydantic/main.py:352: UserWarning: Pydantic serializer warnings:
  Expected `str` but got `dict` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_json(
2024-01-15 06:19:42.463 | INFO     | metagpt.utils.git_repository:archive:165 - Archive: []
2024-01-15 06:19:42.497 | ERROR    | metagpt.utils.common:wrapper:488 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "/app/metagpt/metagpt/utils/common.py", line 483, in wrapper
    result = await func(self, *args, **kwargs)
  File "/app/metagpt/metagpt/team.py", line 134, in run
    self.env.archive(auto_archive)
FileNotFoundError: [Errno 2] No such file or directory: '/app/metagpt/workspace/20240115061904/.git/COMMIT_EDITMSG'

/usr/local/lib/python3.9/site-packages/pydantic/functional_serializers.py:272: UserWarning: Pydantic serializer warnings:
  Expected `str` but got `dict` - serialized value may not be as expected
  lambda x, h: h(x), schema=core_schema.any_schema()

**Comment by voidking** [comment]
使用的什么镜像版本？容器启动命令是什么？

**Comment by chxgzs** [comment]
> 使用的什么镜像版本？容器启动命令是什么？

cmd

```
docker run --name metagpt -d ^
    --privileged ^
    -v D:\docker_all\metagpt\config\key.yaml:/app/metagpt/config/key.yaml ^
    -v D:\docker_all\metagpt\workspace:/app/metagpt/workspace ^
    metagpt/metagpt:latest
```

1. 接下来，进入容器的Shell：

```
docker exec -it metagpt /bin/bash
```



1. 在容器内，您可以执行命令，例如写一个命令行界面的贪吃蛇游戏：

```
metagpt "Write a cli snake game"
```

<img width="598" alt="69f74fc607b4fcce9d005e84178cda4" src="https://github.com/geekan/MetaGPT/assets/47893401/fac1b958-f65a-4e25-812e-a1e8e7dd85fe">

**Comment by voidking** [comment]
最新版的镜像在linux中是可以正常使用的。
试一下不挂载宿主机workspace目录吧？就是把第二个 -v 挂载去掉，直接产出在容器内。

**Comment by chxgzs** [comment]
确实就是这个问题.谢谢你.!

**Comment by zencorn** [comment]
> 确实就是这个问题.谢谢你.!

请问一下，我也是在Windows上进入docker的Shell后，执行下一步时遇到这种错误，有什么解决办法吗？
C:\Users\weiji\OneDrive\Working\Jian_AIGC>docker exec -it metagpt /bin/bash
root@a06d8c03d33c:/app/metagpt# ls
Dockerfile  README.md  config  docs      metagpt           requirements-ocr.txt  ruff.toml  startup.py  workspace
LICENSE     build      dist    examples  metagpt.egg-info  requirements.txt      setup.py   tests
root@a06d8c03d33c:/app/metagpt# metagpt "Write a cli snake game"
**bash: metagpt: command not found**
