### ISSUE TITLE
ActionNode 是否可以支持列表式的children？

### ISSUE THREAD

**Issue by wujiren** [geekan/MetaGPT#763]
**Feature description**

**Your Feature**

我的代码如下：
```python
from typing import Dict, List
from metagpt.actions.action_node import ActionNode
NAME = ActionNode(
    key="name",
    expected_type=str,
    instruction="""name of the objective""",
    example="color"
)

VARIABLE_TYPE = ActionNode(
    key="type",
    expected_type=str,
    instruction="""type of the varialbe. can be String, Int, Float etc, or a self defined type""",
    example="AgentPopulation")
DESC = ActionNode(
    key="desc",
    expected_type=str,
    instruction="""description""",
    example="im a description"
)
Variable_Type = ActionNode.from_children(
    "variable", [NAME, VARIABLE_TYPE, DESC])
VARIABLE_LIST = ActionNode(
    key="variables",
    expected_type=List[Variable_Type],
    instruction="""list of variables""",
    # example=[{
    #     "name": "current_patch",
    #     "type": "Discrete2DPatch",
    #     "desc": "当前网格"
    # }]
    example=[]
)
Input_Type = ActionNode.from_children("input", [NAME, VARIABLE_TYPE, DESC])
INPUTS = ActionNode(
    key="inputs",
    expected_type=List[Input_Type],
    instruction="""list of inputs""",
    example=[]
)
```
我想创建一个INPUTS类型，用来生成一系列变量。由于需要的变量数量不能提前确定，我需要将他们放到一个list中，但是目前好像不支持      expected_type=List[Variable_Type] 这种方式。
报错的信息：
```
Traceback (most recent call last):
  File "/home/jovyan/LLM_agent/MetaGen/action_node.py", line 29, in <module>
    expected_type=List[Variable_Type],
  File "/home/jovyan/.conda/envs/metagpt/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/home/jovyan/.conda/envs/metagpt/lib/python3.10/typing.py", line 1143, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/home/jovyan/.conda/envs/metagpt/lib/python3.10/typing.py", line 1143, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/home/jovyan/.conda/envs/metagpt/lib/python3.10/typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got variable, <class 'str'>, , , , {'name': name, <class 'str'>, name of the objective, color, , {}, 'ty.
```
请问是否有其他方式能够实现让他动态的生成一组不定数量的Variable_Type类型的数据？

**Comment by geekan** [comment]
It's still in the design stage, and further design is needed to complete and stabilize the output, so if you're interested, you can participate in this part together
