### ISSUE TITLE
求助，第一次用。JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by ChenVadder** [geekan/MetaGPT#81]
Traceback (most recent call last):
  File "D:\Documents\Python\MetaGPT-main\lib\site-packages\openai\api_requestor.py", line 753, in _interpret_response_line
    data = json.loads(rbody)
  File "C:\Users\CV\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\CV\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\CV\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

感谢项目组！

**Comment by ChenVadder** [comment]
OPENAI_API_KEY和OPENAI_API_BASE的可用性已在其他项目中得到验证。

**Comment by upbit** [comment]
把 rbody 打出来看看，`line 1 column 1 (char 0)`可能是返回了控内容（比如代理有问题之类的）

**Comment by geekan** [comment]
一般是网络问题。查看一下log.txt，如果缺乏必要的日志信息，加上对应的返回日志

**Comment by ChenVadder** [comment]
当我使用VSCode/CMD（而不是PyCharm）重新部署时，发现setup.py中的某些步骤会报错或提示需要更新（PyCharm中则不会），怀疑是本地的环境问题而不是网络问题。在部署成功后还未尝试重新用PyCharm部署，所以并不能完全定位问题，但可以肯定的是并不是因为网络的问题，因为全程并没有更改网络配置或代理配置。后续如果还遇到类似的问题的话，我再进行解决并分享解决过程。
感谢！

**Comment by WilkinsLiu** [comment]
我也遇到相同的问题，使用的是LLAMA3，难道是模型的能力不足导致的？没使用过OPENAI API，前面几轮都是正常的，但是总是在出结果之前出现这个问题
