### ISSUE TITLE
TypeError: __init__() takes 1 positional argument but 5 were given

### ISSUE THREAD

**Issue by Jonathan-Wei** [geekan/MetaGPT#821]
目前在做taks4到内容，代码是通过官方教程提供的，运行过程提示TypeError: __init__() takes 1 positional argument but 5 were given，具体日志如下：

(metagpt-spark) (base)  ✘ weijiyonglover@MacBook-Pro-2  ~/aigc/metagpt/MetaGPT/metagpt  ↰ main ±     /opt/anaconda3/envs/metagpt-spark/bin/python /Users/weijiyonglover/aigc/metagpt/MetaGPT/metagpt/main.py
2024-02-01 20:18:49.624 | INFO     | metagpt.const:get_metagpt_package_root:32 - Package root set to /Users/weijiyonglover/aigc/metagpt/MetaGPT
2024-02-01 20:18:49.825 | INFO     | metagpt.config:get_default_llm_provider_enum:126 - API: LLMProviderEnum.SPARK
Traceback (most recent call last):
  File "/Users/weijiyonglover/aigc/metagpt/MetaGPT/metagpt/main.py", line 351, in <module>
    fire.Fire(main)
  File "/opt/anaconda3/envs/metagpt-spark/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/anaconda3/envs/metagpt-spark/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/anaconda3/envs/metagpt-spark/lib/python3.9/site-packages/fire/core.py", line 679, in _CallAndUpdateTrace
    component = loop.run_until_complete(fn(*varargs, **kwargs))
  File "/opt/anaconda3/envs/metagpt-spark/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/weijiyonglover/aigc/metagpt/MetaGPT/metagpt/main.py", line 344, in main
    await runner.subscribe(OssWatcher(), GithubTrendingCronTrigger(spec), callback)
  File "/Users/weijiyonglover/aigc/metagpt/MetaGPT/metagpt/main.py", line 216, in __init__
    super().__init__(name, profile, goal, constraints)
TypeError: __init__() takes 1 positional argument but 5 were given

**Comment by Jonathan-Wei** [comment]
报错位置代码：
<img width="748" alt="image" src="https://github.com/geekan/MetaGPT/assets/3073018/5463f526-722a-44e8-8451-bb9449cd95fd">

<img width="894" alt="image" src="https://github.com/geekan/MetaGPT/assets/3073018/15dfb2a2-e526-45b6-9e97-35b87bb97ecb">

**Comment by better629** [comment]
`super.__init__(name=name, profile=profile,...)`

**Comment by shenchucheng** [comment]
是不是用了最新代码，教程是基于0.5.2版本，新版metagpt需要相应修改一下
