### ISSUE TITLE
Generate garbled code starting with u, incorrect JSON format, duplicate request

### ISSUE THREAD

**Issue by lowpair** [geekan/MetaGPT#898]
**Bug description**

**Bug solved method**

**Environment information**

cenos7  python 3.9.10
mac       python 3.11.6

- LLM type and model name:
- System version:
- Python version:

pip install metaGPT
no docker

- packages version:
- installation method: 

**Screenshots or logs**

mac log:

2024-02-15 16:09:37.230 | INFO     | metagpt.utils.cost_manager:update_cost:52 - Total running cost: $0.000 | Max budget: $10.000 | Current cost: $0.000, prompt_tokens: 0, completion_tokens: 0
2024-02-15 16:09:37.233 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:308 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-02-15 16:09:37.235 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:256 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Invalid \uXXXX escape: line 23 column 15 (char 1656)
2024-02-15 16:09:37.235 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:225 - repair_invalid_json, raw error: Invalid \uXXXX escape: line 23 column 15 (char 1656)
2024-02-15 16:09:37.236 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 136.099(s), this was the 4th time calling it. exp: RetryError[<Future at 0x13237b810 state=finished raised JSONDecodeError>]
[CONTENT]
{
    "name": "\u9f99\u51e4\u6cb3\u7684\u5c0f\u767d\u6761",
    "user_group": "\u5e7c\u7a1a\u5b69\u5b50\u548c\u5bb6\u9576",
    "outlines": [
        "\u7ae0\u8282 1: \u767d\u6761\u6c34\u4e1a\u7684\u5947\u9646\u5f00\u59cb",
        "\u7ae0\u8282 2: \u9f99\u51e4\u6cb3\u4e0a\u7684\u5c0f\u670b\u53cb",
        "\u7ae0\u8282 3: \u6df1\u6e0a\u7684\u9690\u79c1\u4e0e\u5e7b\u60f3",
        "\u7ae0\u8282 4: \u5f20\u5f20\u7684\u51fa\u73b0",
        "\u7ae0\u8282 5: \u6c90\u6c90\u548c\u6沐沐\u7684\u5403\u60ca",
        "\u7ae0\u8282 6: \u5c0f\u53f6\u7684\u5bb6\u4e61\u4e8b",
        "\u7ae0\u8282 7: \u767d\u6761\u7684\u52a8\u4f5c",
        "\u7ae0\u8282 8: \u5e7b\u60f3\u4e16\u754c\u7684\u5f00\u653e",
        "\u7ae0\u8282 9: \u4e00\u6b21\u5b8c\u7f8e\u7684\u540e\u5907",
        "\u7ae0\u8282 10: \u4e00\u5207\u5f52\u4e8e\u5e73\u9759"
    ],
    "background": "\u9f99\u51e4\u6cb3\u8fd9\u4e2a\u5e7f\u897f\u7684\u6cb3\u6d41\u548c\u5176\u8fb9\u7f18\u7684\u7eff\u8272\u533a\u57df\u5177\u6709\u7740\u4e0d\u540c\u7684\u79d8\u5bc6\u548c\u5e7b\u60f3\u3002\u5c0f\u767d\u6761\u662f\u6cb3\u91cc\u7684\u4e00\u6761\u5e73\u51e1\u800c\u53c8\u5145\u6ee1\u60c5\u611f\u7684\u5c0f\u9c7c\u3002",
    "character_names": [
        "\u94b0\u94b0",
        "\u6c90\u6c90",
        "\u5c0f\u53f6",
        "\u767d\u6761"
    ],
    "conflict": "\u94b0\u94b0\u548c\u6c90\u6c90\u5728\u6c34\u4e2d\u6d3b\u52a8\u65f6\u9047\u5230\u4e86\u767d\u6761\u3002\u4ed6\u4eec\u60f3\u4fdd\u62a4\u8be5\u5c0f\u9c7c\u4e0d\u88ab\u522b\u4eba\u635f\u8017\u3002",
    "plot": "\u94b0\u94b0\u548c\u6c90\u6c90\u9047\u5230\u4e86\u9f99\u51e4\u6cb3\u7684\u5c0f\u767d\u6761\u3002\u5c0f\u767d\u6761\u5177\u6709\u4e00\u79cd\u795e\u79d8\u
2024-02-15 16:10:10.527 | INFO     | metagpt.utils.cost_manager:update_cost:52 - Total running cost: $0.000 | Max budget: $10.000 | Current cost: $0.000, prompt_tokens: 0, completion_tokens: 0
2024-02-15 16:10:10.531 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:308 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-02-15 16:10:10.534 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:256 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Invalid \uXXXX escape: line 9 column 45 (char 478)
2024-02-15 16:10:10.535 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:225 - repair_invalid_json, raw error: Invalid \uXXXX escape: line 9 column 45 (char 478)
2024-02-15 16:10:10.536 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 169.399(s), this was the 5th time calling it. exp: RetryError[<Future at 0x1325d4c50 state=finished raised JSONDecodeError>]
[CONTENT]
{
    "name": "\u9f99\u51e4\u6cb3\u7684\u5c0f\u767d\u6761",
    "user_group": "\u5e7c\u7a1a\u5b66\u751f\u548c\u540c\u884c\u7231\u597d\u5f71\u54cd\u7c7b\u5c0f\u8bf4\u7684\u8bfb\u8005",
    "outlines": [
        "\u7ae0\u8282 1: \u767d\u6761\u6cb3\u4e2d\u7684\u6df1\u5904\u4f1a\u8bdd",
        "\u7ae0\u8282 2: \u9f99\u94b0\u548c\u6c90\u6c90\u7684\u666f\u8272",
        "\u7ae0\u8282 3: \u5c0f\u53f6\u7684\u5bc2\u5bde",
        "\u7ae0\u8282 4: \u6df1\u6e0a\u7684\u5bc6\u5f7b",
        "\u7ae0\u8282 5: \u767d\u6761\u7684\u5175\u4e8b",
        "\u7ae0\u8282 6: \u4e24\u4e2a\u5c0f\u670b\u53cb\u7684\u52a8\u4f5c",
        "\u7ae0\u8282 7: \u6c34\u4e0e\u667a\u6167\u7684\u5408\u4f5c",
        "\u7ae0\u8282 8: \u5f52\u6765\u7684\u5f71\u54cd",
        "\u7ae0\u8282 9: \u5f3a\u5927\u7684\u5bff\u53d1",
        "\u7ae0\u8282 10: \u4e00\u5207\u5f52\u8f66\u540e\u7684\u5e73\u9759"
    ],
    "background": "\u9f99\u51e4\u6cb3\u662f\u4e00\u6761\u5e7d\u9e23\u800c\u53d1\u5149\u7684\u6cb3\u6d41\uff0c\u5176\u8fb9\u8ddd\u4e00\u5e26\u5c0f\u679d\u6728\u6811\u548c\u4e00\u5806\u5404\u5f0f\u7684\u5c0f\u751f\u547d\u3002\u5c0f\u767d\u6761\u662f\u6cb3\u4e2d\u4e00\u79cd\u5f88\u5c11\u89c1\u5230\u7684\u5c0f\u9c7c\u7c7b\u578b\uff0c\u5177\u6709\u4e0d\u540c\u7684\u8272\u5f69\u548c\u7279\u5f81\u3002",
    "character_names": [
        "\u767d\u6761",
        "\u94b0\u94b0",
        "\u6c90\u6c90",
        "\u5c0f\u53f6"
    ],
    "conflict": "\u767d\u6761\u9700\u8981\u89e3\u51b3\u6cb3\u533a\u7684\u75d5\u75c5\u95ee\u9898\uff0c\u800c\u94b0\u94b0\u548c\u6c90\u6c90\u521d\u672a\u8bc6\u8bba\u5230\u767d\u6761\u7684\u4fdd\u62a4\u4f5c\u7528\u3002",
    "plot": "\u767d\u6761\u662f\u9f99\u51e4\u6cb3\u4e
2024-02-15 16:10:52.683 | INFO     | metagpt.utils.cost_manager:update_cost:52 - Total running cost: $0.000 | Max budget: $10.000 | Current cost: $0.000, prompt_tokens: 0, completion_tokens: 0
2024-02-15 16:10:52.689 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:308 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-02-15 16:10:52.691 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:256 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Invalid \uXXXX escape: line 24 column 51 (char 1674)
2024-02-15 16:10:52.691 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:225 - repair_invalid_json, raw error: Invalid \uXXXX escape: line 24 column 51 (char 1674)
2024-02-15 16:10:52.692 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 211.555(s), this was the 6th time calling it. exp: RetryError[<Future at 0x1324cb250 state=finished raised JSONDecodeError>]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/utils/repair_llm_raw_output.py", line 284, in retry_parse_json_text
    parsed_data = CustomDecoder(strict=False).decode(output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/utils/custom_decoder.py", line 297, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/utils/custom_decoder.py", line 65, in scan_once
    return _scan_once(string, idx)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/utils/custom_decoder.py", line 36, in _scan_once
    return parse_object((string, idx + 1), strict, _scan_once, object_hook, object_pairs_hook, memo)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/utils/custom_decoder.py", line 164, in JSONObject
    value, end = scan_once(s, end)
                 ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/utils/custom_decoder.py", line 34, in _scan_once
    return parse_string(string, idx + 1, strict, delimiter=nextchar)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/utils/custom_decoder.py", line 258, in py_scanstring
    uni = _decode_uXXXX(s, end)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 67, in _decode_uXXXX
    raise JSONDecodeError(msg, s, pos)
json.decoder.JSONDecodeError: Invalid \uXXXX escape: line 24 column 51 (char 1674)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/actions/action_node.py", line 427, in _aask_v1
    parsed_data = llm_output_postprocess(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/provider/postprocess/llm_output_postprocess.py", line 19, in llm_output_postprocess
    result = postprocess_plugin.run(output=output, schema=schema, req_key=req_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/provider/postprocess/base_postprocess_plugin.py", line 68, in run
    new_output = self.run_repair_llm_output(output=output, schema=schema, req_key=req_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/provider/postprocess/base_postprocess_plugin.py", line 32, in run_repair_llm_output
    parsed_data = self.run_retry_parse_json_text(content)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/provider/postprocess/base_postprocess_plugin.py", line 47, in run_retry_parse_json_text
    parsed_data = retry_parse_json_text(output=content)  # should use output=content
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1324cb250 state=finished raised JSONDecodeError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/unm/Desktop/Novel/write_novel_cat.py", line 78, in <module>
    asyncio.run(generate_novel())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/unm/Desktop/Novel/write_novel_cat.py", line 59, in generate_novel
    novel_node = await ActionNode.from_pydantic(Novel).fill(context=instruction, llm=LLM())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/actions/action_node.py", line 505, in fill
    return await self.simple_fill(schema=schema, mode=mode, images=images, timeout=timeout, exclude=exclude)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/metagpt/actions/action_node.py", line 457, in simple_fill
    content, scontent = await self._aask_v1(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1324ca790 state=finished raised RetryError>]
unm@UNMdeMacBook-Air Novel %

**Comment by better629** [comment]
what's your run input? It seems that the fields of `user_group` and `background` are not from the output of Software Generation.

**Comment by better629** [comment]
I see, you run the `examples/write_novel.py`. What is the LLM.

**Comment by lowpair** [comment]
> I see, you run the `examples/write_novel.py`. What is the LLM model ?

zhipuai

**Comment by lowpair** [comment]
> @lowpair here is the output from zhipu using `write_novel.py`. Do you have make changes of the code or else?
> 
> ```
> (metagpt) MacBook-Pro:MetaGPT xxxx$ python3 examples/write_novel.py 
> 2024-02-23 18:34:27.722 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to /Users/xxxx/work/demo-code/MetaGPT
> [CONTENT]
> {
>     "name": "Harry Potter in The Lord of the Rings",
>     "user_group": "Fantasy readers, Harry Potter and LOTR fans",
>     "outlines": [
>         "Chapter 1: The Boy Who Lived Meets the Ring",
>         "Chapter 2: Magic and Middle-earth",
>         "Chapter 3: The Fellowship of Wizards",
>         "Chapter 4: The Two Towers of Hogwarts",
>         "Chapter 5: The Return of the Dark Lord",
>         "Chapter 6: The Battle of Hogwarts and Beyond",
>         "Chapter 7: The Power of Friendship",
>         "Chapter 8: The Paths of the Dead and the Living",
>         "Chapter 9: The End of All Things",
>         "Chapter 10: The Age of Peace"
>     ],
>     "background": "In a world where the magic of Harry Potter and the epicness of The Lord of the Rings intertwine, a new threat emerges that requires the combined efforts of two worlds' heroes.",
>     "character_names": [
>         "Harry Potter",
>         "Frodo Baggins",
>         "Gandalf",
>         "Voldemort",
>         "Sauron",
>         "Hermione Granger",
>         "Ron Weasley",
>         "Aragorn",
>         "Legolas",
>         "Gimli",
>         "Professor Dumbledore",
>         "Severus Snape"
>     ],
>     "conflict": "Harry Potter discovers the One Ring, which is being sought by both Voldemort and Sauron, each for their own malevolent purposes. Harry and Frodo must unite to protect the Ring and prevent the rise of darkness in both their worlds.",
>     "plot": "Harry Potter, on the run from Voldemort, stumbles upon the Shire and befriends Frodo Baggins. Together, they embark on a journey to destroy the One Ring. Along the way, they encounter familiar faces from both Harry's world and Middle-earth, forming an unforgettable fellowship. As the forces of darkness gather, Harry and Frodo must navigate through treacherous lands, face their fears, and ultimately confront the ultimate evil.",
>     "ending": "In a climactic battle that spans across both Hogwarts and Middle-earth, the heroes triumph over Voldemort and Sauron, destroying the Ring and vanquishing the dark lords. The worlds are forever changed, with magic and friendship uniting the two. Harry and Frodo are hailed as legends, and an age of peace begins for both wizarding and Middle-earth alike."
> }
> [/CONTENT]
> 2024-02-23 18:34:52.681 | INFO     | metagpt.utils.cost_manager:update_cost:54 - Total running cost: $0.013 | Max budget: $10.000 | Current cost: $0.013, prompt_tokens: 371, completion_tokens: 525
> [CONTENT]
> {
>     "name": "Chapter 1: The Boy Who Lived Meets the Ring",
>     "content": "Harry Potter had been on the run since the Battle of the Seven Potters. Voldemort's Death Eaters were relentless in their pursuit, and Harry found himself in a world he never knew existed—the Shire. It was there, amidst the peaceful hobbits, that he met Frodo Baggins, a young hobbit burdened with a heavy task. Frodo had been entrusted with the One Ring, a powerful artifact that could grant its bearer unending统治, and Harry sensed the darkness at surrounded it. As the two boys shared their stories, they realized that Voldemort and Sauron were both seeking the Ring for their own nefarious purposes. Understanding the gravity of the situation, Harry and Frodo decided to join forces. Their journey to destroy the Ring had begun."
> }
> [/CONTENT]
> 2024-02-23 18:35:01.925 | INFO     | metagpt.utils.cost_manager:update_cost:54 - Total running cost: $0.013 | Max budget: $10.000 | Current cost: $0.013, prompt_tokens: 722, completion_tokens: 191
> [CONTENT]
> {
>     "name": "Chapter 1: The Boy Who Lived Meets the Ring",
>     "content": "Harry Potter had been on the run since the Battle of the Seven Potters. Voldemort's Death Eaters were relentless in their pursuit, and Harry found himself in a world he never knew existed—the Shire. It was there, amidst the peaceful hobbits, that he met Frodo Baggins, a young hobbit burdened with a heavy task. Frodo had been entrusted with the One Ring, a powerful artifact that could grant its bearer unending统治, and Harry sensed the darkness at surrounded it. As the two boys shared their stories, they realized that Voldemort and Sauron were both seeking the Ring for their own nefarious purposes. Understanding the gravity of the situation, Harry and Frodo decided to join forces. Their journey to destroy the Ring had begun."
> }
> [/CONTENT]
> ```


You are right;

I changed the default language of Field, causing zhipiai to return a hexadecimal reply starting with u; After restoring the default English, the characters returned by zhipuai are normal.
