### ISSUE TITLE
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config

### ISSUE THREAD

**Issue by loyalty-fox** [geekan/MetaGPT#916]
**Bug description**
pip install metagpt后我尝试运行官方文档给的第一个例子，出现了如下报错：

![image](https://github.com/geekan/MetaGPT/assets/56210508/a8b26964-e439-4e67-8149-1bc191bec9f5)

**Bug solved method**

我尝试过降低pydantic版本到1.x但是又会出现其他的一些包不兼容的问题，请问有人知道问题出现在哪吗？

**Screenshots or logs**

出现问题的地方：
![image](https://github.com/geekan/MetaGPT/assets/56210508/68b57959-abe2-488d-afc9-655ed10c45d8)

**Comment by loyalty-fox** [comment]
> 我在执行 `metagpt --init-config` 也报了这个错误，手动创建 `/.metagpt/config2.yaml` 后，正常使用。 @loyalty-fox
> 
> ref: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html

感谢你的建议，之前我只是手动在目录下创建了config/config2.yaml 文件，没有执行`metagpt --init-config` 命令，执行了该命令之后，它自动在我的C:\Users\username下创建了你说的`/.metagpt/config2.yaml`之后 ，就能正常运行程序了。
此外我是windows系统尝试执行这个项目的，不知道为什么需要在c盘下添加配置文件而不是项目当前目录下（我尝试直接把.metagpt文件整个从c盘迁移到项目路径下，就会报相同的错误）。

**Comment by geekan** [comment]
This problem mainly comes from compatibility with pip installation users (they do not have this directory on the disk). But in fact you should also be able to configure config/config2.yaml directly.

**Comment by Icecoffe1** [comment]
这样配置后报错：
Traceback (most recent call last):
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tjz/.cursor-server/extensions/ms-python.debugpy-2024.6.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/tjz/.cursor-server/extensions/ms-python.debugpy-2024.6.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/tjz/.cursor-server/extensions/ms-python.debugpy-2024.6.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/tjz/.cursor-server/extensions/ms-python.debugpy-2024.6.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/tjz/.cursor-server/extensions/ms-python.debugpy-2024.6.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/tjz/.cursor-server/extensions/ms-python.debugpy-2024.6.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/mnt/mydisk/tjz/llm-project/LangChain/Tianji/test/agents/metagpt/answerBot_test_case.py", line 8, in <module>
    from tianji.agents.metagpt_agents.answerBot import AnswerBot
  File "/mnt/mydisk/tjz/llm-project/LangChain/Tianji/tianji/agents/metagpt_agents/answerBot/__init__.py", line 1, in <module>
    from .role import AnswerBot
  File "/mnt/mydisk/tjz/llm-project/LangChain/Tianji/tianji/agents/metagpt_agents/answerBot/role.py", line 6, in <module>
    from metagpt.roles.role import Role, RoleReactMode
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/site-packages/metagpt/roles/__init__.py", line 9, in <module>
    from metagpt.roles.role import Role
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/site-packages/metagpt/roles/role.py", line 30, in <module>
    from metagpt.actions import Action, ActionOutput
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/site-packages/metagpt/actions/__init__.py", line 10, in <module>
    from metagpt.actions.action import Action
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/site-packages/metagpt/actions/action.py", line 15, in <module>
    from metagpt.actions.action_node import ActionNode
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/site-packages/metagpt/actions/action_node.py", line 21, in <module>
    from metagpt.llm import BaseLLM
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/site-packages/metagpt/llm.py", line 11, in <module>
    from metagpt.context import Context
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/site-packages/metagpt/context.py", line 14, in <module>
    from metagpt.config2 import Config
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/site-packages/metagpt/config2.py", line 151, in <module>
    config = Config.default()
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/site-packages/metagpt/config2.py", line 100, in default
    final = merge_dict(dicts)
  File "/mnt/mydisk/tjz/anaconda3/envs/tianji/lib/python3.9/site-packages/metagpt/config2.py", line 147, in merge_dict
    result.update(dictionary)
TypeError: 'NoneType' object is not iterable

**Comment by Icecoffe1** [comment]
yaml中需要写入什么
