### ISSUE TITLE
Code review failed to parse code

### ISSUE THREAD

**Issue by zhongyangfu** [geekan/MetaGPT#95]
`python startup.py "Write a cli snake game" --code_review True`

OPENAI_API_MODEL: "gpt-3.5-turbo-16k"

2023-07-29 15:18:43.424 | ERROR    | metagpt.utils.common:parse_code:170 - ```.*?\s+(.*?)``` not match following text:
2023-07-29 15:18:43.425 | ERROR    | metagpt.utils.common:parse_code:171 - ## Code: game.py

```python
import curses
import random
import time
import argparse


class Snake:
    def __init__(self):
        self.body = [(0, 0)]
        self.direction = (1, 0)

    def move(self):
        """
        Move the snake in the current direction.
        """
        head = self.body[0]
        dx, dy = self.direction
        new_head = (head[0] + dx, head[1] + dy)
        self.body.insert(0, new_head)
        self.body.pop()

    def change_direction(self, key):
        """
        Change the direction of the snake based on the key input.
        """
        if key == 'w':
            self.direction = (0, -1)
        elif key == 's':
            self.direction = (0, 1)
        elif key == 'a':
            self.direction = (-1, 0)
        elif key == 'd':
            self.direction = (1, 0)

    def grow(self):
        """
        Grow the snake by adding a new segment to the body.
        """
        tail = self.body[-1]
        dx, dy = self.direction
        new_segment = (tail[0] - dx, tail[1] - dy)
        self.body.append(new_segment)

    def is_collision(self):
        """
        Check if the snake has collided with itself.
        """
        head = self.body[0]
        return head in self.body[1:]

    def reset(self):
        """
        Reset the snake to its initial state.
        """
        self.body = [(0, 0)]
        self.direction = (1, 0)


class Food:
    def __init__(self):
        self.position = (0, 0)

    def generate_position(self, snake_body):
        """
        Generate a random position for the food that is not occupied by the snake.
        """
        while True:
            x = random.randint(0, 9)
            y = random.randint(0, 9)
            if (x, y) not in snake_body:
                self.position = (x, y)
                break


class Menu:
    def __init__(self, game_modes, difficulty_levels):
        self.game_modes = game_modes
        self.difficulty_levels = difficulty_levels
        self.selected_game_mode = None
        self.selected_difficulty_level = None

    def select_game_mode(self, index):
        """
        Select the game mode based on the index.
        """
        if index < len(self.game_modes):
            self.selected_game_mode = self.game_modes[index]

    def select_difficulty_level(self, index):
        """
        Select the difficulty level based on the index.
        """
        if index < len(self.difficulty_levels):
            self.selected_difficulty_level = self.difficulty_levels[index]

    def display_menu(self):
        """
        Display the game menu and handle user input.
        """
        stdscr = curses.initscr()
        curses.curs_set(0)
        stdscr.nodelay(1)
        stdscr.timeout(100)

        selected_option = 0

        while True:
            stdscr.clear()
            stdscr.addstr(0, 0, "Select game mode:")
            for i, game_mode in enumerate(self.game_modes):
                if i == selected_option:
                    stdscr.addstr(i + 1, 0, f"> {game_mode}")
                else:
                    stdscr.addstr(i + 1, 0, f"  {game_mode}")

            stdscr.refresh()

            key = stdscr.getch()

            if key == curses.KEY_UP:
                selected_option = (selected_option - 1) % len(self.game_modes)
            elif key == curses.KEY_DOWN:
                selected_option = (selected_option + 1) % len(self.game_modes)
            elif key == ord('\n'):
                self.select_game_mode(selected_option)
                break

        selected_option = 0

        while True:
            stdscr.clear()
            stdscr.addstr(0, 0, "Select difficulty level:")
            for i, difficulty_level in enumerate(self.difficulty_levels):
                if i == selected_option:
                    stdscr.addstr(i + 1, 0, f"> {difficulty_level}")
                else:
                    stdscr.addstr(i + 1, 0, f"  {difficulty_level}")

            stdscr.refresh()

            key = stdscr.getch()

            if key == curses.KEY_UP:
                selected_option = (selected_option - 1) % len(self.difficulty_levels)
            elif key == curses.KEY_DOWN:
                selected_option = (selected_option + 1) % len(self.difficulty_levels)
            elif key == ord('\n'):
                self.select_difficulty_level(selected_option)
                break

        curses.endwin()


class Game:
    def __init__(self):
        self.score = 0
        self.high_score = 0
        self.speed = 1
        self.is_paused = False
        self.game_mode = "easy"
        self.difficulty_level = "medium"
        self.snake = Snake()
        self.food = Food()

    def start_game(self):
        """
        Start the game loop.
        """
        while True:
            self.update()
            self.display_score()
            self.check_collision()
            self.snake.move()
            self.generate_new_food_position_if_eaten()
            self.display_game_screen()
            self.delay_for_game_speed()

    def update(self):
        """
        Update the game state.
        """
        if self.is_paused:
            self.display_pause()
        elif self.is_game_over():
            self.display_game_over()
            self.reset_game()
        elif self.is_game_mode_changed():
            self.display_menu()

    def handle_input(self, key):
        """
        Handle user input during the game.
        """
        if key == 'q':
            self.quit_game()
        elif key == 'p':
            self.pause_game()
        elif key in ['w', 's', 'a', 'd']:
            self.snake.change_direction(key)

    def check_collision(self):
        """
        Check for collision with the snake's body or the game boundaries.
        """
        if self.snake.is_collision() or self.is_collision_with_boundaries():
            self.game_over()

    def game_over(self):
        """
        End the game and update the high score if necessary.
        """
        if self.score > self.high_score:
            self.high_score = self.score
        self.display_game_over()
        self.reset_game()

    def pause_game(self):
        """
        Pause the game.
        """
        self.is_paused = True

    def resume_game(self):
        """
        Resume the paused game.
        """
        self.is_paused = False

    def display_score(self):
        """
        Display the current score and high score.
        """
        print(f"Score: {self.score}   High Score: {self.high_score}")

    def display_game_over(self):
        """
        Display the game over message.
        """
        print("Game Over")

    def display_pause(self):
        """
        Display the pause message.
        """
        print("Game Paused")

    def display_menu(self):
        """
        Display the game
Traceback (most recent call last):
  File "/Users/zyf/.pyenv/versions/3.10/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/zyf/ai/MetaGPT/metagpt/actions/write_code.py", line 72, in write_code
    code = CodeParser.parse_code(block="", text=code_rsp)
  File "/Users/zyf/ai/MetaGPT/metagpt/utils/common.py", line 172, in parse_code
    raise Exception
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zyf/ai/MetaGPT/startup.py", line 36, in <module>
    fire.Fire(main)
  File "/Users/zyf/.pyenv/versions/3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/zyf/.pyenv/versions/3.10/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/zyf/.pyenv/versions/3.10/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/zyf/ai/MetaGPT/startup.py", line 32, in main
    asyncio.run(startup(idea, investment, n_round, code_review))
  File "/Users/zyf/.pyenv/versions/3.10.9/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/zyf/.pyenv/versions/3.10.9/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/zyf/ai/MetaGPT/startup.py", line 20, in startup
    await company.run(n_round=n_round)
  File "/Users/zyf/ai/MetaGPT/metagpt/software_company.py", line 60, in run
    await self.environment.run()
  File "/Users/zyf/ai/MetaGPT/metagpt/environment.py", line 56, in run
    await asyncio.gather(*futures)
  File "/Users/zyf/ai/MetaGPT/metagpt/roles/role.py", line 239, in run
    rsp = await self._react()
  File "/Users/zyf/ai/MetaGPT/metagpt/roles/role.py", line 208, in _react
    return await self._act()
  File "/Users/zyf/ai/MetaGPT/metagpt/roles/engineer.py", line 186, in _act
    return await self._act_sp_precision()
  File "/Users/zyf/ai/MetaGPT/metagpt/roles/engineer.py", line 160, in _act_sp_precision
    code = await WriteCode().run(
  File "/Users/zyf/ai/MetaGPT/metagpt/actions/write_code.py", line 78, in run
    code = await self.write_code(prompt)
  File "/Users/zyf/.pyenv/versions/3.10/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/Users/zyf/.pyenv/versions/3.10/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/zyf/.pyenv/versions/3.10/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x11edf0670 state=finished raised Exception>]

**Comment by lybtt** [comment]
因为生成的数据和预期的不一样，多试几次就好，或者换成GPT4应该能大幅度减少这种情况。
<img width="716" alt="image" src="https://github.com/geekan/MetaGPT/assets/38394058/40f138b3-c531-4c70-9634-26403749a852">

**Comment by Hezhexi2002** [comment]
> 因为生成的数据和预期的不一样，多试几次就好，或者换成GPT4应该能大幅度减少这种情况。 <img alt="image" width="716" src="https://user-images.githubusercontent.com/38394058/257178695-40f138b3-c531-4c70-9634-26403749a852.png">

我用的第三方接口的gpt4也会出现这个错误，不知道是不是接口不稳定的原因，主要是断了之后没法接续已经生成的代码这个就很蛋疼
