### ISSUE TITLE
Exist bugs when running the example data_visualization.py

### ISSUE THREAD

**Issue by cywwycedward** [geekan/MetaGPT#964]
**Bug description**
I tried to run the example which filename is "data_visualization.py",and it noticed that aask_code() got an unexpected keyword argument 'temperature'

**Bug solved method**

**Environment information**

- LLM type and model name:ZhipuAI glm-4
- System version:Windows 10
- Python version:Conda Python 3.9.18

**Screenshots or logs**
Traceback (most recent call last):
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\utils\common.py", line 562, in wrapper
    return await func(self, *args, **kwargs)
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\role.py", line 558, in run
    rsp = await self.react()
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\role.py", line 529, in react
    rsp = await self._plan_and_act()
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\role.py", line 497, in _plan_and_act
    task_result = await self._act_on_task(task)
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\mi\interpreter.py", line 46, in _act_on_task
    code, result, is_success = await self._write_and_exec_code()
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\mi\interpreter.py", line 56, in _write_and_exec_code
    code, cause_by = await self._write_code()
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\mi\interpreter.py", line 83, in _write_code
    code = await todo.run(context=context, plan=self.planner.plan, temperature=0.0)
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\actions\mi\write_analysis_code.py", line 52, in run
    rsp = await self.llm.aask_code(messages, **kwargs)
TypeError: aask_code() got an unexpected keyword argument 'temperature'
  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\MetaGPT\metagpt\utils\common.py", line 562, in wrapper
    return await func(self, *args, **kwargs)
  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\MetaGPT\metagpt\roles\role.py", line 558, in run
    rsp = await self.react()
  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\MetaGPT\metagpt\roles\role.py", line 529, in react
    rsp = await self._plan_and_act()
  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\MetaGPT\metagpt\roles\role.py", line 497, in _plan_and_act
    task_result = await self._act_on_task(task)
  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\MetaGPT\metagpt\roles\mi\interpreter.py", line 46, in _act_on_task
    code, result, is_success = await self._write_and_exec_code()
  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\MetaGPT\metagpt\roles\mi\interpreter.py", line 56, in _write_and_exec_code
    code, cause_by = await self._write_code()
  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\MetaGPT\metagpt\roles\mi\interpreter.py", line 83, in _write_code
    code = await todo.run(context=context, plan=self.planner.plan, temperature=0.0)
  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\MetaGPT\metagpt\actions\mi\write_analysis_code.py", line 52, in run
    rsp = await self.llm.aask_code(messages, **kwargs)
TypeError: aask_code() got an unexpected keyword argument 'temperature'

During handling of the above exception, another exception occurred:

  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\MetaGPT\metagpt\utils\common.py", line 584, in wrapper
    raise Exception(format_trackback_info(limit=None))
  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\data_visualization.py", line 8, in main
    await mi.run(requirement)
  File "D:\TreasureOfDDLer\CODE\python\TouristAgent\data_visualization.py", line 14, in <module>
    asyncio.run(main(requirement))
Exception: Traceback (most recent call last):
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\utils\common.py", line 562, in wrapper
    return await func(self, *args, **kwargs)
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\role.py", line 558, in run
    rsp = await self.react()
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\role.py", line 529, in react
    rsp = await self._plan_and_act()
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\role.py", line 497, in _plan_and_act
    task_result = await self._act_on_task(task)
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\mi\interpreter.py", line 46, in _act_on_task
    code, result, is_success = await self._write_and_exec_code()
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\mi\interpreter.py", line 56, in _write_and_exec_code
    code, cause_by = await self._write_code()
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\roles\mi\interpreter.py", line 83, in _write_code
    code = await todo.run(context=context, plan=self.planner.plan, temperature=0.0)
  File "d:\treasureofddler\code\python\touristagent\metagpt\metagpt\actions\mi\write_analysis_code.py", line 52, in run
    rsp = await self.llm.aask_code(messages, **kwargs)
TypeError: aask_code() got an unexpected keyword argument 'temperature'

**Comment by orange-crow** [comment]
aask_code() does not currently support ZhipuAI LLM, you can try openai. And we are refactoring the code to support more LLM type.

**Comment by better629** [comment]
Due to the lack of updates or replies by the user for a long time, we will close it. Please reopen it if necessary.
