### ISSUE TITLE
ollama run error

### ISSUE THREAD

**Issue by ThomasXIONG151215** [geekan/MetaGPT#966]
**Bug description**
I'm using ollama for MetaGPT, after setting up the config2.yml (associating None for API_KEY otherwise it wouldn't work) i tried using it in terminal above as well as under the downloaded MetaGPT directory, however, both tries return errors i do not quite understand.

**Environment information**

- LLM type and model name: Ollama, Llama2
- System version: Windows 11
- Python version: python 3.11.4, 

- packages version: 
- installation method:  git clone https://github.com/geekan/metagpt, pip install setup.py

**Screenshots or logs**

 metagpt "write a cli blackjack game"
2024-03-06 10:10:37.067 | INFO     | metagpt.const:get_metagpt_package_root:29 - Package root set to G:\MetaGPT\MetaGPT
c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages\langchain\vectorstores\__init__.py:35: LangChainDeprecationWarning: Importing vector stores from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.vectorstores import Chroma`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages\langchain\vectorstores\__init__.py:35: LangChainDeprecationWarning: Importing vector stores from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.vectorstores import FAISS`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages\langchain\document_loaders\__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.document_loaders import TextLoader`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages\langchain\document_loaders\__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.document_loaders import UnstructuredPDFLoader`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
c:\users\administrator\appdata\local\programs\python\python311\lib\site-packages\langchain\document_loaders\__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.document_loaders import UnstructuredWordDocumentLoader`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
2024-03-06 10:10:40.395 | INFO     | metagpt.team:invest:90 - Investment: $3.0.
2024-03-06 10:10:40.397 | INFO     | metagpt.roles.role:_act:399 - Alice(Product Manager): to do PrepareDocuments(PrepareDocuments)
2024-03-06 10:10:40.553 | INFO     | metagpt.utils.file_repository:save:60 - save to: G:\MetaGPT\MetaGPT\workspace\20240306101040\docs\requirement.txt
2024-03-06 10:10:40.555 | INFO     | metagpt.roles.role:_act:399 - Alice(Product Manager): to do WritePRD(WritePRD)
2024-03-06 10:10:40.559 | INFO     | metagpt.actions.write_prd:run:86 - New requirement detected: write a cli blackjack game
Understood! Here's the generated output for the given input:

### Project Name
game_2048

### Original Requirements
Create a 2048 game

### Search Information
-

-----

## format example
[CONTENT]
{
    "Language": "en_us",
    "Programming Language": "Python",
    "Original Requirements": "Create a 2048 game",
    "Project Name": "game_2048",
    "Product Goals": [
        "Create an engaging user experience",
        "Improve accessibility, be responsive",
        "More beautiful UI"
    ],
    "User Stories": [
        "As a player, I want to be able to choose difficulty levels",
        "As a player, I want to see my score after each game",
        "As a player, I want to get restart button when I lose",
        "As a player, I want to see beautiful UI that make me feel good",
        "As a player, I want to play game via mobile phone"
    ],
    "Competitive Analysis": [
        "2048 Game A: Simple interface, lacks responsive features",
        "play2048.co: Beautiful and responsive UI with my best score shown",
        "2048game.com: Responsive UI with my best score shown, but many ads"
    ],
    "Competitive Quadrant Chart": "quadrantChart\n    title \"Reach and engagement of campaigns\"\n    x-axis \"Low Reach\" --> \"High Reach\"\n    y-axis \"Low Engagement\" --> \"High Engagement\"\n    quadrant-1 \"We should expand\"\n    quadrant-2 \"Need to promote\"\n    quadrant-3 \"Re-evaluate\"\n    quadrant-4 \"May be improved\"\n    \"Campaign A\": [0.3, 0.6]\n    \"Campaign B\": [0.45, 0.23]\n    \"Campaign C\": [0.57, 0.69]\n    \"Campaign D\": [0.78, 0.34]\n    \"Campaign E\": [0.40, 0.34]\n    \"Campaign F\": [0.35, 0.78]\n    \"Our Target Product\": [0.5, 0.6]",
    "Requirement Analysis": "",
    "Requirement Pool": [
        [
            "P0",
            "The main code ..."
        ],
        [
            "P0",
            "The game algorithm ..."
        ]
    ],
    "UI Design draft": "Basic function description with a simple style and layout.",
    "Anything UNCLEAR": ""
}
[/CONTENT]  Great! Here's the generated output for the given input:

## nodes:

* Language: en_us (English)
* Programming Language: Python
* Original Requirements: Create a 2048 game
* Project Name: game_2048
* Product Goals:
        + Create an engaging user experience
        + Improve accessibility, be responsive
        + More beautiful UI
* User Stories:
        + As a player, I want to be able to choose difficulty levels
        + As a player, I want to see my score after each game
        + As a player, I want to get restart button when I lose
        + As a player, I want to see beautiful UI that make me feel good
        + As a player, I want to play game via mobile phone
* Competitive Analysis:
        + 2048 Game A: Simple interface, lacks responsive features
        + play2048.co: Beautiful and responsive UI with my best score shown
        + 2048game.com: Responsive UI with my best score shown, but many ads
* Competitive Quadrant Chart:
        + quadrantChart
                - title "Reach and engagement of campaigns"
                - x-axis Low Reach --> High Reach
                - y-axis Low Engagement --> High Engagement
                - quadrant-1 "We should expand"
                - quadrant-2 "Need to promote"
                - quadrant-3 "Re-evaluate"
                - quadrant-4 "May be improved"
                - Campaign A: [0.3, 0.6]
                - Campaign B: [0.45, 0.23]
                - Campaign C: [0.57, 0.69]
                - Campaign D: [0.78, 0.34]
                - Campaign E: [0.40, 0.34]
                - Campaign F: [0.35, 0.78]
                - Our Target Product: [0.5, 0.6]
* Requirement Analysis: None
* Requirement Pool:
        + P0: The main code ...
        + P0: The game algorithm ...
* UI Design draft: Basic function description with a simple style and layout.
* Anything UNCLEAR: None

I hope this helps! Let me know if you have any questions or need further clarification.
2024-03-06 10:10:57.991 | INFO     | metagpt.utils.cost_manager:update_cost:103 - prompt_tokens: 1132, completion_tokens: 1280
2024-03-06 10:10:58.056 | WARNING  | metagpt.utils.git_repository:rename_root:214 - Move G:\MetaGPT\MetaGPT\workspace\20240306101040 to G:\MetaGPT\MetaGPT\workspace\game_2048 error: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'G:\\MetaGPT\\MetaGPT\\workspace\\20240306101040'
2024-03-06 10:10:58.057 | INFO     | metagpt.utils.git_repository:rename_root:219 - Rename directory G:\MetaGPT\MetaGPT\workspace\20240306101040 to G:\MetaGPT\MetaGPT\workspace\game_2048
2024-03-06 10:10:58.064 | INFO     | metagpt.utils.file_repository:save:60 - save to: G:\MetaGPT\MetaGPT\workspace\game_2048\docs\prd\20240306101058.json
C:\Users\Administrator\AppData\Roaming\npm\mmdc
C:\Users\Administrator\AppData\Roaming\npm\mmdc.cmd
2024-03-06 10:10:58.123 | INFO     | metagpt.utils.mermaid:mermaid_to_file:48 - Generating G:\MetaGPT\MetaGPT\workspace\game_2048\resources\competitive_analysis\20240306101058.pdf..
2024-03-06 10:10:58.179 | WARNING  | metagpt.utils.mermaid:mermaid_to_file:74 - node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\@mermaid-js\mermaid-cli\src\cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0

2024-03-06 10:10:58.180 | INFO     | metagpt.utils.mermaid:mermaid_to_file:48 - Generating G:\MetaGPT\MetaGPT\workspace\game_2048\resources\competitive_analysis\20240306101058.svg..
2024-03-06 10:10:58.510 | WARNING  | metagpt.utils.mermaid:mermaid_to_file:74 - node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\@mermaid-js\mermaid-cli\src\cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0

2024-03-06 10:10:58.511 | INFO     | metagpt.utils.mermaid:mermaid_to_file:48 - Generating G:\MetaGPT\MetaGPT\workspace\game_2048\resources\competitive_analysis\20240306101058.png..
2024-03-06 10:10:58.922 | WARNING  | metagpt.utils.mermaid:mermaid_to_file:74 - node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\@mermaid-js\mermaid-cli\src\cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0

2024-03-06 10:10:58.927 | INFO     | metagpt.utils.file_repository:save:60 - save to: G:\MetaGPT\MetaGPT\workspace\game_2048\resources\prd\20240306101058.md
2024-03-06 10:10:58.930 | INFO     | metagpt.roles.role:_act:399 - Bob(Architect): to do WriteDesign(WriteDesign)
Understood! I will follow the instructions in the nodes and generate the output in the format example. Please provide me with the content for each node, and I will get started.
2024-03-06 10:11:00.011 | INFO     | metagpt.utils.cost_manager:update_cost:103 - prompt_tokens: 1374, completion_tokens: 37
2024-03-06 10:11:00.014 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:308 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-03-06 10:11:00.014 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:256 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:00.015 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:225 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:00.016 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 0.906(s), this was the 1st time calling it. exp: RetryError[<Future at 0x1b34dad9d10 state=finished raised JSONDecodeError>]
Understood! I will follow your instructions and generate the output in the format example you provided. Please provide me with the content for each node, and I will get started.
2024-03-06 10:11:01.255 | INFO     | metagpt.utils.cost_manager:update_cost:103 - prompt_tokens: 0, completion_tokens: 36
2024-03-06 10:11:01.257 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:308 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-03-06 10:11:01.258 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:256 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:01.258 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:225 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:01.260 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 2.156(s), this was the 2nd time calling it. exp: RetryError[<Future at 0x1b34dc26a10 state=finished raised JSONDecodeError>]
Understood! I will follow your instructions and generate the output in the requested format. Please provide me with the content for each node, and I will take care of the rest.
2024-03-06 10:11:03.626 | INFO     | metagpt.utils.cost_manager:update_cost:103 - prompt_tokens: 0, completion_tokens: 37
2024-03-06 10:11:03.626 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:308 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-03-06 10:11:03.628 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:256 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:03.628 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:225 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:03.629 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 4.531(s), this was the 3rd time calling it. exp: RetryError[<Future at 0x1b34dbf8190 state=finished raised JSONDecodeError>]
Of course! Here's my understanding of the given information:

**Implementation approach:**
As per the requirements, we will analyze the difficult points of the project and select an appropriate open-source framework to implement the game.

**File list:**
We only need to provide relative paths for the files. Therefore, the file list should include the following files:

* main.py
* game.py

**Data structures and interfaces:**
Using the Mermaid classDiagram code syntax, we have defined the following classes and interfaces:

* `Main`: The main class of the program, which contains a search engine, index, ranking, summary, and knowledge base.
* `SearchEngine`: A class that contains an index, ranking, and summary.
* `Index`: A class that contains a knowledge base and methods for creating and querying the index.
* `Ranking`: A class that contains methods for ranking results.
* `Summary`: A class that contains methods for summarizing results.
* `KnowledgeBase`: A class that contains methods for updating and fetching data.

We have also defined the relationships between these classes using the `->` operator.

**Program call flow:**
Using the SequenceDiagram code syntax, we have defined the following program call flow:

* The main class (`Main`) searches an engine (`SE`) for a query.
* The search engine (`SE`) queries the index (`I`) for data.
* The index (`I`) fetches data from a knowledge base (`KB`).
* The knowledge base (`KB`) updates data.
* The search engine (`SE`) ranks results.
* The ranked results are returned to the main class (`Main`).
* The main class (`Main`) summarizes the results and returns them to the search engine (`SE`).
* The search engine (`SE`) returns the summary to the user.

**Anything UNCLEAR:**
There is some uncertainty regarding third-party API integration, which needs clarification.
2024-03-06 10:11:09.732 | INFO     | metagpt.utils.cost_manager:update_cost:103 - prompt_tokens: 0, completion_tokens: 440
2024-03-06 10:11:09.733 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:308 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-03-06 10:11:09.733 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:256 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:09.734 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:225 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:09.735 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 10.625(s), this was the 4th time calling it. exp: RetryError[<Future at 0x1b34dc03910 state=finished raised JSONDecodeError>]
Understood! I will follow your instructions and generate the output in the format example you provided. Please provide me with the content for each node, and I will get started.
2024-03-06 10:11:12.534 | INFO     | metagpt.utils.cost_manager:update_cost:103 - prompt_tokens: 0, completion_tokens: 36
2024-03-06 10:11:12.535 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:308 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-03-06 10:11:12.535 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:256 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:12.536 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:225 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:12.536 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 13.437(s), this was the 5th time calling it. exp: RetryError[<Future at 0x1b34dc25090 state=finished raised JSONDecodeError>]
Understood! I will follow your instructions and generate the output in the format example you provided. Please provide me with the next node to work on.
2024-03-06 10:11:18.815 | INFO     | metagpt.utils.cost_manager:update_cost:103 - prompt_tokens: 0, completion_tokens: 31
2024-03-06 10:11:18.816 | WARNING  | metagpt.utils.repair_llm_raw_output:extract_content_from_output:308 - extract_content try another pattern: \[CONTENT\]([\s\S]*)\[/CONTENT\]
2024-03-06 10:11:18.817 | WARNING  | metagpt.utils.repair_llm_raw_output:run_and_passon:256 - parse json from content inside [CONTENT][/CONTENT] failed at retry 1, exp: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:18.817 | INFO     | metagpt.utils.repair_llm_raw_output:repair_invalid_json:225 - repair_invalid_json, raw error: Expecting value: line 1 column 1 (char 0)
2024-03-06 10:11:18.818 | ERROR    | metagpt.utils.common:log_it:476 - Finished call to 'metagpt.actions.action_node.ActionNode._aask_v1' after 19.718(s), this was the 6th time calling it. exp: RetryError[<Future at 0x1b34dc31890 state=finished raised JSONDecodeError>]
2024-03-06 10:11:18.818 | WARNING  | metagpt.utils.common:wrapper:571 - There is a exception in role's execution, in order to resume, we delete the newest role communication message in the role's memory.
2024-03-06 10:11:18.821 | ERROR    | metagpt.utils.common:wrapper:553 - Exception occurs, start to serialize the project, exp:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\utils\repair_llm_raw_output.py", line 284, in retry_parse_json_text
    parsed_data = CustomDecoder(strict=False).decode(output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\actions\action_node.py", line 427, in _aask_v1
    parsed_data = llm_output_postprocess(
                  ^^^^^^^^^^^^^^^^^^^^^^^
tenacity.RetryError: RetryError[<Future at 0x1b34dc31890 state=finished raised JSONDecodeError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\utils\common.py", line 562, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\roles\role.py", line 558, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
tenacity.RetryError: RetryError[<Future at 0x1b34dc62250 state=finished raised RetryError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\utils\common.py", line 548, in wrapper
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\team.py", line 134, in run
    await self.env.run()
Exception: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\utils\repair_llm_raw_output.py", line 284, in retry_parse_json_text
    parsed_data = CustomDecoder(strict=False).decode(output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\utils\custom_decoder.py", line 297, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\actions\action_node.py", line 427, in _aask_v1
    parsed_data = llm_output_postprocess(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\provider\postprocess\llm_output_postprocess.py", line 19, in llm_output_postprocess
    result = postprocess_plugin.run(output=output, schema=schema, req_key=req_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\provider\postprocess\base_postprocess_plugin.py", line 68, in run
    new_output = self.run_repair_llm_output(output=output, schema=schema, req_key=req_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\provider\postprocess\base_postprocess_plugin.py", line 32, in run_repair_llm_output
    parsed_data = self.run_retry_parse_json_text(content)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\provider\postprocess\base_postprocess_plugin.py", line 47, in run_retry_parse_json_text
    parsed_data = retry_parse_json_text(output=content)  # should use output=content
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1b34dc31890 state=finished raised JSONDecodeError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\utils\common.py", line 562, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\roles\role.py", line 558, in run
    rsp = await self.react()
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\roles\role.py", line 525, in react
    rsp = await self._react()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\roles\role.py", line 471, in _react
    rsp = await self._act()
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\roles\role.py", line 400, in _act
    response = await self.rc.todo.run(self.rc.history)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\actions\design_api.py", line 58, in run
    doc = await self._update_system_design(filename=filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\actions\design_api.py", line 86, in _update_system_design
    system_design = await self._new_system_design(context=prd.content)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\actions\design_api.py", line 73, in _new_system_design
    node = await DESIGN_API_NODE.fill(context=context, llm=self.llm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\actions\action_node.py", line 505, in fill
    return await self.simple_fill(schema=schema, mode=mode, images=images, timeout=timeout, exclude=exclude)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\metagpt\actions\action_node.py", line 457, in simple_fill
    content, scontent = await self._aask_v1(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1b34dc62250 state=finished raised RetryError>]

**Comment by iorisa** [comment]
These are the responses from the large model：
```text
Understood! I will follow the instructions in the nodes and generate the output in the format example. Please provide me with the content for each node, and I will get started.
```

It seems the large model's intelligence is not online and it doesn't know what it's supposed to do. 
I suggest switching to a different model or version.

**Comment by iorisa** [comment]
This issue is similar to #987,  caused by LLM not returning in the required format.
Metagpt expects an llm response as `parse json from content inside [CONTENT][/CONTENT]`

You can locate the response returned by LLM by searching for the log line `metagpt.utils.cost_manager:update_cost`, the response appears above the log.
